### ISSUE TITLE
Unable to create New Project in the Bamboo Moonshine Build

### ISSUE THREAD

**Issue by atingupta2005** [prominic/Moonshine-IDE#257] opened 2018-05-04 06:54 UTC
Hi,

I am getting an strange issue while testing the Bamboo Build of Moonshine. Below are the findings:

1. When I run Moonshine (Bamboo Build) and create a New Project, the Project creation window opens as expected but when I click on the Create button after filling the required details, the Project window closes without any project creation.

Below are few required details:

MAC Version: MACOS Sierra 10.12.6
Moonshine Bamboo Artifact:  https://bamboo.prominic.net/browse/MS-MSGMT-108/artifact/JOB1/MacOS-Installers/
Installer File:  Moonshine_Signed_OffAppStore_Distribution.pkg

Screen Recording is attached for more details:

![moonshine testing 1 11 0](https://user-images.githubusercontent.com/3568735/39615527-4a09b70e-4f94-11e8-8796-0ea20d3343e8.gif)

Please note that I have tested with Moonshine Version 1.11.0 and 1.12.0 both and the issue is in both the version.

Thanks
Atin

**Comment by piotrzarzycki21** [comment] 2018-05-04 07:35
@rat-moonshine it seems to me that this has been fixed in #256 ?

**Comment by rat-moonshine** [comment] 2018-05-04 10:27
@atingupta2005 , I see this is the sandbox issue you're facing with macOS. I tried the following things and did able to reproduce your situation:

- Opened existing Moonshine
- Opened "Edit > Access Manager"
- In opening window, I choose "Revoke All Access" - this removed all my existing bookmarked/accessible sandbox paths from Moonshine
- I did a restart (just as a safe measure)
- Tried to create a project to ~/Desktop folder without selecting by any file browser dialog - at this point I don't have any access to ~/Desktop 
- I seen same scenario that Atin reported

To get access to a system path, a sandbox application must select the path through a file browser dialog.  I think we need to force the user to choose a system path in "Parent Directory" field (in project creation dialog) if there is no previous access found to user's system. But I need to discuss this in detail with @JoelProminic  towards the implementation way.

**Comment by JoelProminic** [comment] 2018-05-04 19:58
@rat-moonshine updated Moonshine to clear the Project Directory list when the user ran "Revoke All Access" from the Access Manager.

However, I am not convinced that this was the start of the problem.  @AtinProminic, do you remember using this interface in your testing?

In order to report similar problems in the future, I requested that we give an alert to the user if the target Project Directory was not accessible when creating a new project.  This should trigger when creating the project, before the form closes:

> Unable to access Project Directory (<directory>).  Please click the "Change" link and open the target directory again.

I was not able to trigger this in my test after the last update today:
1. File > New > Flex Desktop Project
2. Select a valid project directory besides the default or ~/Downloads
3. File > Access Manager
4. Revoke All Access
5. Complete the project creation.  The action fails with no error message or alert.

**Comment by rat-moonshine** [comment] 2018-05-07 09:32
The alerts which I had added before the said test, was suppose to work slight differently:

1. User may already has access to ~/Desktop
2. File > Access Manager - Revoke All Access
3. File > New > Flex Desktop Project
4. User tries to create a project at ~/Desktop where s/he do not have access anymore
5. Project creation dialog close and an alert fires saying the reason of project creation termination

The said alert was also true when project creation dialog close and no project creates due to same project folder name existence (for this we shows on-screen message anyway in the project creation dialog).

The above steps wasn't covering the scenario when all file access revoked during an already opened project creation dialog (as @JoelProminic pointed).

I gave some thought on these. Based on already existing UI structure, project creation dialog auto-close whenever a 'Create' project call sending an event to the project creation API only, this is unlikely. But I don't want to start any structure change on this regard. Thus, I did some changes to show effectively error details during file access error in macOS.

1. The above said alerts are now replaced with console error message (popup alerts wasn't looking very intuitive)
2. There were changes to file API to show console error whenever an IO/Error event during create/delete file/directory
3. Since \#2 change, some codes also able to make compact in different places
4. Project creation process changes with above checks which results following cases:

- Fresh application installed having no access to file system
- File > New > Flex Desktop Project
- Parent Directory - (default shows) - /Users/[user]/Library/Containers/com.moonshine-ide/Data/Documents - this place is good to create any project without opening through a file browser dialog
- User change the 'Parent Directory' to ~/Desktop through file browser dialog
- User able to create a new project
- (optional) User deletes the project
- File > New > Flex Desktop Project
- Parent Directory - /Users/[user]/Desktop
- File > Access Manager - Revoke All Access
- Return to the project creation tab and try to create the project with existing path set
- Throws console error - this suppose to cover @atingupta2005 's main test case now:
```
: Unable to access Parent Directory (/Users/[user]/Desktop).  Please click the "Change" link and open the target directory again.
: Project creation terminated.
```
- File > New > Flex Desktop Project
- Parent Directory - again set to its default - /Users/[user]/Library/Containers/com.moonshine-ide/Data/Documents

**Comment by atinprominic** [comment] 2018-05-09 07:42
Hi,

I have tested it again using the latest Bamboo built and found that the issue is now resolved

Thanks

**Comment by atinprominic** [comment] 2018-05-09 07:54
I have found an issue that if I create the project without manually re-selecting the path to Parent Directory, it behaves wrong as reported. Once I re-select the same directory using "Change" option, it behaves as expected. Attached is the screen recording.
![vereposition090518](https://user-images.githubusercontent.com/34882311/39802701-5819c928-538c-11e8-8642-85763aea087e.gif)

**Comment by piotrzarzycki21** [comment] 2018-05-09 08:12
@atingupta2005 please record again that GIF with whole area of Moonshine. I really don't see what you are doing.

**Comment by atinprominic** [comment] 2018-05-09 08:30
Hi

 

I have tried multiple times but the issue is not occurring now. It seems that it occurs only a few times. I have restarted Moonshine as well but the issue reported is not occurring again.

 

I will record a video again if the issue appears again

 

Thanks
Atin

 

 

----- Original message -----

**Comment by rat-moonshine** [comment] 2018-05-09 08:56
Please, try to do with a fresh installation or whatever you may have did before recording your earlier GIF to revoke your earlier file system access @atingupta2005 , and make sure your recorded GIF also has the console area in frame.

Do you remember if you have seen any error report to console during your following report:

> I have found an issue that if I create the project without manually re-selecting the path to Parent Directory, it behaves wrong as reported. Once I re-select the same directory using "Change" option, it behaves as expected. Attached is the screen recording.

**Comment by rat-moonshine** [comment] 2018-05-09 10:07
I see another scenario where we'll need to alert the user on lost file system access (as we did in case of new project creation):

- Create new projects and have them opened to the sidebar
- Make sure they run well
- File > Access Manager - Revoke All Access
- Try to 'Build & Run' any opened project
- Moonshine fails silently 

I'm working on this now.

**Comment by rat-moonshine** [comment] 2018-05-09 11:37
I noticed that 'Build & Run' do has checks for un-accessible paths prior to the build. It was checking against the different file object access inside the project, but it wasn't checking the root project's path. Now, this check also added. 

Along with this, 'Revoke All Access' now alerts the user with possible outcome before continue:
```
Revoking all access may cause your projects behave unexpectedly. Are you sure you want to revoke?
Yes | No
```

We can work on the message sentence, though.

**Comment by JoelProminic** [comment] 2018-05-09 16:09
I see the new prompt on Revoke All Access, and it looks fine.   I also confirmed that I am prompted to fix the dependencies when I try to Build & Run an already open project.

**Comment by rat-moonshine** [comment] 2018-05-09 16:40
I'm closing this issue to get it release with 1.12.0. Please, re-open if found specific problem related to this.

**Closed by rat-moonshine** 2018-05-09 16:40 UTC
Labels: bug

**Comment by JoelProminic** [comment] 2018-05-09 19:33
@atinprominic, the simplest explanation for the behavior you reported is that you ran "Revoke All Access" from the File > Access Manager interface at some point during your testing.
![image](https://user-images.githubusercontent.com/24532731/39835409-aeab68f6-5395-11e8-97de-696469bbeacc.png)

Do you remember doing this?  

If not, then there may be another issue that causes the bookmarks to be removed.   Unfortunately, there is not much more we can do to prevent that case without being able to reproduce it (but the updates in this issue will make it give a better error message, at least).

**Comment by atinprominic** [comment] 2018-05-10 04:46
Hi

 

I have never done "Revoke All Access"

 

I will try to list the steps to reproduce this issue and update

 

Thanks

 

 

----- Original message -----
