### ISSUE TITLE
High priority - sort file names alphabetically in the Project list

### ISSUE THREAD

**Issue by JustinProminic** [prominic/Moonshine-IDE#650] opened 2020-01-17 02:34 UTC
@JoelProminic @rat-moonshine  @piotrzarzycki21  I thought we had talked about this a while ago.

I know we have pressing cool features to add to Moonshine, but we really need to cover this basic problem asap.

This screen shot demonstrates how difficult it is to deal with files when they are not sorted alphabetically in the project navigator at each branch in the tree:

![image](https://user-images.githubusercontent.com/30169573/72579590-2df1d380-389f-11ea-98b4-ce01778eb5a4.png)

**Comment by rat-moonshine** [comment] 2020-01-17 04:36
I believe we had sorting functionality added to the tree-view. I couldn't found the relevant issue against that but found #176 which strengthen my believe.

I'll see what have changed in between times.

**Comment by rat-moonshine** [comment] 2020-01-17 06:29
@JustinProminic I see the sorting functionality to side-bar is still present to opened projects. This includes project's folder, and folder contents. 

Since the view you've provided is showing a Java project, I checkout 'Connection Quality' from SVN to see if something is acting differently. I tested files sorted alphabetically for the project type as well. Can you provide the name of the project/path you were testing if it's already hosted to SVN (?)

The _only_ action I seen is not sort-updating is renaming a file. I'm working to fix this.

**Comment by piotrzarzycki21** [comment] 2020-01-17 07:03
> @JustinProminic I see the sorting functionality to side-bar is still present to opened projects. This includes project's folder, and folder contents.
> 
> Since the view you've provided is showing a Java project, I checked-out 'Connection Quality' from SVN to see if something is acting differently (for the type of project). I tested files also sorted properly for this project type, though. Can you provide the name of the project/path you were testing if it's already on SVN (?)
> 
> Or, any information on performed action before you noticed the unsorted list (?) Even if there were an exception you noticed in console.
> 
> The _only_ action I seen is not sort-updating is renaming a file. I'm working to fix this.

Did you make those tests on released version of Moonshine? I have a filling that Justin is using that version to open this project.

**Comment by rat-moonshine** [comment] 2020-01-17 08:45
Yes, I tested by last-stable release and didn't able to reproduce the scenario. Please report, if you see any oddity at your side.

**Comment by JustinProminic** [comment] 2020-01-22 00:04
Hi @rat-moonshine , I am 100% confident that this problem occurs.   Joel and I just tested it with the PrimeFaces Portal Java project, and can again reproduce it.  This is on MacOS Mojave.

If you look, the subfolders are sorted incorrectly as well:

![image](https://user-images.githubusercontent.com/30169573/72853938-74b54400-3c78-11ea-9474-23d53d07ca70.png)

**Comment by rat-moonshine** [comment] 2020-01-22 05:45
I tried to find the project under 'pni/trunk' but couldn't locate any folder named with 'primefaces' (if that is how the folder suppose to be named). Can you please point me to the location, Justin (?)

**Comment by rat-moonshine** [comment] 2020-01-22 06:50
Okay, I did a checkout of the project after receiving the path from Justin. During my tests I also pasted my random files/folders into the directory using context-menu 'Paste'. The sorting appears correct to me, however:

![image](https://user-images.githubusercontent.com/24370870/72870747-0a9bae00-3d0f-11ea-91b2-c2be990d2041.png)

Using El Capitan, I'm wondering if this something special in case of Mojave where `File` system behave differently (?)

I think I need some test in Mojave, Justin:

Please, create any file/folder inside the folder where sorting appears broken, this will force-sort the parent folder where the file/folder being created. Please, let me know the result after this.

**Comment by JoelProminic** [comment] 2020-01-23 21:13
I can reproduce this with my laptop running macOS High Sierra, with the latest nightly AppStore build of Moonshine.  (Unfortunately, I can't attach an image right now).  Interestingly, I see that the sorting is exactly the same as what @JustinProminic showed in his screenshot.

**Comment by rat-moonshine** [comment] 2020-01-24 10:54
> I can reproduce this with my laptop running macOS High Sierra, with the latest nightly AppStore build of Moonshine. (Unfortunately, I can't attach an image right now). Interestingly, I see that the sorting is exactly the same as what @JustinProminic showed in his screenshot.

I'm hoping to able to reproduce this myself when upgrade to Mojave.

**Comment by JoelProminic** [comment] 2020-01-29 22:02
Here is a test project that you can use to repeat this problem on macOS High Sierra or later:
[2020_01_29__TestSidebarSort.zip](https://github.com/prominic/Moonshine-IDE/files/4130913/2020_01_29__TestSidebarSort.zip)
![image](https://user-images.githubusercontent.com/24532731/73401424-be251500-42b0-11ea-890f-fed43b1316f4.png)

**Comment by JustinProminic** [comment] 2020-01-30 08:31
Hi @rat-moonshine please prioritize getting your MacOS upgraded to Mojave so you can reproduce this issue.  It is vital we get this resolved ASAP. @piotrzarzycki21 please also upgrade your MacOS.

Be sure to use a Time Machine backup of your complete install to a USB disk before you attempt to upgrade, in case you have to roll-back for some reason.

**Comment by piotrzarzycki21** [comment] 2020-01-30 11:09
I was able to reproduce that issue on Mac OS Mojave. It looks like there are differences in terms of how sorting is working on Mac vs Windows in ArrayCollection - in relation with TreeView. I think behavior on Mac is actually more correct than on windows. 

We are providing set of projects in ArrayCollection, along with folders which in Tree are treat as a children. We are applying sorting on ArrayCollection, but it is only applied to the root items in that tree. Children are stored in Array not ArrayCollection which we have sorting ON.  It is mysterious to me why children on windows gets sorted, but they shouldn't actually. 

I will reopen that issue for tests and comments.

**Comment by rat-moonshine** [comment] 2020-01-30 12:36
@JustinProminic I'm on my plan to upgrade my OS (it is something I particularly waiting for a long time), the new HDD will reach to me by coming Monday.

It is possible that Windows and macOS returns item-ordering differently. Furthermore, since we hadn't notice this issue in earlier version of macOS, it is also possible that the trend has changed with more recent version of the macOS. Although, it's a guesswork, Piotr.

I need to talk to Joel to help me remember something.

**Comment by piotrzarzycki21** [comment] 2020-01-30 15:26
Currently bamboo build seems to do not get my changes. It's probably failing. If it gets proper rebuild fix should be in place.

**Comment by rat-moonshine** [comment] 2020-01-30 15:56
> Currently bamboo build seems to do not get my changes. It's probably failing. If it gets proper rebuild fix should be in place.

I see your commit successfully build as Build#1557. Latest build should be Build#1559 in a few minutes, so your changes already in last known successfully build.

**Comment by piotrzarzycki21** [comment] 2020-01-30 16:12
Sorry for the noise. I just tried build on Mac and fix seems to working, but not fully. When previously opened project opens you will see unsorted folders, but open and close one of the node get's children sort. I need to improve that.

**Comment by rat-moonshine** [comment] 2020-01-30 16:19
> Sorry for the noise. I just tried build on Mac and fix seems to working, but not fully. When previously opened project opens you will see unsorted folders, but open and close one of the node get's children sort. I need to improve that.

Try to change ordering [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L1116). Of course, projects those already have a saved tree-cookies might came as they are; I would suggest to spend not much on that; Let's standardise the fix for the projects opens from now on.

I was thinking by the same fix, I see you already thought that ;)

**Comment by piotrzarzycki21** [comment] 2020-01-30 16:28
> Try to change ordering [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L1116). Of course, projects those already have a saved tree-cookies might came as they were; I would suggest to spend not much on that; Let's standardise the fix for the projects opens from now on.
> 
> I was thinking by the same fix, I see you already thought that ;)

It's the same when I'm opening node, so I don't won't to increase amount of using sort logic. 
I just committed some fix which should improve all of that. I agree it's enough time spend on this. I look froward when Joel will test that.

**Comment by piotrzarzycki21** [comment] 2020-01-30 16:29
Build with fix should be: ac67953fee8909bad95dbcc42f10e981aa660540

**Comment by JoelProminic** [comment] 2020-01-30 17:21
When I first reopened the test project, I found that the .java files were sorted properly, but the directories still had the old sort.  This persisted after I closed and reopened the project and Moonshine.  It seems that the sort was saved along with the expanded directories for the project.

If I refresh the src directory, I can force the sort to update as well.  When I open a fresh project, the sorting is also correct.   So, this should work fine, as long as users refresh any previously existing projects.

**Comment by JoelProminic** [comment] 2020-01-30 17:32
After some more testing, and suggestions from @rat-moonshine, I found this behavior:
1. Close Moonshine, delete the cookies, and reopen Moonshine.  This is needed so that you can do a fresh test of the test project
2. Open a project that has the sorting bug, and explore the tree.  The sorting for both directories and files is correct
3. Close and reopen the project
4. The expanded folders will reopen.  BUG:  the folders and files are not sorted incorrectly.  The sorting seems the same as for the original issue.

**Comment by piotrzarzycki21** [comment] 2020-02-03 07:52
I have spend lot's of time on that. On mac when I'm opening the project initially neasted children are not sorted. I cannot figure out how to force sorting initially. When you interact with Tree - open/close some tree node it gets sorted, cause there is force on that event. I will take another shot of looking into that today. 

![last](https://user-images.githubusercontent.com/24554795/73634906-8e845d00-4662-11ea-959a-7014c70ccf65.png)

**Comment by rat-moonshine** [comment] 2020-02-03 09:10
> I cannot figure out how to force sorting initially. When you interact with Tree - open/close some tree node it gets sorted, cause there is force on that event.

I think we should not spend on initial sorting to the file-list; As this won't full-proof unless you do two things - 1) Having the full hierarchy of tree-list, 2) Sorting them - both the points could be time consuming if a project with large number of files. 

I think sorting the children on node-open is the way to go. When a project loads to sidebar, loads in collapsed manner. So opening nodes will able us sort on demand way. Once opened and sorted this will saved into tree-cookies can reload next time.

**Comment by piotrzarzycki21** [comment] 2020-02-03 14:32
> I think we should not spend on initial sorting to the file-list; As this won't full-proof unless you do two things - 1) Having the full hierarchy of tree-list, 2) Sorting them - both the points could be time consuming if a project with large number of files.
> 
> I think sorting the children on node-open is the way to go. When a project loads to sidebar, it loads in collapsed manner. So opening nodes will able us sort on demand way. Once opened and sorted this will saved into tree-cookies which can use to reload next time.

Well there is scenario where project initially is not closed. If you open some old project and previously nodes were opened - those one won't be sorted. I bet Justin run into that scenario same as me. However maybe you are right that there is no sense spend on that more time. Let's see on a call if my solution is enough so far.

**Comment by rat-moonshine** [comment] 2020-02-03 15:35
Yes, I understand that old opened projects will keep opening as they were. That is what I mentioned earlier that let's make the rule solid for project opens from 'now-on' (previous opened project cookies can clear at any time).

**Comment by JoelProminic** [comment] 2020-02-03 16:41
We need to get the sorting working when reopening projects as well.  This is something that will regularly trigger during normal usage, and @JustinProminic  is going to immediately see the same behavior again if he does a test.

If this is going to require more time to fix, then we can consider continuing this in the next milestone.

**Comment by rat-moonshine** [comment] 2020-02-03 17:05
> 
> 
> We need to get the sorting working when reopening projects as well. This is something that will regularly trigger during normal usage, and @JustinProminic is going to immediately see the same behavior again if he does a test.
> 
> If this is going to require more time to fix, then we can consider continuing this in the next milestone.

I want to re-stress on our discussion/explanation to make sure we are on same boat, @JoelProminic . Opening any project _will_ show items properly sorted, but from now on. So, if you upgrade to newer Moonshine build:

1. If you have an opened project in sidebar from a long time (ideally before the current fix applied), they will keep opening with their old saved tree-ordering, unless user do an open/close node to get the node's item sorted and re-saved
2. If you open any project from **now on**, closing and reopening projects will demonstrate you right sorting

Please, let me know if we still wants to spend on fixing the first case.

**Comment by JoelProminic** [comment] 2020-02-03 20:43
I am still seeing this behavior on macOS High Sierra, with the latest nightly non-Sandbox build (1571)
1. Open a project from an older build of Moonshine - BUG:  the directories and files are not sorted correctly
2. Refresh the project
3. Expand the tree.  The directories and files are sorted properly
4. Close and reopen the project.  BUG:  The directories and files are not sorted properly

If we can't easily resolve the case from 1, this is not a major deal, as long as we have a one-time fix.

From @rat-moonshine's last comment, this should work for brand new projects, but I found that this is not the case either:
1. Create a new Java Gradle project
2. Add multiple packages/directories and classes.  Use the list from my example project to make sure you have names that trigger the sorting issue. The sorting is correct at this point.
3. Close and reopen the project.  BUG:  the directories and files are not sorted properly

**Comment by rat-moonshine** [comment] 2020-02-04 04:52
I have my Mojave installed and running well. I can look into the macOS specific issues more.

**Comment by piotrzarzycki21** [comment] 2020-02-04 05:01
> I have my Mojave installed and running well. I can look into the macOS specific issues more.

I'm going to look into that, but in about 4h - if you till that time figure out something let me know. Maybe fresh look allows resolve this once for all.

**Comment by rat-moonshine** [comment] 2020-02-04 06:05
Thanks @piotrzarzycki21 . I just able to give a look with Mojave and able to reproduce the problem as reported by @JoelProminic .

I looked into the details a bit. If I understood correctly, we were saving tree-data by opened folder-node wise. That means even we have the folder references, that doesn't mean we will also have their children sort references. So after expanding those folder-nodes, they demands an automatic or manual sorting again. 

I just [added](https://github.com/prominic/Moonshine-IDE/commit/5eedf1bfc1343271b1e0778515e5ee01018e3751#diff-b380bd3bb50860cc0ca1c7982479f90aR212) the automatic-sort during restoration from tree-cookie data, and this seems to fix the problem in my tests. Even, this will also fix the scenario of _1_ I described [here](https://github.com/prominic/Moonshine-IDE/issues/650#issuecomment-581515732).

**Comment by piotrzarzycki21** [comment] 2020-02-04 12:58
> Thanks @piotrzarzycki21 . I just able to give a look with Mojave and able to reproduce the problem as reported by @JoelProminic .
> 
> I looked into the details a bit. If I understood correctly, we were saving tree-data by opened folder-node wise. That means even we have the folder references, that doesn't mean we will also have their children sort references. So after expanding those folder-nodes, they demands an automatic or manual sorting again.
> 
> I just [added](https://github.com/prominic/Moonshine-IDE/commit/5eedf1bfc1343271b1e0778515e5ee01018e3751#diff-b380bd3bb50860cc0ca1c7982479f90aR212) the automatic-sort during restoration from tree-cookie data, and this seems to fix the problem in my tests. Even, this will also fix the scenario of _1_ I described [here](https://github.com/prominic/Moonshine-IDE/issues/650#issuecomment-581515732).

I wanted to avoid what you did, but it looks like it's necessary. Actually my fix https://github.com/prominic/Moonshine-IDE/commit/4d693e604210d107fabb66081b762f35cf6df876 suppose to have the same action as yours and this is exactly on what I have spend so much time. In my commit I have forced (last param `true`) to make an event dispatch whenever method `expandItem` is being called. - Once it is done [onTreeItemOpen](https://github.com/prominic/Moonshine-IDE/blob/ddca7d4197343dc28778823c43de1e2ee1804416/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L1108)  should be called. - However for some reason it is not always happen. I suggest you to:
1. Change last parameter to false and try your fix
2. Check if when you clicking on some node and open it your code is not being called - Because if it is called - we will call sort two times. First [here](https://github.com/prominic/Moonshine-IDE/commit/5eedf1bfc1343271b1e0778515e5ee01018e3751) and later [here](https://github.com/prominic/Moonshine-IDE/blob/ddca7d4197343dc28778823c43de1e2ee1804416/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L1110)

**Comment by rat-moonshine** [comment] 2020-02-04 15:36
> 2. Check if when you clicking on some node and open it your code is not being called - Because if it is called - we will call sort two times. First [here](https://github.com/prominic/Moonshine-IDE/commit/5eedf1bfc1343271b1e0778515e5ee01018e3751) and later [here](https://github.com/prominic/Moonshine-IDE/blob/ddca7d4197343dc28778823c43de1e2ee1804416/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L1110)

My impression was the [latter](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/utils/CustomTree.as#L192) calls only during project open/import situation. Correct me if I'm wrong.

**Comment by piotrzarzycki21** [comment] 2020-02-04 15:53
> I'm not sure at this moment what are the implication of false|true arguments in expandItem method, but if this to trigger item-open event to Tree then perhaps it's makes sense to set the event bubble=false [here](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/utils/CustomTree.as#L211).

I wasn't talking about event buble false, last parameters is not for bubbling.

**Comment by piotrzarzycki21** [comment] 2020-02-04 15:55
> My impression was the [latter](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/utils/CustomTree.as#L192) calls only during project open/import situation. Correct me if I'm wrong.

If that's the case ok, however expandItem calls with true last parameters and your calls of sorting right after that - may end up with sorting two times. It looks like your call for sure sort Array, my changes https://github.com/prominic/Moonshine-IDE/commit/4d693e604210d107fabb66081b762f35cf6df876 didn't always raise handler of open here -> https://github.com/prominic/Moonshine-IDE/blob/ddca7d4197343dc28778823c43de1e2ee1804416/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L1110

**Comment by rat-moonshine** [comment] 2020-02-04 16:06
> If that's the case ok, however expandItem calls with true last parameters and your calls of sorting right after that - may end up with sorting two times

Yes, I understood that. I'll need to check the codes to understand what is the implication of last parameter true|false, and shall check then whether sorting triggers twice or not.

**Comment by JoelProminic** [comment] 2020-02-04 16:33
I did a test on High Sierra, and the sorting is working well for me now.  I tested on:
- Old project opening on Moonshine restart 
- closing and reopening project
- Checking out a new copy of the project from SVN

It sounds like there are some concerns about how this was implemented, but the functionality seems good.

**Comment by rat-moonshine** [comment] 2020-02-04 16:36
Yes, we just needs to check a few things, and we probably good after that.

**Comment by rat-moonshine** [comment] 2020-02-04 17:37
I tested [this](https://github.com/prominic/Moonshine-IDE/blob/828045ebecc93002742e4f95d136f24c6e4be97e/ide/MoonshineSharedCore/src/actionScripts/utils/CustomTree.as#L211) `expandItem` calls only when project opening. I confirm sending last parameter=true also do not triggers node-open event to the `Tree` component, unfortunately. I removed the last parameter.

I see even if it would work (last parameter `true`), then we would had a chance to trigger [this](https://github.com/prominic/Moonshine-IDE/blob/828045ebecc93002742e4f95d136f24c6e4be97e/ide/MoonshineSharedCore/src/components/views/project/TreeView.mxml#L1111) unnecessarily, during project open. Maybe, we could have different plan for the situation then.

**Comment by piotrzarzycki21** [comment] 2020-02-05 08:06
I'm closing this one.

**Comment by JoelProminic** [comment] 2020-06-03 18:12
We are seeing this issue again with the production 2.6.0 builds on macOS Mojave.  My steps are:
1. Open the MoonshineDESKTOPevolved project from the Moonshine source
2. Expand src/actionscripts/impls
3. Right-click on impls and click "Refresh".  BUG:  the file sorting changes and they are no longer in alphabetical order.

Before:
![image](https://user-images.githubusercontent.com/24532731/83672352-ba293c80-a59b-11ea-8b6d-99e94cdba794.png)

After:
![image](https://user-images.githubusercontent.com/24532731/83672400-d036fd00-a59b-11ea-8c5e-d7ef1d5624f0.png)

**Comment by rat-moonshine** [comment] 2020-06-04 05:04
I'm looking into this.

**Comment by rat-moonshine** [comment] 2020-06-04 08:02
This should work now.

**Comment by JoelProminic** [comment] 2020-06-08 15:34
I could not reproduce this on my tests on macOS Mojave.  I also tried:
- Refreshing the project directory
- Refreshing a "grandparent" directory
- Refreshing multiple "sibling" directories.

The sorting seemed fine for all these cases.

**Closed by JoelProminic** 2020-06-08 15:34 UTC
Labels: bug, test-ready
