### ISSUE TITLE
Add ActionScript mobile project type

### ISSUE THREAD

**Issue by joshtynjala** [prominic/Moonshine-IDE#660] opened 2020-01-30 23:31 UTC
When you create an ActionScript project, you can choose between AIR, Web, and Visual Editor.

There doesn't seem to be an option for AIR mobile.

Someone in the Starling forums asked how to migrate a Starling project (and I assume that it's pure AS3), and I'm not sure what to tell them.

https://forum.starling-framework.org/d/22221-moonshine-ide-for-starling-ios-android

**Comment by rat-moonshine** [comment] 2020-02-11 05:26
@JoelProminic @joshtynjala @piotrzarzycki21 can someone help me to understand how "visual editor" type is different to others, in ActionScript Project creation dialog (?)

![image](https://user-images.githubusercontent.com/24370870/74213009-1569b300-4cbd-11ea-9c73-0db4290a2ded.png)

**Comment by JoelProminic** [comment] 2020-02-11 17:52
I tested the branch on macOS with an App Store build.  The project created properly, and I could run it with the default options.

I could also update the window size with the options in the Run tab, but the stage size did not update, so the label was not centered.  This may be outside the scope of this issue, though.

**Comment by rat-moonshine** [comment] 2020-02-12 04:57
@JoelProminic also conclude that the 'visual editor' platform might never implemented completely, or as it was intended. I noticed 'web' and 'visual editor' platform both creates same project. I'm removing this platform for now; We can bring this to discussion again if we have clear plan for this in future.

**Comment by rat-moonshine** [comment] 2020-02-27 05:09
This issue now merged into master.

**Comment by joshtynjala** [comment] 2020-02-27 16:39
I gave it a try, and I was able to successfully add the Starling library and debug in the simulator.

**Comment by rat-moonshine** [comment] 2020-02-27 16:56
We have some stage sizing issue (in desktop simulator) which Joel pointed, when using different target-device type; Perhaps it'll raise as separate issue. A device test is pending also..

**Comment by JoelProminic** [comment] 2020-03-04 17:39
This is still waiting for a test on a device.

**Comment by rat-moonshine** [comment] 2020-03-05 11:19
Using Android device with sandbox-Moonshine, I able to run/install directly to my device. 

However, I still see it opens debug tab in Moonshine even I chose 'Build & Run'. I think we did had fix to this, but having difficulty to find the discussion.

**Comment by joshtynjala** [comment] 2020-03-05 17:42
This is how I fixed it last time: 1524bddc57ae6b35a628332e1489316aec07e87f

In DebugAdapterPlugin, event.additionalProperties.noDebug will be true if it's Build & Run.

**Comment by rat-moonshine** [comment] 2020-03-06 10:39
Thank you @joshtynjala . I have [added](https://github.com/prominic/Moonshine-IDE/commit/fcb96c27ca68e5fbaea84f301b0d7fb73aedc589#diff-e8d21cceef16051cca8fff93e02b3deaR1257) the missing 'noDebug' property during device run. This does not opens the debug panel anymore during a 'Build & Run'.

I'm closing this issue hopefully we've nothing left towards this issue.

**Comment by JoelProminic** [comment] 2020-10-05 17:09
While testing the 3.0.0 release candidate on macOS 10.14.6, I got this error when building a Actionscript Mobile project

    : Build completed successfully.
    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCFlashModulePlugin/compileModule()
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCFlashModulePlugin/projectBuildSuccessfully()
    : 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/shellData()


Steps to reproduce:
# Create a new Actionscript Mobile project.  Do not change any of the default settings
# Project > Build & Run
# BUG:  The console shows the above error
# Note:  The application launches anyway after the error.

**Comment by JoelProminic** [comment] 2020-10-05 20:01
I got the same error on a Flex Desktop project, so I moved this to a separate issue (#733 ).

**Closed by JoelProminic** 2020-10-05 20:01 UTC
Labels: enhancement, test-ready
