### ISSUE TITLE
[Run Customization] Advance run customization options for mobile projects - device debugging

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#10] opened 2017-09-12 11:04 UTC
We need to investigate on USB device debugging in Moonshine. 

Following is some of the related reads on the subject:
http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac7b2281cc12cd6bced97-8000.html
http://blogs.adobe.com/airodynamics/2012/06/13/debugging-air-applications-over-usb-on-ios/

**Comment by rat-moonshine** [comment] 2017-09-18 06:09
- Basic UI state logic has prepared for USB device debugging
- Code started to preserve certificate values
- Code started to initial install and run (no debug) on Android device through USB

**Comment by rat-moonshine** [comment] 2017-09-18 06:10
Install on device through USB (Android) is working now. No debug.

**Comment by rat-moonshine** [comment] 2017-09-18 10:57
Until now:
- More structural changes to the subject 
- Run after installation to device 
- Packaging support with given resource paths and native extension
- Basic install & run codes on iOS (no debug)

**Comment by rat-moonshine** [comment] 2017-09-19 15:36
- UI state preservation against USB devices (in "Run" section)
- Connected device detection prior to install to devices

**Comment by rat-moonshine** [comment] 2017-10-10 11:43
Codes were taken to 'master' after fixing initial conflicts.

**Comment by rat-moonshine** [comment] 2017-10-27 13:26
I shall details this later -
https://forums.adobe.com/thread/1409739
https://tracker.adobe.com/#/view/AIR-4198467

**Comment by rat-moonshine** [comment] 2017-10-30 06:23
Here's a summary to the process changes on device installation through USB due to AIR/OSX behaviour. 

NativeProcess and its Standard.OUTPUT event is unreliable and opposite in OSX, unlike in Windows. The event never fires if a given command do not returns anything to the command line. This is opposite in Windows where the event returns if a command end running no matter if its returns anything to command line or not. Since the event is not reliable and do not returns in OSX all the time, designing a chain command system is not possible by depending on the said event's return. 

Thus the NativeProcess' executable changed to use 'adt' instead. But using 'adt' in Windows can be possible only through using 'adt.jar' - where the NativeProcess' executable is supposed to be a Java file. To keep similarity between the platform codes, Moonshine now using Java as the executable and runs 'adt.jar' in both the platforms (Windows, OSX). This keeps the procedure similar and working. 

The AIR does have another problem with installation to device, though. It returns 'Installation Error: APIInternalError' everytime even used with latest AIR SDK.

This problem discussed at -
https://forums.adobe.com/thread/1409739
https://tracker.adobe.com/#/view/AIR-4198467

I've tried with latest Feathers and Flex SDKs with latest AIR SDK, but all returned same results and apparently there were no installation to device through USB in iOS. I reported my test results as well to the Adobe bug tracker issue.

Windows to Android is installing well, but OSX to iOS installation fall pending due to the said above issue.

**Comment by piotrzarzycki21** [comment] 2017-10-30 09:42
@rat-moonshine ,

Just quick question, cause you have tried things with newest AIR and that Adobe ticket is closed. It means that they didn't fix the problem ?

**Comment by rat-moonshine** [comment] 2017-10-30 10:58
I see the resolution to the issue is 'Fixed'. I don't know when they did closed it, but they anyway responding to this.

**Comment by rat-moonshine** [comment] 2017-11-29 09:10
Hi @joshtynjala ,

I think this issue is more or less is good to open for you now. I had some trouble installing app to iOS device (through USB) but it could be my certificate issue; in Android it's installing well.

The installation process to device runs through following areas (I thought to detail them here if this helps you somehow) :
- In case of mobile project, user right-click on the project root/node and choose `Settings`
- User therefore need to navigate to `Settings > Run` section in opening window
- User need to choose "Device" in `Launch Method` dropdown, s/he also need to provide requisite certificates/password etc., in given fields
- After a save in project's `Settings` window, user can `Build & Run` the project 

- Moonshine compiles the .swf file adding requisite mobile capabilities to it (`MXMLCPlugin.as`)
- Upon compilation of the .swf file, the class pass the call to `SWFLauncherPlugin.as`
- Inside `launchAIR(..)` if this found a mobile and device run - the class pass the call to the `DeviceLauncher.as` class 
- `DeviceLauncher` therefore runs requisite codes based on the user platform (iOS, Android)

In general, for debugging call, the process diverted at line number# 879 in `MXMLCPlugin.as`.

Can you please take a look, in this updated scenario, where or how we can enable the debugging in device run, as well (?)

**Comment by joshtynjala** [comment] 2017-11-30 16:14
@rat-moonshine Yes, I'll take a look!

**Comment by rat-moonshine** [comment] 2018-01-03 05:14
Hi @joshtynjala , I was wondering, if you can able to look into this after the 1.8.0 release (?)

**Comment by joshtynjala** [comment] 2018-01-03 14:58
@rat-moonshine Is this more important than trying to speed up the completion list?

**Comment by piotrzarzycki21** [comment] 2018-01-03 15:00
To me speed up the completion list is definitely more important.

**Comment by rat-moonshine** [comment] 2018-01-03 15:34
Hi @joshtynjala . I wasn't aware of your current list of things. If CC speeding up or whichever tasks what you're looking at now, then definitely this can wait until you feel you can look into it. Since this was idle for a long time, I thought to give a gentle reminder. Please, feel free to visit this per your task in hand basis.

**Comment by joshtynjala** [comment] 2018-02-21 17:54
@rat-moonshine It appears that you are incorrectly parsing the output of the `adt -devices` command. Based on your comment (copied below) and the surrounding code, it looks like you have assumed that macOS and Windows will receive different output:

``` actionscript
/*
@example
@osx
List of attached devices:
Handle	DeviceClass	DeviceUUID					DeviceName
1	iPad    	6de82fb31xxxxxxxxxxxxcc8	My iPad

@windows
list of devices attached
h7azcyxxxx32	device
*/
```

However, the different output is actually based on whether you pass `-platform android` or `-platform iOS` to the adt command. I am on macOS, and I have an Android device connected to my computer with USB, but I'm seeing output like this when I run adt manually:

```
List of devices attached
071f8b06d0084569	device
```

In `onDeviceListFound()`, it looks like you need to check the value of `isAndroid` instead of `ConstantsCoreVO.IS_MACOS`.

> I had some trouble installing app to iOS device (through USB) but it could be my certificate issue; in Android it's installing well.

Assuming that your computer runs Windows, this probably explains why you were not able to install on an iOS device.

**Comment by joshtynjala** [comment] 2018-02-21 18:00
I committed the changes I needed to make Android installation work on macOS. I have not tested iOS yet.

**Comment by rat-moonshine** [comment] 2018-02-22 06:41
@joshtynjala thank you for pointing the problem. Its true, myself I wasn't able to test Android device on macOS but Windows, and iOS on macOS, so I probably missed out the problem area that you've described. 

I hope you've uncommented the _213_ line number from https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/plugin/run/view/RunMobileSettingRenderer.mxml (which should able you to test options on device through project's Run section) (the Git version has it still uncommented - probably you're testing uncommented locally).

**Comment by joshtynjala** [comment] 2018-02-22 14:42
> probably you're testing uncommented locally

Yes, that's what I'm doing until I finish the implementation.

**Comment by rat-moonshine** [comment] 2019-10-09 06:27
I able to have application installed to USB-device after having new entitlement added:

```
<key>com.apple.security.device.usb</key>
<true/>
```

@JoelProminic , we shall be needing this in production entitlement plist file for the purpose.

However, I encountered with many a problem during my tests to this issue, which may not directly related but affect to the functionality of the issue. I'm trying to brief them here, @joshtynjala .

**Test-Environment:**
macOS: 10.11.6 (El Capitan)
Device: Android Moto E (Android 5.0.2)
_(I know the Android is old but if we able to install on it then we should debug on it, too)_ 

1. I able to "Build & Run" to the device, application installs properly and ran
2. Any second attempt of "Build & Run" never worked from Moonshine [**BUG 1**] (we can have separate issue for this). Only workaround is quit Moonshine and restart
3. If the app already install to the device, Moonshine failed to re-install during any next "Build & Run" attempt [**BUG 2**] (we can have separate issue for this):
```
: Sending to adt: -jar&&/Users/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/lib/adt.jar&&-installApp&&-platform&&android&&-package&&NewFlexMobileProject.apk
: Failure [INSTALL_FAILED_ALREADY_EXISTS]
```
4. With "Build & Debug" I able to install and start on device (after uninstalling any previous install) but pointer never stopped to any added breakpoints [**BUG 3**]:
![image](https://user-images.githubusercontent.com/24370870/66456548-90ab2600-ea8b-11e9-88b2-6ffc82553fc1.png)

For "Build & Debug" I also couldn't able to restart any second debug without being Moonshine restart. In case of debug, I received following error during any second attempt (if not Moonshine restart):
```
: Sending to adt: -jar&&/Users/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/lib/adt.jar&&-package&&-target&&apk-debug&&-storetype&&pkcs12&&-keystore&&/Users/Documents/ProminicGITBranch/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/MoonshineSelfSignedCertificate.p12&&-storepass&&moonshine&&NewFlexMobileProject.apk&&NewFlexMobileProject-app.xml&&NewFlexMobileProject.swf
: Sending to adt: -jar&&/Users/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/lib/adt.jar&&-installApp&&-platform&&android&&-package&&NewFlexMobileProject.apk
: Process error: Exception during request command: attach
: java.lang.NullPointerException
: Process error: 	at com.as3mxml.vscode.SWFDebugSession.attach(SWFDebugSession.java:814)
: 	at com.as3mxml.vscode.SWFDebugSession.attach(SWFDebugSession.java:691)
: 	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:142)
: 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:171)
: 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:118)
: 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:91)
: 	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:72)
: Exception in thread "main" java.lang.NullPointerException
: 	at com.as3mxml.vscode.debug.DebugSession.sendErrorResponse(DebugSession.java:90)
: 	at com.as3mxml.vscode.debug.DebugSession.sendErrorResponse(DebugSession.java:74)
: 	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:232)
: 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:171)
: 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:118)
: 	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:91)
: 	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:72) 
```

**Comment by JoelProminic** [comment] 2019-10-09 15:34
If we add an entitlement to the App Store version, then we'll need to worry about justifying it for the App Store review.   Do we need the entitlement if the user uses the non-sandbox build instead?  It looks like this was our solution for #479

**Comment by rat-moonshine** [comment] 2019-10-09 15:38
Since this an IDE so we might justify the necessity of the entitlement for the USB-debugging.

The non-sandbox version uses different entitlement (with sandbox off), so we can partially have the entitlement available for the non-sandbox version, but I think that would limitise the feature availability between the versions. Perhaps, we can try to justify ours reason at least once.

**Comment by joshtynjala** [comment] 2019-10-15 22:23
FYI, this week, I'm working on addressing the issues brought up with device installation and debugging.

**Comment by joshtynjala** [comment] 2019-10-16 22:08
Alright, with my latest changes, debugging on mobile devices should be more reliable. I have confirmed that it's possible the debug more than once in a single session, without restarting Moonshine. Tried with both Android and iOS.

**Comment by rat-moonshine** [comment] 2019-10-18 12:12
I spent sometime today on testing by downloading latest build version from Bamboo. Following were my tests results between sandbox and non-sandbox respectively.

Both the builds I tested with stock mobile example, providing self-signed certificate for signing, using Android device with macOS. I confirm device is detectable to macOS by running following command in Terminal:

`adt -devices -platform android`

**Sandbox build**

1. Despite of providing requisite signing options, **Build & Debug** didn't proceed for me throwing alert missing signing options. I confirm, signing certificate and password were entered properly to the project's settings
2. Upon running **Build & Run**, console throws following errors for me:
```
: Compiling NewFlexMobileProject
: Error #1009
: TypeError: Error #1009
: 	at actionScripts.plugins.vscodeDebug::VSCodeDebugProtocolPlugin/handleDisconnectOrTerminated()
: 	at actionScripts.plugins.vscodeDebug::VSCodeDebugProtocolPlugin/stop()
: 	at actionScripts.plugins.vscodeDebug::VSCodeDebugProtocolPlugin/dispatcher_stopDebugHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/startShell()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/initShell()
: 	at MethodInfo-16402()
: 	at actionScripts.utils::EnvironmentSetupUtils/executeOSX()
: 	at actionScripts.utils::EnvironmentSetupUtils/executeSetCommand()
: 	at actionScripts.utils::EnvironmentSetupUtils/executeCommandWithSetLocalEnvironment()
: 	at actionScripts.utils::EnvironmentSetupUtils/initCommandGenerationToSetLocalEnvironment()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/compileRegularFlexApplication()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/proceedWithBuild()
: 	at MethodInfo-13642()
: 	at actionScripts.utils::UtilsCore$/closeAllRelativeEditors()
: 	at MethodInfo-16394()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/buildStart()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/build()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/buildAndRun()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
: 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
: 	at actionScripts.ui.menu::MenuPlugin/redispatch()
:
: Click here to Report a Bug
: SDK path: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
: Sending to mxmlc: "/Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/mxmlc" -load-config+=obj/NewFlexMobileProjectConfig.xml -static-link-runtime-shared-libraries=true +configname=airmobile -debug=true -o bin-debug/NewFlexMobileProject.swf
: Loading configuration file /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/airmobile-config.xml
: Loading configuration file /Users/devsena/Desktop/NewFlexMobileProject/obj/NewFlexMobileProjectConfig.xml
: /Users/devsena/Desktop/NewFlexMobileProject/bin-debug/NewFlexMobileProject.swf (1697942 bytes)
: Project Build Successfully.
: Launching application NewFlexMobileProject.
: SWFLauncherPlugin cannot launch Adobe AIR application on a mobile device.
: Error: SWFLauncherPlugin cannot launch Adobe AIR application on a mobile device.
: 	at actionScripts.plugins.swflauncher::SWFLauncherPlugin/launchAIR()
: 	at actionScripts.plugins.swflauncher::SWFLauncherPlugin/launchSwf()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/testMovie()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/shellData()
:
: Click here to Report a Bug
```

**Non-sandbox build**

1. Running by **Build & Debug** prints me following to the console - as its stuck at password prompt, however signing information provided properly to the project's settings:
```
: Compiling NewFlexMobileProject
: SDK path: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
: Sending to mxmlc: "/Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/mxmlc" -load-config+=obj/NewFlexMobileProjectConfig.xml -static-link-runtime-shared-libraries=true +configname=airmobile -debug=true -o bin-debug/NewFlexMobileProject.swf
: Loading configuration file /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/airmobile-config.xml
: Loading configuration file /Users/devsena/Desktop/NewFlexMobileProject/obj/NewFlexMobileProjectConfig.xml
: /Users/devsena/Desktop/NewFlexMobileProject/bin-debug/NewFlexMobileProject.swf (1697942 bytes)
: Sending to adt: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/adt -package -target apk-debug -listen 7936 -storetype pkcs12 -keystore /Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/MoonshineSelfSignedCertificate.p12 -storepass moonshine NewFlexMobileProject.apk NewFlexMobileProject-app.xml NewFlexMobileProject.swf
: password: 
```
2. Running by **Build & Run** throws me following errors:
: SDK path: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
: Sending to mxmlc: 
```
"/Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/mxmlc" -load-config+=obj/NewFlexMobileProjectConfig.xml -static-link-runtime-shared-libraries=true +configname=airmobile -debug=true -o bin-debug/NewFlexMobileProject.swf
: Loading configuration file /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/airmobile-config.xml
: Loading configuration file /Users/devsena/Desktop/NewFlexMobileProject/obj/NewFlexMobileProjectConfig.xml
: /Users/devsena/Desktop/NewFlexMobileProject/bin-debug/NewFlexMobileProject.swf (1697941 bytes)
: Project Build Successfully.
: Launching application NewFlexMobileProject.
: SWFLauncherPlugin cannot launch Adobe AIR application on a mobile device.
: Error: SWFLauncherPlugin cannot launch Adobe AIR application on a mobile device.
: 	at actionScripts.plugins.swflauncher::SWFLauncherPlugin/launchAIR()
: 	at actionScripts.plugins.swflauncher::SWFLauncherPlugin/launchSwf()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/testMovie()
: 	at actionScripts.plugins.as3project.mxmlc::MXMLCPlugin/shellData()
:
: Click here to Report a Bug
```

**Comment by joshtynjala** [comment] 2019-10-18 16:17
I guess that's what I get for testing on Windows only! 😉

**Comment by joshtynjala** [comment] 2019-10-21 18:08
The exceptions thrown when choosing Build & Run should now be resolved.

I cannot reproduce the issue where the signing options. On both Windows and macOS, I can successfully activate Build & Debug using both Android and iOS devices. Confirmed that it displays console output and stops at breakpoints.

**Comment by rat-moonshine** [comment] 2019-10-22 05:51
I tried by downloading latest sandbox and non-sandbox builds from the Bamboo. This time I didn't seen any error, unfortunately I only returned by following messages to console, either the build I'm using:

```
: Compiling NewFlexMobileProject
: SDK path: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
: Sending to mxmlc: "/Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/mxmlc" -load-config+=obj/NewFlexMobileProjectConfig.xml -static-link-runtime-shared-libraries=true +configname=airmobile -debug=true -o bin-debug/NewFlexMobileProject.swf
: Loading configuration file /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/airmobile-config.xml
: Loading configuration file /Users/devsena/Desktop/NewFlexMobileProject/obj/NewFlexMobileProjectConfig.xml
: /Users/devsena/Desktop/NewFlexMobileProject/bin-debug/NewFlexMobileProject.swf (1697877 bytes)
: Sending to adt: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/adt -package -target apk-debug -listen 7936 -storetype pkcs12 -keystore /Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/MoonshineSelfSignedCertificate.p12 -storepass moonshine NewFlexMobileProject.apk NewFlexMobileProject-app.xml NewFlexMobileProject.swf
: password: 
```

It looks like password is not injecting to the native-process properly. 

@piotrzarzycki21 Can you able to spend some time testing this on your macOS and with Android or iOS device? With Android you can use Moonshine's self-signed certificate for packaging.

**Comment by piotrzarzycki21** [comment] 2019-10-22 08:19
@rat-moonshine I won't be able to test that. Please if it's possible proceed based on your tests.

**Comment by joshtynjala** [comment] 2019-10-22 15:03
It's very strange to me that adt is asking for your password because I can see `-storepass moonshine` in the adt command from your output.

Hmm... maybe it's because there are spaces in the path to the certificate:

/Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/MoonshineSelfSignedCertificate.p12

I'll try to escape the paths passed in this command.

**Comment by joshtynjala** [comment] 2019-10-22 16:32
I was able to reproduce the issue with spaces in the certificate path. I just pushed a fix, and it works on both Windows and macOS.

I added a new class named `CommandLineUtil` with a method named `joinOptions()`. It takes a `Vector.<String>` and returns a single `String` with all options joined. If any of the individual options contain space characters, they are escaped appropriately for the current platform. On Windows, the option is wrapped in quotes. On macOS, the space is escaped with a backslash \ character.

We should always try to use this new utility function when we're running commands, so that we can be sure that they can properly handle paths with spaces too.

**Comment by rat-moonshine** [comment] 2019-10-23 06:07
Thank you, @joshtynjala , for adding that utility class; should be helpful in different areas. 

I tested by newer builds, but I came by following problem with a fresh mobile project test:

```
: Compiling NewFlexMobileProject
: SDK path: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
: Sending to mxmlc: "/Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/mxmlc" -load-config+=obj/NewFlexMobileProjectConfig.xml -static-link-runtime-shared-libraries=true +configname=airmobile -debug=true -o bin-debug/NewFlexMobileProject.swf
: Loading configuration file /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/frameworks/airmobile-config.xml
: Loading configuration file /Users/devsena/Desktop/NewFlexMobileProject/obj/NewFlexMobileProjectConfig.xml
: /Users/devsena/Desktop/NewFlexMobileProject/bin-debug/NewFlexMobileProject.swf (1697684 bytes)
: Sending to adt: /Users/devsena/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/adt -package -target apk -storetype pkcs12 -keystore /Users/devsena/Documents/Adobe\ Flash\ Builder\ 4.7/ProminicGITBranch/Moonshine-IDE/ide/MoonshineDESKTOPevolved/build/MoonshineSelfSignedCertificate.p12 -storepass moonshine NewFlexMobileProject.apk NewFlexMobileProject-app.xml NewFlexMobileProject.swf
: /Users/devsena/Desktop/NewFlexMobileProject/bin-debug/NewFlexMobileProject-app.xml: error 301: Application descriptor missing/cannot be opened
: Adobe AIR package build has been terminated with exit code: 12
```

I see you choose to merge device-packaging codes into [MXMLCPlugin.as](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as) class file.

Upon investigation, it seems that application-descriptor file is not copying to the **bin-debug** folder during the process - this is noticeable in a fresh project situation thus the above error. 

I also noticed that you choose to call the packaging-block directly from the `shellData` [completion](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L1149); this direct call also missing one key-process which usually called by the `testMovie()` method - [copyingResources](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L1230). If we won't do this resource copying process before packaging-process, any possible run-problem may arrive for the projects using different external resources.

**Comment by joshtynjala** [comment] 2019-10-23 14:42
The debugger process now handles installation and launch, so maybe the debug plugin can dispatch a new event when it is fully connected, and we can use that event to hide the busy notification instead of whatever we're using now.

**Comment by JoelProminic** [comment] 2019-11-14 23:09
@rat-moonshine reported that he has tested this with Android, but he did not have a way to test with iOS.  Unfortunately, I can't easily test iOS either.

I don't like doing it this way, but I'm going to close the issue for the 2.5.0 release, and we can reopen it if we find iOS issues later :( .

**Closed by JoelProminic** 2019-11-14 23:09 UTC
Labels: enhancement
