### ISSUE TITLE
OnDisk "Project" menus do not populates during startup

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#710] opened 2020-06-26 05:16 UTC
In certain situations during Moonshine start, the only opened OnDisk project into sidebar lost its selection and not populates usual "Projects" menu-options against the type:

![image](https://user-images.githubusercontent.com/24370870/85823033-f403f200-b799-11ea-8e4d-7dc7a7bfe198.png)

Opening another project and re-selection the OnDisk one in the sidebar generates the expected menu-options therefore:
 
![image](https://user-images.githubusercontent.com/24370870/85823109-2a417180-b79a-11ea-8543-7b3a151f5a54.png)

**Comment by rat-moonshine** [comment] 2020-06-26 06:08
This should be fixe now. @JoelProminic please, check.

**Comment by piotrzarzycki21** [comment] 2020-06-26 09:48
What's the requirements for that so @Aszusz could test it for us. Joel is pretty busy with other stuff.

**Comment by rat-moonshine** [comment] 2020-06-26 15:06
Oh, sorry. I haven't noticed this request. Hopefully, we shall able to give a test while discussing with Joel tonight. 

You or Adrian can also give a test. Open Moonshine with one or multiple projects in sidebar, one/multiple OnDisk projects should be there. The "Project" menu should show the following option when OnDisk project selected:

![image](https://user-images.githubusercontent.com/24370870/85823109-2a417180-b79a-11ea-8543-7b3a151f5a54.png)

**Comment by JoelProminic** [comment] 2020-06-26 19:00
We did some testing today on macOS, and I wasn't able to reproduce the original issue with a single On Disk project or multiple open projects.

**Comment by Aszusz** [comment] 2020-07-01 15:12
I performed a couple of test and didn't notice the exact issue. The only problem I can see is missing "Generate Apache Royale Project":
![image](https://user-images.githubusercontent.com/7197014/86260712-ed241780-bbbd-11ea-85b3-8576b02282c4.png)

**Comment by rat-moonshine** [comment] 2020-07-01 16:20
> I performed a couple of test and didn't notice the exact issue. The only problem I can see is missing "Generate Apache Royale Project":

This could be related to missing locale for the menu option, which I actually fixed to the branch build we're testing. I'll see to update the 'master' as well. Thanks for pointing, @Aszusz .

**Comment by rat-moonshine** [comment] 2020-07-02 08:15
@Aszusz you should see the menu in master too, now.

**Comment by rat-moonshine** [comment] 2020-07-02 08:18
@Aszusz I noticed that as we haven't merged this issue yet in 'master' this available only in [features/issue_704_royale_CRUD_tabular_interface](https://github.com/prominic/Moonshine-IDE/tree/features/issue_704_royale_CRUD_tabular_interface) branch for now. Sorry, for the confusion.

**Comment by JoelProminic** [comment] 2021-06-02 19:29
I tested this on the 3.1.0 release candidate, and I haven't been able to reproduce the missing menu items for Domino On Disk Project.

The "Generate Apache Royale Project" menu item is related to #704, which has not been merged.  #704 has been put on hold for now, but we'll revisit this eventually.

Since this is a bug related to a "new" feature for 3.1.0, I am not adding a special note for in the changelog.

**Closed by JoelProminic** 2021-06-02 19:29 UTC
Labels: bug, test-ready
