### ISSUE TITLE
Perform "Replace" in "Search" view removes all indentation in result file

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#809] opened 2021-04-19 13:56 UTC
Details of that issue is baked in #801. 

It starts from sentence:

`If I replace text in this interface, it removes all indentation.`

**Comment by JoelProminic** [comment] 2021-04-19 16:17
I originaly reported this for a Java Gradle project, but I confirmed the same issue for a Flex Desktop project:
1. Create a new Flex Desktop project
2. Project > Search
3. Enter "Hello" and click Replace
4. Enter "Hi" as the replace string and click Replace
5. Check the file - all indentation is removed.

```
<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009" 
xmlns:s="library://ns.adobe.com/flex/spark" 
xmlns:mx="library://ns.adobe.com/flex/mx" minWidth="955" minHeight="600">
			   
<fx:Declarations>
</fx:Declarations>
	
<fx:Script>
<![CDATA[
			
]]>
</fx:Script>
	
<s:Label fontSize="24" fontWeight="bold" textAlign="center"
horizontalCenter="0" verticalCenter="0"
text="Hi World!"/>
</s:WindowedApplication>
```

I ran this test on macOS.

**Comment by JoelProminic** [comment] 2021-04-19 16:51
I confirmed the same behavior on Windows.

**Comment by JoelProminic** [comment] 2021-05-12 17:24
This bug can mess up the user's code, so we need to fix this sooner.   If it is a difficult fix, it can be moved to 3.2.0.

**Comment by JoelProminic** [comment] 2021-05-14 17:14
To further clarify this, if the bug is too time consuming to fix now, then disable the "Replace" button in Project > Search:
![image](https://user-images.githubusercontent.com/24532731/118305539-bab99b00-b4ad-11eb-9c93-f062a7e1bf4d.png)

And add a tooltip or other message that says something like:

> Replace is currently disabled because of a known issue.

**Comment by rat-moonshine** [comment] 2021-05-17 04:41
This should be fixed now. Please, check.

**Comment by piotrzarzycki21** [comment] 2021-05-17 08:41
> This should be fixed now. Please, check. To be clear, the alignment problem is fixed.

@rat-moonshine Please check if bamboo build is working. You have committed stuff 3h ago and it looks like build didn't kick on.

**Comment by rat-moonshine** [comment] 2021-05-17 10:56
Unfortunately, I couldn't able to RDP the Bamboo Windows build system. I see macOS build completes but has deployment errors which might @JoelProminic can resolve.

**Comment by Aszusz** [comment] 2021-05-18 11:18
> This should be fixed now. Please, check. To be clear, the alignment problem is fixed.

I tested on Flex Desktop Project and everything seems to be fine now.
Using Windows build 431.

![replace](https://user-images.githubusercontent.com/7197014/118642199-595e3880-b7db-11eb-9d8a-c2940113d9e9.png)

**Comment by piotrzarzycki21** [comment] 2021-05-18 11:29
Thanks @Aszusz . Please close issue @rat-moonshine

**Comment by rat-moonshine** [comment] 2021-05-18 18:03
Please reopen if you see any oddity, until then I'm closing this as fixed.

**Closed by rat-moonshine** 2021-05-18 18:03 UTC
Labels: bug
