### ISSUE TITLE
Add option "Scroll from Source"

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#80] opened 2017-11-28 20:16 UTC

**Comment by piotrzarzycki21** [comment] 2017-12-17 17:41
@JoelProminic , @rat-moonshine I just finished implementation of that feature. In project tree header you will see icon which allows you jump to the item based on currently opened file. I'm not closing this issue cause I would like to ask you to look into the icon which I choose - Maybe you will have better suggestion.

**Comment by rat-moonshine** [comment] 2017-12-18 07:12
In my opinion, the current "<<" icon looks like collapsing the sidebar to left. Instead, you might consider to use some crosshair type of icon (I think that is how IntelliJ also show the icon(?)). 

Out of curiosity, are you saving each tree opened folders state against each opened editor file? As I've noticed following test cases:

- Having a structure like [A] which consists of [B, C, D] sub folders
- Expanded 'A', expanded to [B, B1, B2, B3, B4] and opened file 'B4File'
- Opened 'AFile'
- Collapsed 'A'
- Being active in the 'AFile' editor clicked on the 'Scroll to source' icon (I guess the title to issue should be 'Scroll to source' instead of 'Scroll from source')
- 'A' expanded, highlighted 'AFile'
- I also see [B, B1, B2, B3, B4] also expanded without a reason

**Comment by piotrzarzycki21** [comment] 2017-12-18 09:12
@rat-moonshine I just change icon as you suggested - take a look.
That option in intellij is called "Scroll from Source" - Initially when I was checking it - the name was weird to me, but when you think about it more. You are editing something in the editor (sources), so clicking on that option you are actually scrolling from source to file.

I don't save anything in that case. I'm taking active editor, splitting path to file by `File.separator` and I'm using the results to open tree folders.

**Comment by piotrzarzycki21** [comment] 2017-12-18 09:29
As for the case with opened other items, once you scroll to the one you choose. We may think about it as a Bug related to feature #86 .
If you consider following project tree:

-A (folder - root)
--B (folder)
--- FileB.mxml
--C (folder)
--- FileC.mxml

Let's say that use has opened FileC.mxlm in the editor and by clicking in the Tree:
1) Open A, B and C
2) Close A (root)
3) Click on "Scroll from Source"
In the result of that scenario, branch C will be opened **and branch B** - cause it was saved to the Shared object previously and wasn't removed when root is being collapsed (A).

Questions:
- Do you think we should remove from shared object state of children if their root is being collapsed ? (if yes raise separate Bug here)
- Do you think "Scroll from Source" should saving state of Tree ? (if yes, I will work on that as part of this feature)

**Comment by piotrzarzycki21** [comment] 2017-12-18 10:44
After consideration I think "Scroll from Source" should also save the state of the Tree. - I will implement it. First question is still remains.

**Comment by rat-moonshine** [comment] 2017-12-18 12:28
The new icon looks better now, thank you @piotrzarzycki21 .

On your first question, I tired to search an answer in Eclipse. I noticed that in running application cycle collapsing the root node do not collapse all its sub-nodes completely. That means, when you expand the root node, its sub-nodes again restored to their previous states. However, if you restart the application closing the root node, the state of sub-nodes disappears.

**Comment by piotrzarzycki21** [comment] 2017-12-18 13:19
Our logic is working pretty similar. In intellij closing root, close also children. @JoelProminic what is your thought in that matter ?

**Comment by piotrzarzycki21** [comment] 2017-12-18 18:38
I think we should leave it as is. It was always annoying to me in Intellij that when I close root of some branch other has been closed. 
Let's play with it and give feedback after some time of usage - in the mean time I'm closing that issue.

**Comment by JoelProminic** [comment] 2017-12-19 00:09
@piotrzarzycki21, @rat-moonshine 
I like the crosshair icon - this seems intuitive to me.
The tree-preserving logic seems fine to me in the current state.
In Eclipse, I remember this feature as being a toggle instead of a one-time action.  If it was enabled, the tree selection would change each time you switched tabs.  However, that behavior is often more annoying than helpful, so I tend to just double click the toggle to go to the current file only when I need this feature.  So, the current button makes sense to me, but there may be some demand for "locking" this behavior from other users.

**Comment by atinprominic** [comment] 2017-12-27 08:35
Hi

I tested this functionality and its working good. But I have few improvement suggestions:

 - The use is not able to understand at first glance what the icon labelled - "Scroll from Source" is all about. So there should be some more information there to guide about it.
- I think we should use some more meaningful name of it so that the user can figure out what it does. We can label it like - "Navigate in Project Explorer"
 - We should also change its position somewhere in the working pane. That we user will easily locate it

Thanks
Atin

**Comment by piotrzarzycki21** [comment] 2017-12-28 10:39
"Scroll from Source" is well known people who are working with Intellij, does that feature exists in Flash Builder ? How does it call ?
In Visual Studio Code that options is configurable from settings and it's called 
"explorer.autoReveal".
In Visual Studio 2017 that options is being called "Sync with Active Document".

I'm not sure whether "Navigate in Project Explorer" is the correct name from the language point of view - it would be great if @JoelProminic could look into that.

As for the position, please suggest something ? I thing we will have couple of more options in the header of Project Tree.

**Comment by JoelProminic** [comment] 2017-12-28 18:40
I agree that "Scroll from Source" is not immediately clear, though there is definitely an advantage to using a term from an existing IDE.   I didn't worry about this before because I felt that the action would be clear if the user tried the button.  I can understand if some users would be hesitant to try an unknown button, though.

"Navigate in Project Explorer" and "Auto Reveal" seem too vague to me.

"Sync with Active Document" is probably the most clear of the mentioned options, but I don't think I would be able to figure out what this meant without trying the button.

Brainstorming my own label options, I came up with:
- "Select open file".  "open file" could be interpreted as any of the open tabs, though.
- "Select current file".  I think "current file" would be interpreted as the file currently selected in the sidebar, though, so this label would be unclear

"Select" could be replaced with "Find" or "Show".  I think any of these options would be clear enough, and the details would become obvious when the action was used.
- Select:  Matches the actual action, but doesn't necessarily imply show.  
- Find:  Matches user's expected intent, but could be confused with the Find/Search actions
- Show:  Matches user's expected intent, but doesn't imply selection

Alternatively, we could move the button to the tabs, and set the label to "Select in sidebar".  I think this is the clearest label, but it would be a change from the "normal" behavior.  Maybe this would be better as an additional feature.

As you can probably see, I don't have a strong opinion on this.  I think I prefer "Select open file" from the above options, but I am open to more feedback.

**Comment by rat-moonshine** [comment] 2017-12-28 19:09
In my opinion, an amount of confusion created against the word is because of the icon/button's position. If it would have against each tab then we could say something like "Reveal in the project/sidebar" (but this is not something that can accompany with each tab, too). So, any word might left an amount of uncertainty what against it meant to (unless user self-explore this after using once or twice).

**Comment by piotrzarzycki21** [comment] 2017-12-29 10:56
I will change the option tool tip to "Select open file" - Really like the idea. In my opinion having that option in each opened Tab should be out of question. I cannot imagine anything more on the tabs than "Name of the file" + Close button. 
- We will have less space for the name 
- We are adding there possibility to click on the different icon than close

**Closed** 2017-12-29 11:03 UTC
Labels: enhancement

**Comment by JoelProminic** [comment] 2017-12-29 17:27
I confirmed the tooltip was updated.   

@piotrzarzycki21, I understand your point about adding clutter to the tabs.   If we still want to add a corresponding button to the tabs, then we could add it in the right-click menu.  If it is not visible by default, though, I suspect it won't get as much use as the "Select open file" button.
