### ISSUE TITLE
Issues with Go To Definition Functionality 

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#460] opened 2019-02-18 22:51 UTC
I noticed this behavior during my Moonshine testing today (1.16.0 release, OS X Yosemite and Windows 10).  Some of this is related to #298, but I also included my findings for CMD-Click/CTRL-Click and Go To Definition
1. Close all projects and restart Moonshine
2. Create a new Flex Desktop Project
3. Create a new folder in src, called "test"
4. Create a new AS3 Class in src/test, called TestClass
5. In the original class, add a reference to TestClass in <fx:Script>:  public var testClass:TestClass = new TestClass();
6. In the original class, CMD-Click or CTRL-Click on TestClass - the class file opens, and the cursor is put at the top of the file.  I expected to see the cursor on the class name, but this behavior is reasonable
7. In the original class, CMD-Click or CTRL-Click on TestClass() - BUG:  the class opens, but the cursor is placed at the top of the file rather than on the constructor
8. In the original class, put the cursor on TestClass and select Edit > Go To Type Definition - BUG:  Error #1034
9. In the original class, put the cursor on TestClass() and select Edit > Go To Definition - BUG:  Error #1034

```
	<fx:Script>
		<![CDATA[
			import test.TestClass;
			public var testClass:TestClass = new TestClass();
		]]>
	</fx:Script>
```

    : Error #1034
    : TypeError: Error #1034
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.utils::KeyboardShortcutManager/dispatch()
    : 	at actionScripts.utils::KeyboardShortcutManager/stopEvent()
    : 	at actionScripts.ui.menu::MenuPlugin/redispatch()
    :
    : Click here to Report a Bug

I see similar behavior for Java Maven projects (after working around the class creation issue, #457).

**Comment by joshtynjala** [comment] 2019-03-04 18:48
> 6/7 the class opens, but the cursor is placed at the top of the file

This bug appears to be introduced in commit 74959edc55b18184a94790a9e26ef6105cabdc8f

It does not set the atLine property unless files.length > 1. I don't know if that's supposed to be > 0 or if it should be something else, but I'm moving it back out because it probably should never be ignored if passed in as one of the parameters!

**Comment by joshtynjala** [comment] 2019-03-04 18:55
I could not reproduce Error #1034, so this one may already be fixed.

In case this comes up again, Error #1034 with full debug text is as follows:

> Error #1034: Type Coercion failed: cannot convert to *[name of class]*

Based on the stack trace, it looks some some event listener is expecting a different event type than what is dispatched.

**Closed** 2019-03-04 18:55 UTC
Labels: bug
