### ISSUE TITLE
Add EASY AND FOOLPROOF support for Royale nightly builds

### ISSUE THREAD

**Issue by JustinProminic** [prominic/Moonshine-IDE#653] opened 2020-01-22 00:07 UTC
We have apparently reported and closed this one before.

We must fix this ASAP so people can EASILY use the nightly build of Royale with Moonshine.

Here is the SDK Installer issue, again:

https://github.com/prominic/Moonshine-SDK-Installer/issues/12

**Comment by piotrzarzycki21** [comment] 2020-01-22 08:57
@rat-moonshine We should continue our discussion. We have had some plan on that we need to agree on something - Let's allocate some time when priorities on the meeting will be revealed.

**Comment by rat-moonshine** [comment] 2020-01-22 11:50
> @rat-moonshine We should continue our discussion. We have had some plan on that we need to agree on something - Let's allocate some time when priorities on the meeting will be revealed.

Can you remind me once on the plan/discussion those we had on this and we needs to decide on (?)

**Comment by piotrzarzycki21** [comment] 2020-01-22 11:55
> Can you remind me once on the plan/discussion those we had on this and we needs to decide on (?)

Comments in https://github.com/prominic/Moonshine-SDK-Installer/issues/12#issuecomment-506221807 - and this -> https://github.com/prominic/Moonshine-IDE/issues/594#issuecomment-506209773 - We should expand our discussion.

**Comment by rat-moonshine** [comment] 2020-01-22 11:59
Ah, thanks. I vaguely remember now the parts we still needs to decide on, mostly usability cases, i.e. radio vs dropdown etc.

**Comment by piotrzarzycki21** [comment] 2020-01-22 12:01
> Ah, thanks. I vaguely remember now the parts we still needs to decide on, mostly usability cases, i.e. radio vs dropdown etc.

Exactly. That is why we need to meet - maybe a call tomorrow, figure out some plan. Write it down so you could eventually discuss with Joel.

**Comment by rat-moonshine** [comment] 2020-01-23 05:55
I'm starts looking into the https://github.com/prominic/Moonshine-SDK-Installer/issues/12 issue.

**Comment by rat-moonshine** [comment] 2020-01-23 05:59
@piotrzarzycki21 just wants to confirm, if we download from a location like this (below) without any need to bother about what is the build-number, should be Okay?

"http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/apache-royale-0.9.7-bin-js.zip"

http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/

**Comment by piotrzarzycki21** [comment] 2020-01-23 08:26
> @piotrzarzycki21 just wants to confirm, if we download from a location like this (below) without any need to worry about what is the build-number, should be Okay?
> 
> Download URL: http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/lastSuccessfulBuild/artifact/out/apache-royale-0.9.7-bin-js.zip
> 
> From: http://apacheroyaleci2.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/

Yes that's enough for now. Can you elaborate what will be UI changes ?

**Comment by rat-moonshine** [comment] 2020-01-23 09:45
As of now, I want to go by introducing a small dropdown accompanying build variants those we'll feed by the XML. The dropdown can contain of any number of variants as we may require.

For software that accompany only variant (i.e. stable) will not appear this option, though.

**Comment by rat-moonshine** [comment] 2020-01-27 06:48
This issue now addressed into https://github.com/prominic/Moonshine-SDK-Installer/issues/12 and ready for testing.

**Comment by piotrzarzycki21** [comment] 2020-01-27 15:02
In Moonshine Getting Started width of DropDown list should be improved so I could see full text:
![width](https://user-images.githubusercontent.com/24554795/73185450-5dfe6980-411e-11ea-8f07-c91a650c9d49.png)

**Comment by piotrzarzycki21** [comment] 2020-01-27 15:13
Issue in Getting Started:
.I don't have any version of Apache Royale SDK in `c:\MoonshineSDKs\`. When I open Moonshine and Getting Started, next filter By Software I see:
![sdk](https://user-images.githubusercontent.com/24554795/73185958-4f648200-411f-11ea-9a6a-3344a7f6b403.png)

I do have setup in menu File -> Settings -> Default SDK -> Apache Royale 0.9.7 - Nightly from different location than `c:\MoonshineSDKs\`.

Drop down has selected default Nightly - 0.9.7, when I changed it to 0.9.6 Moonshine indicates me that I don't have 0.9.6, which is good.
![sdk](https://user-images.githubusercontent.com/24554795/73186291-c13ccb80-411f-11ea-988e-6137a4d2b51a.png)

When I get back to 0.9.7 it indicates that I also don't have this SDK, which in general is true cause I don't have it in `c:\MoonshineSDKs\`. 

In general the issue is with initial state which indicates that some SDK is installed. - At least I think so.

**Comment by piotrzarzycki21** [comment] 2020-01-27 15:17
Other than that minor stuff - I was able nicely download Nightly build!

**Comment by rat-moonshine** [comment] 2020-01-27 15:20
> Other than that minor stuff - I was able nicely download Nightly build!

I shall investigate the scenario. Good to hear the download works for you.

**Comment by rat-moonshine** [comment] 2020-01-28 05:23
> In general the issue is with initial state which indicates that some SDK is installed. - At least I think so.

I believe that is the case, where initial state of availability affects to initial view of UI. Maybe, we need a more tricker handling for supporting the states between standalone and Moonshine-IDE run.

**Comment by piotrzarzycki21** [comment] 2020-01-28 14:38
> By the way @piotrzarzycki21 , did you noticed any error during change of variant dropdown in Moonshine-IDE?

I haven't seen any errors.

**Comment by piotrzarzycki21** [comment] 2020-02-05 08:06
Royale Nightly build options is in place - I'm closing this.

**Closed by piotrzarzycki21** 2020-02-05 08:06 UTC
Labels: enhancement, test-ready
