### ISSUE TITLE
JAVA_HOME Management

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#456] opened 2019-02-15 23:11 UTC
While reviewing #449, I was reminded that many of the Moonshine features (Flex, Royale, Feathers, Ant, Maven) require that JAVA_HOME is set in the environment.  If the user has already set JAVA_HOME as a global environmental variable in Windows, or installed at least one JDK in macOS, then Moonshine can run the above features without requiring additional setup for Java.

However, this has some limitations:
- I new, non-technical user may not have Java installed.
- The user can't customize which Java is used from Moonshine

If we install OpenJDK automatically as part of #449, we should be able to force the above features to use the configured JDK by passing a value for JAVA_HOME in the environment variables (we already do something similar for FLEX_HOME).

If we want to give the user an option to use the default JDK configured for the system, we could check JAVA_HOME on Windows or /usr/libexec/java_home on macOS (though this would be unavailable until the macOS user has opened the SDK path once).   I think this adds extra complication to the process for #449, though.

**Comment by JoelProminic** [comment] 2019-02-15 23:13
From my investigation, macOS uses a couple helper script to support Java:
- /usr/bin/java - will prompt the user to install Java if they have not done so already
- /usr/libexec/java_home - return the path an installed JRE or JDK

I was able to test the initial Java behavior on macOS by temporarily moving the installed JDKs:

    mkdir ~/Documents/Backup/JavaVirtualMachines
    sudo mv /Library/Java/JavaVirtualMachines/* ~/Documents/Backup/JavaVirtualMachines/
    export JAVA_HOME=""
    export PATH=export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin


Running "java -version" triggers this popup:

![image](https://user-images.githubusercontent.com/24532731/52889324-005b5200-3145-11e9-81d0-9a1a3c6db902.png)

Clicking "More Info" opens a the download page for the latest JRE (currently 11.0.2), rather than the JDK:  https://www.oracle.com/technetwork/java/javase/downloads/index.html

I found that Flex, Royale, Ant, and Maven all showed errors like this if I ran them without any JDKs in /Library/Java/JavaVirtualMachines:

    : No Java runtime present, requesting install.

However, the Java popup did not open in this case.

For reference, I included the errors for each SDK:

#### Flex AIR

On Build & Run

    : Compiling TestFlexDesktop_NoJava
    : Sending to mxmlc: mxmlc -load-config+=obj/TestFlexDesktop_NoJavaConfig.xml -optimize=false +configname=air -debug=true -o bin-debug/TestFlexDesktop_NoJava.swf
    : No Java runtime present, requesting install.
    : 2019-02-15 13:57:19.067 java[4353:9276232] JLRequestRuntimeInstall: Error calling: CFMessagePortCreateRemote



#### Royale

    : Compiling TestRoyale_0210
    : SDK path: /Users/joelanderson/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js/royale-asjs
    : Using Royale Compiler codebase: /Users/joelanderson/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js/royale-asjs
    : Using Royale SDK: /Users/joelanderson/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js/royale-asjs
    : No Java runtime present, requesting install.
    : 2019-02-15 14:07:20.731 java[6857:9286711] JLRequestRuntimeInstall: Error calling: CFMessagePortCreateRemote


#### Ant


    : Ant build Running
    : Unable to find any JVMs matching version "(null)".
    : No Java runtime present, try --request to install.
    : No Java runtime present, requesting install.
    : 2019-02-15 13:59:02.648 java[4606:9277970] JLRequestRuntimeInstall: Error calling: CFMessagePortCreateRemote
    : Unable to find any JVMs matching version "(null)".
    : No Java runtime present, try --request to install.
    : No Java runtime present, requesting install.
    : 2019-02-15 13:59:02.648 java[4606:9277970] JLRequestRuntimeInstall: Error calling: CFMessagePortCreateRemote
    : FSCH exit code: 1



#### Maven

    : Starting Maven build...
    : Maven path: /Users/joelanderson/Downloads/MoonshineSDKs/Maven/apache-maven-3.6.0
    : Maven build directory: /Users/joelanderson/Documents/Flex/temp_workspace/TestConverterLocal_openjobs
    : Command: -c /Users/joelanderson/Downloads/MoonshineSDKs/Maven/apache-maven-3.6.0/bin/mvn clean install
    : No Java runtime present, requesting install.
    : 2019-02-15 14:06:09.024 java[6605:9285665] JLRequestRuntimeInstall: Error calling: CFMessagePortCreateRemote
    : Maven build has been terminated with exit code: 1

**Comment by piotrzarzycki21** [comment] 2019-03-04 14:58
I was thinking about that today and my thoughts that JAVA_HOME should be used at the end of chain:
1. User installed JAVA with Moonshine helper, so it's default set and used in IDE
2. User didn't install java with Moonshine, but setup path in the settings - We don't care for a global environment JAVA_HOME
3. User haven't done **1** and **2** we are using JAVA_HOME, if it doesn't exists user can go back to **1**

**Comment by JoelProminic** [comment] 2019-03-08 23:26
I saw an error today that made me think that JAVA_HOME was not being set when starting the language server on macOS.   See #476 for more information.

**Comment by JoelProminic** [comment] 2019-03-11 22:49
Here are some commands I have been using to verify the environment variables set by Moonshine.

To check the environment variables for Maven, you can use the built-in "help:system" action.  

To check the environment variables for Ant, add these lines to the end of the default task (or another task that you know will execute):


````
		<echo message="ANT_HOME=${env.ANT_HOME}" />
		<echo message="FLEX_HOME=${env.FLEX_HOME}" />
		<echo message="JAVA_HOME=${env.JAVA_HOME}" />
		<echo message="PATH=${env.PATH}" />
````

If I figure out good tricks for testing the environment for the other project types, I'll report them here.

**Comment by JoelProminic** [comment] 2019-03-13 22:53
Any environment variables set from Moonshine should be set for the executed process only.  

For example, here are some example commands to setup the environment for an Ant execution on Windows

    # Switch to a Royale Browser Project
    cd C:\Flex\temp_workspace\TestRoyale_0311\build

    set FLEX_HOME=C:\Users\<USER>\MoonshineSDKs\Royale_SDK\apache-royale-0.9.4-bin-js\royale-asjs
    set JAVA_HOME=C:\Users\<USER>\MoonshineSDKs\Java\openjdk-1.8.0
    set ANT_HOME=C:\Users\<USER>\MoonshineSDKs\Ant\apache-ant-1.10.1
    set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%PATH%
    ant

    # Debugging commands
    ant -version
    java -version
    where java

These could be executed from a batch script.   It is possible to do this in a single line, but the format needs to be very specific:
- Separate the commands with & (execute all commands ignoreing failures) or && (to stop if any of the previous commands fail)
- no trailing whitespace on the "set" commands
- Need to wrap the command with "cmd /V /C"  and use ! to dynamically evaluate the environment varialbes.  Otherwise, %JAVA_HOME% and %ANT_HOME% will not be set properly in PATH.  See: https://superuser.com/questions/223104/setting-and-using-variable-within-same-command-line-in-windows-cmd-exe
- We need to be careful about whitespace in custom paths.  I did not account for this below, but the escape key is ^

    cd C:\Flex\temp_workspace\TestRoyale_0311\build
    cmd /V /C "set FLEX_HOME=C:\Users\<USER>\MoonshineSDKs\Royale_SDK\apache-royale-0.9.4-bin-js\royale-asjs& set JAVA_HOME=C:\Users\<USER>\MoonshineSDKs\Java\openjdk-1.8.0& set ANT_HOME=C:\Users\<USER>\MoonshineSDKs\Ant\apache-ant-1.10.1& set PATH=!JAVA_HOME!\bin;!ANT_HOME!\bin;!PATH!& ant"



For macOS, this is a little simpler:

    cd /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale_0313/build

    export FLEX_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js/royale-asjs"
    export JAVA_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Java/openjdk-1.8.0"
    export ANT_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Ant/apache-ant-1.10.1"
    export PATH=$JAVA_HOME/bin:$ANT_HOME/bin:$PATH
    ant

    # debug commands
    ant -version
    java -version
    which java


And for a single line command, just separate the commands with semicolons.

    cd /Users/joelanderson/Documents/Flex/temp_workspace/TestRoyale_0313/build

    export FLEX_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Royale_SDK/apache-royale-0.9.4-bin-js/royale-asjs"; export JAVA_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Java/openjdk-1.8.0"; export ANT_HOME="/Users/joelanderson/Downloads/MoonshineSDKs/Ant/apache-ant-1.10.1"; export PATH=$JAVA_HOME/bin:$ANT_HOME/bin:$PATH; ant

**Comment by rat-moonshine** [comment] 2019-03-14 11:46
The above findings come out fruitful in my initial investigation. However, I couldn't able to run a command in above formatting by `NativeProcess` but external batch execution. (I have seen batch execution had trouble during SDK Installer test for Joel in past, so we probably need to re-evaluate this way of execution again)

I made sure I don't have JAVA_HOME defined in my system environment variable, and I wanted a quick test like this:

`cmd /V /C "set JAVA_HOME=C:\Users\devsena\Documents\MoonshineSDKs\Java\openjdk-1.8.0& set PATH=!JAVA_HOME!\bin;!PATH!& echo !JAVA_HOME!"`

Running above in a new command-line returned expected output.

I moved the command to run with `NativeProcess` in Moonshine. I tried by various character escaping ways (including shell-encoding that we used in Git process executions in Moonshine) but none were worked. It is possible that we may want to invest more time on escaping sequence investigation, and things may work with NativeProcess as well. Until now, I returned by its `standardErrorData`, i.e.

```
'\"set JAVA_HOME=C:\Users\devsena\Documents\MoonshineSDKs\Java\openjdk-1.8.0& set PATH=!JAVA_HOME!\bin;C:/Program Files/Adobe/Adobe Flash Builder 4.7 (64 Bit)/jre/bin/server;C:/Program Files/Adobe/Adobe Flash Builder 4.7 (64 Bit)/jre/bin;C:/Program Files/Adobe/Adobe Flash Builder 4.7 (64 Bit)/jre/lib/amd64;C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\;%JAVA_HOME%\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;.......;& echo !JAVA_HOME!\"' is not recognized as an internal or external command,
operable program or batch file.
standardErrorData
```

Then I moved to write the same command to an external batch file:
```
@echo off
cmd /V /C "set JAVA_HOME=C:\Users\devsena\Documents\MoonshineSDKs\Java\openjdk-1.8.0& set PATH=!JAVA_HOME!\bin;!PATH!& echo !JAVA_HOME!"
```
And the above worked pretty well. I tested also with a local Moonshine build, and that seems successfully set the local environment variable and there were no error event so far. 

Path with space also didn't trouble with above usage. 

**Where to go from here**

1. Include the batch file processing (with some changes) in Moonshine and let Joel test in his workstation if that work

**Comment by piotrzarzycki21** [comment] 2019-03-14 12:25
> cmd /V /C "set JAVA_HOME=C:\Users\devsena\Documents\MoonshineSDKs\Java\openjdk-1.8.0& set PATH=!JAVA_HOME!\bin;!PATH!& echo !JAVA_HOME!"

Why we need to setup PATH ? I don't think we should do that. Remove PATH and try again.

**Comment by piotrzarzycki21** [comment] 2019-03-14 12:26
Apart of that when you setup PATH - is it local setup or Global for windows ? If I setup in one CMD PATH and go to another - Am I going to see that ?

**Comment by rat-moonshine** [comment] 2019-03-14 14:18
> 
> 
> > cmd /V /C "set JAVA_HOME=C:\Users\devsena\Documents\MoonshineSDKs\Java\openjdk-1.8.0& set PATH=!JAVA_HOME!\bin;!PATH!& echo !JAVA_HOME!"
> 
> Why we need to setup PATH ? I don't think we should do that. Remove PATH and try again.

We probably need to set PATH, Joel can give more detail on this.

@JoelProminic I added an experimental process to execute batch script includes environment variable for ANT_HOME, JAVA_HOME and FLEX_HOME. The batch will generate and run based on current Moonshine configuration. At present, the setup process is available only on Windows. 

The process is made to run during Moonshine startup, and whenever a path is changed for default SDK, Ant and Java. 

After you install latest build of Moonshine, it'll show you a *test* alert printing your current JAVA_HOME location based on your local environment variable. You can change the Java path by going into `Moonshine -> Settings` and wait for the alert to see if the path prints correctly for you. The alert will result of executing following formatted batch file:

`cmd /V /C "set $FIELD=$PATH& set PATH=!FIELD!;!PATH!"`

You can view the generated batch file by going into following location:

C:\Users\$User\AppData\Roaming\com.moonshine-ide\Local Store\setLocalEnvironment.bat

**Comment by JoelProminic** [comment] 2019-03-14 14:27
I set PATH in my example commands because that was the recommended system configuration for Ant:
https://ant.apache.org/manual/install.html

I looked into this after I got this error:  https://stackoverflow.com/questions/2618281/ant-error-when-trying-to-build-file-cant-find-tools-jar

All of the environment variables in my above commands will only be set for the "session" (i.e. a single NativeProcess call from Moonshine).  They should not affect the global environment variables (and we do not want Moonshine to change those).

If we find that we have trouble with setting PATH, we can try without it.  We would need to call the executables by the full path, though:

    %ANT_HOME%\bin\ant

@rat-moonshine, if you are going to use batch and bash scripts, then I recommend that you use the multiple line commands I gave earlier.  These will be easier to read and maintain.

**Comment by JoelProminic** [comment] 2019-03-14 23:11
To give some context for why the environment variable setup is important for the 2.0.0 release, I did some tests with no global environment variables installed.   For macOS, I also temporarily hid the JDKs I had installed in the default location:

    sudo mv /Library/Java/JavaVirtualMachines /Library/Java/Hidden_JavaVirtualMachines

For Windows, I tested with a fresh Windows 10 VM.

Action | Requires Environment Variables | macOS | Windows | Notes
-------|--------------------------------|-------|---------|------
Start language Server | Yes (FLEX_HOME, Flex/Royale projects only) | Works | Works |
Build Project (Flex) | Yes (FLEX_HOME (or project specific), JAVA_HOME) | Fails: "No Java runtime present..." | Failed: 'java' is not recognized |
Build Project (Feathers) | " |  | Not Tested |
Build & Run (Flex) | " | Fails: "No Java runtime present..." | Failed: 'java' is not recognized |
Build & Run (Feathers) | " |  | Not Tested |
Build as Javascript | " | Fails: "No Java runtime present..." | Failed: 'java' is not recognized |
Build & Run as Javascript | " | Fails: "No Java runtime present..." | Failed: 'java' is not recognized |
Build Release (Flex) | " | Fails: "No Java runtime present..." | Failed: 'java' is not recognized |
Build Release (Feathers)) | " |  | Not Tested |
Build & Debug (Flex) | " | Fails: "No Java runtime present..." | Failed: 'java' is not recognized |
Build & Debug (Feathers) | " |  | Not Tested |
Build with Apache Ant | Yes (ANT_HOME, JAVA_HOME,FLEX_HOME) | Fails: "No Java runtime present..." | Fails:  '"java.exe"' is not recognized... |
Right Click -> Run Ant Script | Yes (ANT_HOME, JAVA_HOME,FLEX_HOME) | Fails: "No Java runtime present..." | Fails:  '"java.exe"' is not recognized... |
Build with Apache Maven | Yes (MAVEN_HOME, JAVA_HOME,FLEX_HOME) |  |  |
Subversion | No |  | Fails (Hang) | This may be a separate problem.  I'll check this more tomorrow
Git | No |  |  |
Preview PrimeFaces | JAVA_HOME | Fails: "No Java runtime present..." | Fails:  Server for PrimeFaces preview has not been set up |

I confirmed that Java Home was configured in the Moonshine Settings for both environments.

I ran out of time to test all fo the cases, but it is clear that a lot of the functionality won't work currently without an external Java installation.

**Comment by rat-moonshine** [comment] 2019-03-15 09:20
The above problems are pretty severe and dismisses the idea behind introducing new functionalities as/with SDK Installer.

I spent quite some time behind this today to reproduce the behaviour listed above and finding for way out. 

While on Windows, I removed all my known Java references from system environment variable, I see `set` command still returning me list containing JAVA_HOME with valid path. I don't know where this is coming from. Since Moonshine also auto-set the Java path through SDK Installer, I couldn't able to successfully check above listed behaviours. 

However, I able to reproduce the behaviour on macOS by removing Java environment variable, and manipulating `/Library/Java/JavaVirtualMachine` by your suggested command.

What I wonder is, how you able to run type-ahead on macOS. I think I probably downloaded same OSX Moonshine version from Bamboo, and when supplied with both Java and Flex paths, I see type-ahead startup notification added to the application's status bar but console populated with error and therefore no type-ahead worked for me (following screen during Moonshine startup):

![StartupProblem](https://user-images.githubusercontent.com/24370870/54420178-506f0980-472f-11e9-8ab2-a5ab662b966d.png)

The above busy/progressbar animation never disappeared probably because some expected event never returned thus never turned the animation stop. I tested with local build, that also shown me similar result.

Next, I moved to test way out to avail necessary environments to any Moonshine process, I choose to investigate against `Project -> Build & Run` against Flex desktop project. I made sure both Apache Flex SDK and Java path added to Moonshine settings. 

Overall the investigation was quite time taking. To test every with-system-Java and without-system-Java presence, I had to manipulate `/Library/Java/JavaVirtualMachines` path; I couldn't manipulate the path while testing/debugging from IDE - because IDE failed to debug the project due to non-existence of required Java. So overtime I required to build it externally through Ant build script, manipulate the `/Library/Java/JavaVirtualMachines` path, and then test the generated Moonshine app.

To create a test-investigation I had to modify many codes in `Build & Run` class file. Moonshine use to build a Flex application with the usage of `fcsh` and `mxmlc` executable. I found different problem using `fcsh` so I choose to limited by using `mxmlc` only (that is also Okay to test a build process and to produce a .swf file). I finally have a command prepared like this (based on current Moonshine configuration):

```
export JAVA_HOME="/Users/santanu/Downloads/Moonshine_SDKs/Java/openjdk-1.8.0"; export FLEX_HOME="/Users/santanu/Downloads/Moonshine_SDKs/Flex_SDK/Flex_4.16.1_AIR_30.0"; export PATH=$JAVA_HOME/bin:$FLEX_HOME/bin:$PATH;export SETUP_SH_VMARGS="-Duser.language=en -Duser.region=en";mxmlc -load-config+=obj/NewFlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true -o bin-debug/NewFlexDesktopProject.swf
```

I confirm running the above command on command-line (when no system environment Java) to the project folder produce appropriate result. Unfortunately, it looked like running the above command in Moonshine had had trouble:

![ErrorWhileBuildRun](https://user-images.githubusercontent.com/24370870/54420896-3e8e6600-4731-11e9-8646-f543d9af2ba0.png)

I'm thinking how to next at this moment.

**Comment by piotrzarzycki21** [comment] 2019-03-15 09:26
In case of Windows you may have in Path direct path to Java somewhere. Additionally I would not only remove paths, but also go to uninstaller on Windows and uninstall all Java SDK. Next try scenario from Joel. Maybe before you do restart your machine.

**Comment by rat-moonshine** [comment] 2019-03-15 12:30
I think I found the equation to do this on Windows.. 

I made sure I don't have Flex or Java environment exists in my system. Command-line reported appropriate results of non-existence for both the items. 

I made some changes to the local environment setup policy, Windows now setting the environments in line break style through batch file execution, OSX version for now continuing to execute as one-line command. On Windows it is not as Joel suggested:

```
@echo off
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_102
set ANT_HOME=G:\DevareaLocal\apache-ant-1.10.5
set FLEX_HOME=G:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR_32.0
set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%FLEX_HOME%;%PATH%

```
I made some changes to "Build & Run" execution for Flex/ActionScript projects only for now (we shall need to implement the same type of execution policy for other areas if we want to go by this). Compilation command now executed with same `NativeProcess` process along with the batch file execution. That worked. 

I tested also in standalone build of Moonshine, that worked good too to open the application to AIR window (in case of Flex desktop).

I'm committing the changes concentrating only to Build & Run area for Flex/ActionScript projects on Windows; Since OSX the process is still not resolved, it'll continue using its old execution structure.

**Comment by piotrzarzycki21** [comment] 2019-03-15 14:39
Great! Can you check whether PATH have to be setup? I'm afraid that we are overriding something having path setup.

**Comment by rat-moonshine** [comment] 2019-03-15 15:31
> 
> 
> Great! Can you check whether PATH have to be setup? I'm afraid that we are overriding something having path setup.

Yeh, I can give that a try too.

**Comment by JoelProminic** [comment] 2019-03-15 22:54
The commands I gave are adding to the beginning of the existing PATH variable, and the changes do not persist in my tests.

However, I confirmed that PATH is not required for at least the basic ant behavior.  These commands worked fine for me (note that the last command uses the full path to the executable)

    cd C:\Flex\temp_workspace\TestRoyale_0311\build

    set FLEX_HOME=C:\Users\<User>\Documents\MoonshineSDKs\Royale_SDK\apache-royale-0.9.4-bin-js\royale-asjs
    set JAVA_HOME=C:\Users\<User>\Documents\MoonshineSDKs\Java\openjdk-1.8.0
    set ANT_HOME=C:\Users\<User>\Documents\MoonshineSDKs\Ant\apache-ant-1.10.1
    %ANT_HOME%\bin\ant

I think it is probably preferable to use the full path for all executables.  I think we were doing this already in the Moonshine code.

**Comment by rat-moonshine** [comment] 2019-03-18 12:53
Local environment setup on OSX is now working. 

Unfortunately, removing 'set PATH' command during batch process run on Windows didn't worked against compiler like 'mxmlc'. It continued to report java-not-recognized error until 'set PATH' provided to the batch process. It looks like OSX didn't shown such restriction so it's not using in OSX. Following is the command how I tried to run the batch script without 'set PATH' command:

```
@echo off
set JAVA_HOME=C:\Users\devsena\Documents\MoonshineSDKss\Java\openjdk-1.8.0\bin
set ANT_HOME=G:\DevareaLocal\apache-ant-1.10.5\bin
set FLEX_HOME=G:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR_32.0\bin
"G:\DevareaLocal\ApacheFlexSDK\4.16.1_AIR_32.0\bin\mxmlc.bat" -load-config+=obj/NewFlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true -o bin-debug/NewFlexDesktopProject.swf
```

From #449 , from @JoelProminic 

> Use a different file extension for the script. I confirmed .cmd works, but I didn't find a way to run a script with an arbitrary extension. @rat-moonshine, I think we used a command like this for Native, to force Windows to open a file/URL with a specific application.

Moonshine is now generating the batch file with .cmd extension instead of .bat. 

From @piotrzarzycki21 

> I prefer that you won't use any kind of delay. If changing extension is working, let's go with that way without adding additional complication. Adding delay should be the last thing to resolve problems.

I don't think changing the extension to .cmd make the process different in Vagarant. The system from Vagarant must be intelligent to identify any executable like .cmd or .bat, thus its process may hold the file as was before. However, I have only changed the extension for now, if @JoelProminic continue to see similar problem, we may want to test by delaying execution. 

@JoelProminic , on OSX I tried to execute the local environment setup by executing through a bash script (.sh) with similar line-break style as we followed for batch execution on Windows. However, the test failed as sandbox thrown security error during generating dynamic bash file. Following were the cases which found failed during my tests:

1. Having .sh file in application folder with executable permission, security error thrown during updating the file inside application folder location
2. Generated .sh file to application storage location, that worked but OSX added an extended attribute to the file
3. In sandbox it is not permitted to use 'xattr' to alter some file's extended attribute
4. Having an extended attribute the .sh file didn't permitted to run even the file had executable permission
5. I tried to copy a proper .sh file without any extended attribute and executable permission from application's folder to application storage area - after the file get copied, its added with the extended attribute

Due to above problems, we're not executing environment setup command in one line without using of any external file and without any 'set PATH' command. This is working so far. 

Current list of functionalities from Moonshine those incorporated to use the local environment setup policy and tested have mentioned in #449 .

**Comment by piotrzarzycki21** [comment] 2019-03-25 11:26
Are we moving more work on that stuff as part of this issue for the next release or can we close this ?

**Comment by JoelProminic** [comment] 2019-03-25 22:13
I was able to reproduce the PATH requirement for mxmlc.bat:

    cd C:\Flex\temp_workspace\TestFlexDesktop_0318
    set FLEX_HOME=C:\Users\<user>\Documents\MoonshineSDKs\Flex_SDK\Flex_4.16.1_AIR_32.0
    set JAVA_HOME=C:\Users\<user>\Documents\MoonshineSDKs\Java\openjdk-1.8.0
    set ANT_HOME=C:\Users\<user>\Documents\MoonshineSDKs\Ant\apache-ant-1.10.1
    "%FLEX_HOME%\bin\mxmlc.bat" -load-config+=obj/TestFlexDesktop_0318Config.xml -optimize=false +configname=air -debug=true -o bin-debug/TestFlexDesktop_0318.swf


    C:\Flex\temp_workspace\TestFlexDesktop_0318\build>"%FLEX_HOME%\bin\mxmlc.bat" -load-config+=obj/TestFlexDesktop_0318Config.xml -optimize=false +configname=air -debug=true -o bin-debug/TestFlexDesktop_0318.swf
    'java' is not recognized as an internal or external command,
    operable program or batch file.


    # mxmlc.bat works after this command
    set PATH=%FLEX_HOME%\bin;%JAVA_HOME%\bin;%ANT_HOME%\bin;%PATH%


Checking the contents of mxmlc.bat, I see that it uses "java" without JAVA_HOME:

```
@echo off
rem Licensed to the Apache Software Foundation (ASF) under one or more
...

if "%FLEX_HOME%"=="" set FLEX_HOME=%~dp0\..

java -Xmx384m -Dsun.io.useCanonCaches=false -Djava.util.Arrays.useLegacyMergeSort=true -jar "%FLEX_HOME%\lib\mxmlc.jar" +flexlib="%FLEX_HOME%\frameworks" %*
```


However, bin\mxmlc on macOS should have the same problem:
```
#!/bin/sh
...

# don't use $FLEX_HOME in this variable because it may contain spaces,
# instead put it on the java args directly, with double-quotes around it
VMARGS="-Xmx384m -Dsun.io.useCanonCaches=false -Djava.util.Arrays.useLegacyMergeSort=true "

java $VMARGS $D32 $SETUP_SH_VMARGS -jar "$FLEX_HOME/lib/mxmlc.jar" +flexlib="$FLEX_HOME/frameworks" "$@"
```

I didn't notice this problem in my tests because /usr/bin/java was still defined and functional on my path.  So, the mxmlc command could be using a different version of Java in this case.  In order to completely clear the external Java from my test environment, I needed to run these commands:


    # clear any existing JAVA_HOME
    export JAVA_HOME=""
    # Clear any references on the PATH
    export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"

    # disable /usr/libexec/java_home
    sudo mv /Library/Java/JavaVirtualMachines /Library/Java/Hidden_JavaVirtualMachines
    # Reenable it with this command when you are done with testing
    sudo mv /Library/Java/Hidden_JavaVirtualMachines /Library/Java/JavaVirtualMachines

    # Disable /usr/bin/java
    sudo mv /usr/bin/java /usr/bin/java_hidden
    # Reenable it when you are done with testing
    sudo mv /usr/bin/java_hidden /usr/bin/java


    # test commands
    cd /Users/<user>/Documents/Flex/temp_workspace/TestFlexDesktop_0325
    export FLEX_HOME=/Users/<user>/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0
    export JAVA_HOME=/Users/<user>/Downloads/MoonshineSDKs/Java/openjdk-1.8.0
    export ANT_HOME=/Users/<user>/Downloads/MoonshineSDKs/Ant/apache-ant-1.10.1
    $FLEX_HOME/bin/mxmlc -load-config+=obj/TestFlexDesktop_0325Config.xml -optimize=false +configname=air -debug=true -o bin-debug/TestFlexDesktop_0325.swf


    # example output
    $ $FLEX_HOME/bin/mxmlc -load-config+=obj/TestFlexDesktop_0325Config.xml -optimize=false +configname=air -debug=true -o bin-debug/TestFlexDesktop_0325.swf
    /Users/<user>/Downloads/MoonshineSDKs/Flex_SDK/Flex_4.16.1_AIR_32.0/bin/mxmlc: line 69: java: command not found


So, PATH is needed for macOS as well, at least for the mxmlc command.

**Comment by JoelProminic** [comment] 2019-03-25 22:21
In order to resolve the batch script issues we reported on Windows (more discussion in #449), we added a 1 second delay before the script is executed.   This seemed to reliably resolve the problem for me.  

@piotrzarzycki21, do find the delay noticeable?  If it is a problem, we could investigate a better solution.

**Comment by piotrzarzycki21** [comment] 2019-03-26 08:37
> In order to resolve the batch script issues we reported on Windows (more discussion in #449), we added a 1 second delay before the script is executed. This seemed to reliably resolve the problem for me.
> 
> @piotrzarzycki21, do find the delay noticeable? If it is a problem, we could investigate a better solution.

Nope. I think in general using delay should be the last solution if anything fails. It can bee too much unpredictable. ;)

**Comment by rat-moonshine** [comment] 2019-03-27 15:56
'set PATH' command also added for macOS environment setup, as well.

**Comment by piotrzarzycki21** [comment] 2019-04-09 09:57
@rat-moonshine are we good with that ? Can we close it ?

**Comment by rat-moonshine** [comment] 2019-04-09 10:40
> 
> 
> @rat-moonshine are we good with that ? Can we close it ?

It looks we are now good with this issue. However, Joel may want to close this issue if he think nothing else is left to address.

**Comment by JoelProminic** [comment] 2019-04-12 22:07
This has been working well for me, so we can close this issue unless we want to improve how we handle the race condition for the batch script on Windows.

**Closed** 2019-04-15 12:59 UTC
Labels: enhancement
