### ISSUE TITLE
ActionScript file popup do not import class statement automatically

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#251] opened 2018-04-26 11:57 UTC
While having the "Superclass" and "Interfaces" field is handy to new ActionScript file popup, supplying the information not auto-import class paths to the file, which breaks the file (during compilation). User needs to manually import the class statement later which reduce the usability of supplying the fields to the new file creation popup.

![image](https://user-images.githubusercontent.com/24370870/39304222-a4db7e5c-4976-11e8-8f5b-e38349a83774.png)

Following a few options we might choose from:
- Remove the "Superclass" and "Interfaces" fields from the new file popup and let user import/add them by themselves (if we found adding auto-import critical here)
- Auto-import class statement to the file (if language-server can help on this part it'd be even best)

Enhancement:
- Add ability to choose from existing files, to the fields (it could be an auto-complete input, or someway to select from existing file) - this will reduce typo

**Comment by piotrzarzycki21** [comment] 2018-04-26 15:28
That enhancement makes me realize that we may have everything what is needed for that issue. Makes autocomplete available here should also allows use import mechanism. Are you going to work on that ?

**Comment by rat-moonshine** [comment] 2018-04-26 15:31
I can plan to start on this after #247 . However, if you have some plan you can jump into before me, and raise whichever portion you can complete by the time.

**Comment by piotrzarzycki21** [comment] 2018-04-26 15:34
I've been looking into the language server a bit, so I may have some idea how to achieve that. I will take it.

**Comment by piotrzarzycki21** [comment] 2018-04-27 12:31
@joshtynjala I did look into that a bit and I have a question related to language server. The goal here is to have completion list when I'm typing during file creation. In the results it would looks similar as in intellij:

![completion_in_window](https://user-images.githubusercontent.com/24554795/39362358-735ba356-4a26-11e8-9b43-38b79faeb382.gif)

However in order to invoke code completion list you [prequire path to the current editor](https://github.com/prominic/Moonshine-IDE/blob/b9de7fd1d5171ee92960bb70eba2124f0482c25f/ide/MoonshineDESKTOPevolved/src/actionScripts/utils/LanguageServerForProject.as#L954). In case of that issue we won't have yet any file. 

Is it ok from the language server perspective if I send request without that url ? 

The second thing is that I probably won't be able to reuse current instance of language server, but rather invoke new one, or maybe implement my own class which returns for me list.

**Comment by joshtynjala** [comment] 2018-04-27 15:34
@piotrzarzycki21 The language server has a workspace symbol command that seems appropriate here. It wouldn't require an editor or a new instance of the language server. We have a dialog for search workspace symbols already, but it should be possible to also expose the command with an event or something to simply return the array of raw data.

You'd get many extra symbols that you don't need, but you could easily filter the result, if you only needed classes or interfaces.

**Comment by piotrzarzycki21** [comment] 2018-04-30 16:29
Thanks @joshtynjala I see now how to do that.

**Comment by joshtynjala** [comment] 2018-05-07 16:28
@piotrzarzycki21 I will try to update the workspace symbols command to return framework classes in a future version of the language server.

**Comment by piotrzarzycki21** [comment] 2018-05-07 16:30
Many thanks. I will finish than implementation on my sight to be ready for that.

**Comment by piotrzarzycki21** [comment] 2018-05-09 13:16
I have finished part where we have code completion in above popup based on `TypeAheadEvent.EVENT_WORKSPACE_SYMBOLS` event. I will commit everything once we release 1.12.0. The next stage in that task is to have imports in place when user hit "Create" file. How actually approach to that task?

The EVENT_WORKSPACE_SYMBOLS event gives me only [name](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineSharedCore/src/actionScripts/valueObjects/SymbolInformation.as) of the file without any package information. 
Should I run import mechanism once user create that file ?

**Comment by joshtynjala** [comment] 2018-05-09 17:41
The language server populates a containerName field with the name of the package, but it looks like Moonshine does not currently include the containerName in the value object.

**Comment by piotrzarzycki21** [comment] 2018-05-11 12:28
Thanks @joshtynjala it was very helpful. I think I have finished on my sight. If you expose more things through `TypeAheadEvent.EVENT_WORKSPACE_SYMBOLS` event it should work without modification on my sight.

**Comment by piotrzarzycki21** [comment] 2018-05-15 09:42
@joshtynjala I did apply change related to differences between SymbolInformation and CompletionItem. 
I have noticed one thing with usage of `TypeAheadEvent.EVENT_WORKSPACE_SYMBOLS`. If I don't have any files opened it's not working. If I open at least one file from the project it's working fine - language server respond to any request related to that event. Is it expected behavior ?

**Comment by joshtynjala** [comment] 2018-06-07 17:02
The following commits from the upcoming v0.13 of the language server will enhance TypeAheadEvent.EVENT_WORKSPACE_SYMBOLS to also return symbols that are defined in SWC files.

BowlerHatLLC/vscode-nextgenas@bfc17dfd5db4078f84fab4444e7af0c5ced3ddb3
BowlerHatLLC/vscode-nextgenas@8fa0fdba2951701e6b27345c6f636a37b69e859e

**Comment by joshtynjala** [comment] 2018-09-19 17:16
The language server has been updated to v0.13, and the workspace symbols call now includes the classes that were previously missing.

**Comment by piotrzarzycki21** [comment] 2018-09-20 06:38
Thanks Josh it's working. I may look in the future to improve it a bit in case of filtering, but for now I'm closing this one.

**Closed by piotrzarzycki21** 2018-09-20 06:38 UTC
Labels: enhancement
