### ISSUE TITLE
"Find Symbol in Workspace" window demonstrates item listing when no filter string is present

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#724] opened 2020-09-15 10:52 UTC
Testing the "Find Symbol in Workspace" window with newer FeathersUI implementation, I noticed a few oddities:

- Open the window from View -> Find Symbol in Workspace
- It appears with no listing and no value in its input field
- Try to type some texts in the input and then remove them using the keyboard Backspace
- Try to do the above step until a situation occurs when there is no input value yet there is a number of items in its list

![image](https://user-images.githubusercontent.com/24370870/93201793-4b997480-f76f-11ea-82f9-20730afe3d30.png)

Expected (any of the following):
1. There shall be an unfiltered listing always present no matter user input any filter string
2. No item should be listed when there is no search string input

**Comment by joshtynjala** [comment] 2020-09-15 15:30
Thank you.

> Open the window from View -> Find Symbol in Workspace
> It appears with no listing and no value in its input field

For these two, it is the expected behavior. That's how it worked in the Flex version too. It's just a general search dialog, and there's no context when initially opening the window.

> there is no input value yet there is a number of items in its list

This behavior likely also existed in the Flex version because I think that it's possible for the language server to return results out of order. I should probably keep track message IDs and ignore "older" ones. However, I will investigate and see if it could be anything else.

**Comment by rat-moonshine** [comment] 2020-09-17 11:55
> However, I will investigate and see if it could be anything else.

Until then, should we keep this issue open, or you think that is another subject of investigation and we close this issue (?)

**Comment by joshtynjala** [comment] 2020-09-17 16:13
We can keep it open for now. I'll take a look next week and close it when I'm done.

**Comment by joshtynjala** [comment] 2020-09-21 18:34
I made a few changes to improve Find Symbol in Workspace.

- I moved Find Symbol in Workspace (and Find Symbol in Document) to the Edit menu with the other "Find" options. This should make it more obvious why there is nothing in the input box when you open the window.
- When the query is empty, it will list all symbols in the workspace (instead of an empty list of results). This more closely matches the behavior of Find Symbol In Document. Basically, we're filtering a list of all symbols when we start typing. With that in mind, when you delete your query, it should restore the full list of all symbols.
- When the window opens, I immediately send a request for all symbols. It takes a moment to finish loading, though, so the results list will be empty for a moment. Eventually, we should add some kind of activity indicator to show that a search is in progress.
- The results list is now sorted alphabetically.

**Closed by joshtynjala** 2020-09-21 18:34 UTC
Labels: bug

**Comment by rat-moonshine** [comment] 2020-09-22 11:58
Testing this in master, 'Find symbol in Workspace' seems to work as per the [new](https://github.com/prominic/Moonshine-IDE/issues/724#issuecomment-696294011) way. I confirm the list-population sync issue is now fixed. 

However, I'm not clear how the 'Find symbol in Document' is expected to work. As in the following screenshot, the window automatically listed `ValModule1` but I couldn't able to list `VallModule2` or `SrcModule1` etc. through its search option:

![image](https://user-images.githubusercontent.com/24370870/93879241-0342ff00-fcf9-11ea-98d4-bce4566df71e.png)
![image](https://user-images.githubusercontent.com/24370870/93879282-1229b180-fcf9-11ea-92cd-cbbcca443395.png)

**Comment by rat-moonshine** [comment] 2020-09-22 15:19
> However, I'm not clear how the 'Find symbol in Document' is expected to work. As in the following screenshot, the window automatically listed ValModule1 but I couldn't able to list VallModule2 or SrcModule1 etc. through its search option:

Okay. I think I understood it now correctly as its name depicts "Find symbol in Document" - it searches symbols in the active editor/document only, rather than in project's directory which is task of "Find symbol in Workspace".

**Comment by joshtynjala** [comment] 2020-09-22 15:52
Correct, it's the symbols in the currently active editor. If it would help, we could rename it "Find Symbol in Editor" or something else. I think that "Find Symbol in Document" is what VSCode calls it, so I used the same name.

**Comment by rat-moonshine** [comment] 2020-09-22 16:25
As you mentioned I remember one problem, which might interest you. 

During "Find Symbol in Workspace" we noticed that the command also depends on an opened editor or project's file if precise. This feature probably doesn't require to depend on if any editor is open or not. 

I saw this behavior while testing "Find Symbol in Workspace":

Scenario | "Find Symbol in Workspace" working
------------------------------ | -----------------
A project file opened | Works
No editor file opens but projects opened in the sidebar | Do not work
Project files opened in editors, project's Settings tab is active editor | Do not work

**Comment by joshtynjala** [comment] 2020-09-22 17:29
I just pushed a fix that will search for symbols when there is no active editor (or the active editor is settings).

The results are still based on the active project, though. Ideally, the request would be sent to the language servers for all projects, and then, the results would be merged. That's how it works in VSCode. However, I've found it challenging to figure out a way to implement the merging, so it's limited to the active project for now.

It might be better if we renamed it to "Find Symbol in Project" instead.

**Comment by rat-moonshine** [comment] 2020-09-23 05:56
> It might be better if we renamed it to "Find Symbol in Project" instead.

Ah, I think that makes sense then; since this works against a particular project that has the selection currently. I shall change the menu label.

**Comment by JoelProminic** [comment] 2021-05-18 20:58
I see that "active project" is defined as the project associated with the currently open file.   If there is no open editor, then it is based on the selected project in the sidebar.   Elsewhere in Moonshine, we use the selected project in the sidebar only to determine the selected project, so I found this a little confusing originally.   This does not need to be fixed now, but it is something we may revisit if it keeps causing confusion.

**Comment by joshtynjala** [comment] 2021-05-18 21:05
@JoelProminic With that in mind, we should probably automatically change the selected project in the sidebar when the active editor changes. If I searched symbols in the current project, and I only saw symbols from a different project than the one associated with the currently active editor, that would feel like a major bug to me.

**Comment by JoelProminic** [comment] 2021-05-18 21:38
@joshtynjala, we previously avoided locking the sidebar to the currently edited file.  In my experience with Eclipse, I found this behavior annoying rather than useful most of the time.  Instead, we have a button to "Select Open File" (#80), which could be used to quickly update the active/selected project to match the active editor.

If there is interest in in, we could add a feature to lock and unlock the sidebar from the currently edited file.  So far, the "Select Open File" feature seemed to be sufficient for users.

Alternatively, we could make other updates that would make this difference less noticeable:
- Show a combobox/dropdown with the available projects to search.
- Search all projects.  I saw you said that this is [stuck for now](https://github.com/prominic/Moonshine-IDE/issues/724#issuecomment-696867009), though:

**Comment by joshtynjala** [comment] 2021-05-18 22:27
> In my experience with Eclipse, I found this behavior annoying rather than useful most of the time.

Funny, I guess I'm the exact opposite. I like knowing that the sidebar selection in my editor/IDE will be updated when I open a different file, and I certainly take advantage of that behavior.

I just realized that this explains my confusion about why the active project always seemed wrong when I needed to work on various features that rely on knowing the active project. Not only did I add this workaround to the Find In Project feature, but I'm also pretty sure that I've added a similar workaround  in other places too. If I had to guess, maybe in places related to building and debugging certain types of projects. I would also consider it a serious bug if the chosen project for those features wasn't based on the active editor either.

**Comment by Aszusz** [comment] 2021-10-05 11:03
@rat-moonshine
Could you tell me where can I find the functionality that was previously available under `View -> Find Symbol in Workspace`?

**Comment by rat-moonshine** [comment] 2021-10-05 11:16
I'm not very familiar with Symbol section(s).. Doing a quick search in source, I couldn't found any instance named 'Find Symbol in Workspace', though.

**Comment by Aszusz** [comment] 2021-10-05 11:21
@joshtynjala 
Do you know if the functionality that was previously available under `View -> Find Symbol in Workspace` still exists?
