### ISSUE TITLE
Buttons for creating new projects are too long

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#61] opened 2017-11-03 09:22 UTC
In the Tab "Home" buttons for creating new projects are too long and user can start creating projects by clicking in the empty space. 
Take a look into the following screenshot where I'm hovering in the middle of the "Home" page and I'm still able to see "hand" which indicates that I can create project.

![buttons_too_long](https://user-images.githubusercontent.com/24554795/32366986-c5d2c13a-c080-11e7-969f-44b5c953d8e7.gif)

**Comment by rat-moonshine** [comment] 2017-11-03 09:48
List of options showing in the splash screen are based on List component. Categorically there are two lists - at left its project open/creation options, at right its file/project history list. Both sided of lists acquired 60:40% width ratio. 

Since the option/buttons' text length could be anything, and we did not wanted to line break left side options, we did not restrict the lists with a fixed width. In default Moonshine size (1024x768), when both sides have enough contents opened, and the left sidebar also opened, this 60:40 ratio I think become sense:
![image](https://user-images.githubusercontent.com/24370870/32367972-274a42fc-c0aa-11e7-9424-445a2af3e3e2.png)

**Comment by piotrzarzycki21** [comment] 2017-11-03 10:17
I didn't look into the code of that lists, but width of the lists itself could be different than items in itemrenderers. In the other words they can react for clicking in the width which they take. Let me look into that having your thoughts in mind.

**Comment by rat-moonshine** [comment] 2017-11-03 10:51
I'm not clear - you suggesting a way that can make itemrenderes not to line break but its List container can have smaller width than than the renderers (?) I'd like to know the way of implementation, though.

**Comment by piotrzarzycki21** [comment] 2017-11-03 10:58
No I'm not saying that the list container can have smaller size than the renderers. I'm saying that content of renderers can have smaller size than list. Just theoretically:
```
<List width="100">
    <Group width="100%"> - My renderer
          <Button width="30%"/> - it can have here such width.
    </Group>
</List>
```

Does that make sense now ?

**Comment by rat-moonshine** [comment] 2017-11-03 11:05
Okay, I understood. Thank you for the explanation. I shall take a look.

**Comment by JoelProminic** [comment] 2017-11-15 22:56
I confirmed that dialogs only open when clicking on the text

However, the buttons animate when I mouse over or click in the area that was previously clickable.  This makes it seem like the button is there, but does not work.

Also, mousing over and clicking the icons to the left of the text animates the buttons, but the dialogs do not open.  I would expect clicking the icons to open the dialogs.

If this is non-trivial to fix, it can wait until a later release.

**Comment by rat-moonshine** [comment] 2017-11-16 05:24
Unlike the recent project/files list at right-hand side (which uses a custom approach to render the list to overcome varied position/alignment problems), template list at the left-hand side still uses native component list. I don't think we have a good reason to replace them completely with another custom approach.

Thus, I made it sure the mouse-over effect restrict to the label only and has the impression the label only is clickable. Hovering effect removed from the icons, also mouse-over effect now limited to the labels' width (as we have in the recent project/file list).

I'm closing this for the time being for 1.6.1 release. We can re-open this after the release.

**Closed by rat-moonshine** 2017-11-16 05:24 UTC
Labels: bug
