### ISSUE TITLE
File Chooser in Project Paths Interface Should Use Last Opened Path

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#520] opened 2019-04-15 20:36 UTC
Extracted from #499:

> Currently file choosers for new path entries always open to ~/Desktop. This should instead open to either the project base directory or the last open directory. Using the last open directory would fit better with the file chooser logic in the rest of the application.

I thought we had previously implemented this logic for all file choosers in Moonshine, but I couldn't find the original issue.

**Comment by JoelProminic** [comment] 2019-05-08 23:01
Further information about the current logic from @rat-moonshine:
1. If you open file-chooser for first time, it should open you to Desktop directory
2. You browsed any other location through the dialog
3. Next time you open a file-choose from some area - this should open you to that last browsed location
4. In case of browsing by specific path, i.e. you click on Change link associated to any path value already set in Settings, this will open the dialog by that path - if exists 
5. Next time if you open file-chooser it'll open by the last accessed


I tried this, and it failed for me like this:
1. Import a project with Project > Open/Import Project
2. Check Project > Open/Import Project again - the diretory is preserved.  Cancel the prompt
3. Create a new Flex Desktop project
4. Create some "lib" directories in the project
5. Project > Settings > Paths
6. Add a new Resource Folder - for me, this opened to the last directory in my "Parent Directory" tropdown (from the New Project form)
7. Browse to one of the added directories
8. Add another Resource folder - BUG:  this opens to the same path from 6.  Cancel the prompt
2. Check Project > Open/Import Project again - BUG:  this opens the same path from 6.

**Comment by rat-moonshine** [comment] 2019-05-10 10:55
![image](https://user-images.githubusercontent.com/24370870/57522420-438e2100-7340-11e9-8acd-5fdab6a0fe96.png)

**Comment by rat-moonshine** [comment] 2019-05-23 09:45
Moonshine now stores the last browsed location so next time Moonshine start browsing can be start from the same location. 

If the saved location found not exists anymore, Moonshine will continue to open browsing from the user's desktop directory.

**Comment by rat-moonshine** [comment] 2019-05-27 11:49
I'm closing this as fix. Please, reopen if any problem found.

**Comment by JoelProminic** [comment] 2019-05-29 20:42
I noticed that this new logic also affected the default parent directory for new projects on the App Store macOS build:
1. Delete the application data
1. Launch Moonshine.  
1. The Getting Started page is displayed because of Git and SVN.  Click configure and follow the prompts to allow access to /Library/Developer/CommandLineTools/
1. Create a new project (I tried Java Gradle).  BUG:  Parent Directory is set to "/Library/Developer/CommandLineTools" rather than the previous default (~/Containers/com.moonshine-ide/.../Desktop)
1. Create the progject in this directory anyway.  BUG:  Moonshine reports access errors:

    : Unable to access directory:/Library/Developer/CommandLineTools/TestJavaGradle_0529
    : Please open File > Access Manager and click "Add Access" to to allow access to this directory.
    : Unable to access directory:/Library/Developer/CommandLineTools/TestJavaGradle_0529/src
    : Please open File > Access Manager and click "Add Access" to to allow access to this directory.
    : Unable to access directory:/Library/Developer/CommandLineTools/TestJavaGradle_0529/src/main
    : Please open File > Access Manager and click "Add Access" to to allow access to this directory.
    : Unable to access directory:/Library/Developer/CommandLineTools/TestJavaGradle_0529/src/main/java
    : Please open File > Access Manager and click "Add Access" to to allow access to this directory.
    : Error #3215
    : ArgumentError: Error #3215
    : 	at Error$/throwError()
    : 	at flash.desktop::NativeProcessStartupInfo/set workingDirectory()
    : 	at actionScripts.languageServer::JavaLanguageServerManager/startNativeProcess()
    : 	at actionScripts.languageServer::JavaLanguageServerManager/preTaskLanguageServer()
    : 	at actionScripts.languageServer::JavaLanguageServerManager()
    : 	at actionScripts.impls::ILanguageServerBridgeImp/addProjectHandler()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugin.java.javaproject::CreateJavaProject/createSave()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at MethodInfo-25869()
    : 	at actionScripts.plugin.settings::SettingsView/save()
    : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
    :
    : Click here to Report a Bug
    : Error #3215
    : ArgumentError: Error #3215
    : 	at Error$/throwError()
    : 	at flash.desktop::NativeProcessStartupInfo/set workingDirectory()
    : 	at actionScripts.plugins.svn.commands::InfoCommand/request()
    : 	at actionScripts.plugins.svn.commands::RepositoryTestCommand()
    : 	at actionScripts.plugins.svn.provider::SubversionProvider/checkIfSVNRepository()
    : 	at actionScripts.plugins.svn::SVNPlugin/handleCheckSVNRepository()
    : 	at actionScripts.plugins.svn::SVNPlugin/handleProjectOpen()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at actionScripts.plugin.java.javaproject::CreateJavaProject/createSave()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at MethodInfo-25869()
    : 	at actionScripts.plugin.settings::SettingsView/save()
    : 	at actionScripts.plugin.settings::SettingsView/handleSaveClicked()
    :
    : Click here to Report a Bug 

I think macOS has restrictions on this directory, and it doesn't make sense to create projects here anyway.

If I import another project before creating a new project, I see that Parent Directory is set to the full path to the project.  This could be useful (though the user would probably want to use the parent of this project for the Parent Directory.

I think it would be better to use a fixed default value for Parent Directory until the user adds additional values.  If you have other concerns about this change, let me know.

**Comment by rat-moonshine** [comment] 2019-05-30 05:20
I'm a bit unclear with the above requirement and my test-output; Here are my test results with sandbox build of Moonshine:

1. Removed application data /Library/Containers/com.moonshine-ide
2. Start Moonshine, "Getting Started" tab opened
3. Accept to configure Git/SVN, opened file-browser to /Applications/XCode.app/Contents/Developer in my case (which should be fine too)
4. Accepted the browsing selection and closed "Getting Started"
5. Tried to import a project, file-browser opened to /Applications/XCode.app/Contents/Developer as expected
6. I changed my browsing to /Desktop/MyGradleProject and imported the project
7. Tried to create any other project now, I see the 'Parent Directory' starts with a fixed path in this case:
![image](https://user-images.githubusercontent.com/24370870/58610143-0924fd80-82c8-11e9-9e0f-b9013dced2fc.png)

While the above result might what you asked for:

> I think it would be better to use a fixed default value for Parent Directory until the user adds additional values. If you have other concerns about this change, let me know.

But on a second thought, this could have been right if the 'Parent Directory' could show the last browsed location in this case (which you mentioned in your test results as follows):

> If I import another project before creating a new project, I see that Parent Directory is set to the full path to the project. This could be useful (though the user would probably want to use the parent of this project for the Parent Directory.

I see something which requires to change from my tests, you also see something which requires to change - but they are different. So, I'm not clear what to change in what scenario.

**Comment by rat-moonshine** [comment] 2019-05-30 18:26
I able to reproduce the behavior after having more test-steps from @JoelProminic ,

> 1. Delete ~/Library/Containers/com.moonshine-ide
> 2. Open Moonshine
> 3. From the Getting Started Page, click the configuration icon next to Git or SVN
> 4. Accept the prompt, and click Open with the filechooser
> 4. File > New > New Java Gradle Project
> 5. The Parent Directory path has changed from the default.  In this cas it is /Applications/Xcode.app/Contents/Developer

We also think of following options for 'Parent directory' in above scenario:

> We could go two ways with this:
> 1. Use the same default directory under Containers/com.moonshine-ide
> 2. Try to determine the "workspace" from the imported project path. Using the full imported project path will be wrong - this is an individual project. Using the parent directory of the imported project is more likely to be right, but the AppStore build may not have access to this
> 3. Force the user to choose a directory the first time.  This may be an unnecessary distraction for new users, though

For now, I'm trying to restrict the 'Parent directory' option to 1 above.

**Comment by JoelProminic** [comment] 2019-05-30 20:17
The current behavior seems fine for the 2.3.0 release.

**Comment by piotrzarzycki21** [comment] 2019-06-05 11:07
I'm working on #465 I bump into an issue which probably was introduced by changes here. 
When I create `new FileLocation("incorrectpath") ` with non existing path - default it creates for me new object with last opened location. Definitely it shouldn't happen - I should rather get object with non existing path.

**Comment by rat-moonshine** [comment] 2019-06-05 11:16
Do you want me to check this or you want to check if you have hurry?

**Comment by piotrzarzycki21** [comment] 2019-06-05 11:41
> Do you want me to check this or you want to check if you have hurry?

Please check on your own. I would like to progress with #465 .

**Comment by piotrzarzycki21** [comment] 2019-06-06 13:28
@rat-moonshine Will you be able to look into that? It looks like I need fix for this in order to make proper changes to #465.

**Comment by rat-moonshine** [comment] 2019-06-06 14:10
Yes, give me tomorrow. I'll check this. Sorry, for hold you here.

**Comment by rat-moonshine** [comment] 2019-06-07 06:22
@piotrzarzycki21 Can you give me some more context to your test procedure? As in my initial tests I found creating a `new FileLocation("incorrectPath")` does retain the incorrect path value without replacing with last browsed location.

(I tested on Windows)

**Comment by piotrzarzycki21** [comment] 2019-06-07 09:35
> @piotrzarzycki21 Can you give me some more context to your test procedure? As in my initial tests I found creating a `new FileLocation("incorrectPath")` does retain the incorrect path value without replacing with last browsed location.
> 
> (I tested on Windows)

If you couldn't reproduced maybe I have some special scenario. I will look into that closer and maybe I will be able to fix it. I will get back to you.

**Comment by piotrzarzycki21** [comment] 2019-06-11 12:01
@rat-moonshine I would like to ask you look into that, cause I'm occupied by other tasks and this issue still prevent from correct work #465. Here is the scenario which should allows you to reproduce that and use debugger. Place breakpoint [here](https://github.com/prominic/Moonshine-IDE/blob/9b0d9e6c5b087bb343e3b430adb1d5acaa58786e/ide/MoonshineSharedCore/src/actionScripts/plugin/settings/renderers/PathRenderer.mxml#L129). 

Scenario:
1. Open Java Maven project using **Open/Import Project...** on home screen
2. Open another project using  **Open/Import Project...** on home screen
3. Go to the settings of project opened in **1**
4. Go to  Paths and choose **Change**

In the result you should see in the debugger:
![path](https://user-images.githubusercontent.com/24554795/59270156-1c818280-8c51-11e9-8063-28f2704096e7.gif)

Provided path is incorrect, but when I look inside FileLocation object I see that path exists and I see path to previous opened  project. - It definitely shouldn't work like that.

**Comment by rat-moonshine** [comment] 2019-06-11 15:18
Okay. I'll see this.

**Comment by rat-moonshine** [comment] 2019-06-11 15:54
You'll probably need to maintain full relative path of the file in configuration file, to make it appear correct and valid. 

If your path is incorrect then above behavior is correct. 

While file-browsing from anywhere it requires to open by last browsed location; If your path is correct in Paths section, then the browser will definitely open by the path, else it'll need to open by last-known valid-file-browsed location for the user. One thing to note that the actual paths collection to the project has no effect on above.

Now help me understand, programmatically in which area of your implementation the above changes creating you trouble, so we can discuss and find a way out for you.

**Comment by piotrzarzycki21** [comment] 2019-06-11 16:53
Well I don't thin it is correct. Couple of questions.

What is happening when you creat new File not in our application but in some test one - Do you fallback to some default path? 
How can I determine whether path exists when it is always fallback to default path?

IMO even if it should fallback in some last opened location - it should happen only in specific places - Not for all FileLocation class.

**Comment by JoelProminic** [comment] 2019-06-11 19:50
I confirmed the behavior @piotrzarzycki21 reported.  The "Main class" field seems to be a bit strange in that it is opened from a file path, but the actual saved  (and needed) value is just the class name.  The path could be reconstructed from the class name and class path, but only if there is only one class path:
![image](https://user-images.githubusercontent.com/24532731/59301857-31154900-8c58-11e9-8052-344732e6d82e.png)
![image](https://user-images.githubusercontent.com/24532731/59301863-35416680-8c58-11e9-908e-6ba9b61f57da.png)

**Comment by piotrzarzycki21** [comment] 2019-06-11 19:55
Joel it will work correctly once we agree on some solution in case of FileLocation class, cause I feel like it shouldn't change inself inside. Once you do that new FileLocation("path") - I should have my path regardless it's correct or incorrect.

**Comment by rat-moonshine** [comment] 2019-06-12 04:41
> 
> 
> Well I don't think it is correct. Couple of questions.
> 
> What is happening when you creat new File not in our application but in some test one - Do you fallback to some default path?
> How can I determine whether path exists when it is always fallback to default path?
> 
> IMO even if it should fallback in some last opened location - it should happen only in specific places - Not for all FileLocation class.

There were many test cases in Moonshine, which we required to cover by these changes. To answer your question whether it is correct to override any File with incorrect path situation - as I have mentioned [earlier](https://github.com/prominic/Moonshine-IDE/issues/520#issuecomment-499771848) that I have tested creating new File/FileLocation with incorrect path and they retains the incorrect value. So I **don't think the changes globally** affects File/FileLocation creations.

While in _paths_ section (in Settings) where we requires to open file-browsers specially, we required to handle temporary created file-path entries with added handling to cover many test-cases, which you noticed above. In _paths_ section the rules are simple - open by file-path if it is correct, open by last-known-valid-path if the entry-path is incorrect. However, you shall always have your project's original paths-collection as they are. If you do a Save in settings with incorrect path, they will save as it is!

So again, help me to understand what is causing you trouble programmatically to complete your task, I can look into and help.

**Comment by piotrzarzycki21** [comment] 2019-06-12 07:27
> So again, help me to understand what is causing you trouble programmatically to complete your task, I can look into and help.

Did you debug code according to my instruction ?

**Comment by rat-moonshine** [comment] 2019-06-12 07:35
Yes, and I know this is how it's suppose to happen in Paths sections. Now, if you tell me what is your implementation problem in whole picture (it'll be helpful if you guide me with some process-steps where you're facing problem to complete your task).

**Comment by rat-moonshine** [comment] 2019-06-12 08:33
Yes, I did and I know that this is how it's suppose to happen. 

Okay, let me give you more explanation on why this is happening in your case. 

A created `FileLocation` can be use anywhere for file-browsing. To make the browsing work the `File` object inside it requires to be a valid `File` object. (even you can get exception thrown when accessing `nativePath` if the File object is invalid)

Now we can see there are three types of states for a File object:
1. Correct-path and valid 
2. Incorrect-path but valid
3. Invalid

In case of _Invalid_ state you'll see the File object has error/exception marked to all its field and throws exception. To overcome this _invalid_ state problem AND support the rules for opening file-browsing from last-known-valid-path location AND keep the `FileLocation` object usable, every `FileLocation` object creates by a default path [initially](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IFileBridgeImp.as#L59). This keeps the `FileLocation` object valid and per browsing-rules. The `nativePath` thereafter updates by whichever value you gave.

In case of yours, this also have no difference. The `FileLocation` object you created with an incorrect path also initially created with last-known-valid-path location.

Now, here's the fun part. I see we have differences between our debug/tests with incorrect path value. When I tested this following path on Windows, I found that `FileLocation` **retain the incorrect path**:

`var location:FileLocation = new FileLocation("z:\\someFileName.mxml");`

While in your case, you see the path by which the `FileLocation` object initially created:
1. You tried to create a FileLocation object as `new FileLocation("someFileName.mxml") `
2. FileLocation initially created by a valid known location, say `c:\\Users\\$user\\Desktop`
3. Thereafter FileLocation object tried to set its `nativePath` by the value you given "someFileName.mxml"
4. You see the FileLocation object holds `c:\\Users\\$user\\Desktop`

Above case is clearly different than my test-result. 

When I tried to debug more of your case, I found at the time of set `nativePath` of the `File` object, it turns to an error (you probably see some log on your console too while happening this). Now this is where the fun part lies. It seems like the `File` API has its own algorithm to determine between a valid and an invalid path. I tried in a separate application for this:

Path value | `nativePath` set thrown error
---------------- | ----------------
MyFile.txt (doesn't exist) | Yes
z:\\myFile.txt (doesn't exist) | No

It looks like the provided path has to be of valid path type, else it'll turn to error handler when trying to save the File's `nativePath`. Since your `FileLocation` object initially created with a valid path location, you're seeing that in your debug test.

**Comment by piotrzarzycki21** [comment] 2019-06-12 10:18
> Yes, I did and I know that this is how it's suppose to happen.
> 
> Okay, let me give you more explanation on why this is happening in your case.
> 
> A created `FileLocation` can be use anywhere for file-browsing. To make the browsing work the `File` object inside it requires to be a valid `File` object. (even you can get exception thrown when accessing `nativePath` if the File object is invalid)
> 
> Now we can see there are three types of states for a File object:
> 
> 1. Correct-path and valid
> 2. Incorrect-path but valid
> 3. Invalid
> 
> In case of _Invalid_ state you'll see the File object has error/exception marked to all its field and throws exception. To overcome this _invalid_ state problem AND support the rules for opening file-browsing from last-known-valid-path location AND keep the `FileLocation` object usable, every `FileLocation` object creates by a default path [initially](https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineDESKTOPevolved/src/actionScripts/impls/IFileBridgeImp.as#L59). This keeps the `FileLocation` object valid and per browsing-rules. The `nativePath` thereafter updates by whichever value you gave.
> 
> In case of yours, this also have no difference. The `FileLocation` object you created with an incorrect path also initially created with last-known-valid-path location.
> 
> Now, here's the fun part. I see we have differences between our debug/tests with incorrect path value. When I tested this following path on Windows, I found that `FileLocation` **retain the incorrect path**:
> 
> `var location:FileLocation = new FileLocation("z:\\someFileName.mxml");`
> 
> While in your case, you see the path by which the `FileLocation` object initially created:
> 
> 1. You tried to create a FileLocation object as `new FileLocation("someFileName.mxml") `
> 2. FileLocation initially creates by a valid known location, say `c:\\Users\\$user\\Desktop`
> 3. Thereafter FileLocation object tried to set its `nativePath` by the value you given "someFileName.mxml"
> 4. You see the FileLocation object holds `c:\\Users\\$user\\Desktop`
> 
> Above case is clearly different than my test-result.
> 
> When I tried to debug more of your case, I found at the time of set `nativePath` of the `File` object, it turns to an error (you probably see some log on your console too while happening this). Now this is where the fun part lies. It seems like the `File` API has its own algorithm to determine between a valid and an invalid path. I tried in a separate application for this:
> 
> Path value	`nativePath` set thrown error
> MyFile.txt (doesn't exist)	Yes
> z:\myFile.txt (doesn't exist)	No
> It looks like the provided path has to be of valid path type, else it'll turn to error handler when trying to set the File's `nativePath`. Since your `FileLocation` object initially created with a valid path location, you're seeing that in your debug test.

Now it much more clear. In my case when I wanted to actually display File name which eventually is a class name I need to have some different type of setting renderer. Renderer which won't involve displaying path, but name of the file only.

**Comment by rat-moonshine** [comment] 2019-06-12 10:28
> Now it much more clear. In my case when I wanted to actually display File name which eventually is a class name I need to have some different type of setting renderer. Renderer which won't involve displaying path, but name of the file only.

You can customize to display the UI value to a pathRenderer to whatever you want I guess. But make sure you saves the path to configuration file as a relative path to the project (as other path values does).

**Comment by piotrzarzycki21** [comment] 2019-06-12 10:46
> You can customize to display the UI value to a pathRenderer to whatever you want I guess. But make sure you saves the path to configuration file as a relative path to the project (as other path values does).

Well our way of working is to do exactly what you are saying in many places. However I need display different things than PathRenderer do right now, so instead of baking another condition and part of the logic I prefer create dedicated renderer for that. I think I can close this issue. I make changes probably tomorrow.

**Closed by piotrzarzycki21** 2019-06-12 10:46 UTC
Labels: bug
