### ISSUE TITLE
Setting temporary env-variable for Git having space in its path creates project debugging problem

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#739] opened 2020-10-07 17:27 UTC
@joshtynjala reported this following problem/observation while testing #735 :

> I'm trying to test this, but I can't seem to build any of my Flex projects anymore. I get the following output in the console when I choose Build & Debug:
> 
> : Compiling NewFlexDesktopProject
> : Command: "C:\Users\josht\Development\flash\sdks\Flex4.16.1_AIR32\bin\mxmlc.bat" -load-config+=obj/NewFlexDesktopProjectConfig.xml -optimize=false +configname=air -debug=true
> : 'C:\Program' is not recognized as an internal or external command,
> : operable program or batch file.
> : 'C:\Program' is not recognized as an internal or external command,
> : operable program or batch file.
> It's probably worth mentioning that the path to my JDK is: C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot.
> 
> I remembered that I recently set the path to Git in my Moonshine settings. When I cleared that path, builds started working correctly.
> 
> It appears that the build was failing because Moonshine's setLocalEnvironment.cmd runs the following command, and it isn't properly escaping a Git path with spaces:
> 
> %GIT_HOME%\bin\git config --global http.sslCAInfo %GIT_HOME%\mingw64\ssl\cert.pem
> For reference, C:\Program Files\Git is the standard installation path on Windows, so handling spaces is very important.

I confirm the problem and it's worth a fix.

**Comment by rat-moonshine** [comment] 2020-10-07 17:56
I have escaped the problematic GIT_HOME path in temporary environment setup batch file. Here's how it looks when I tested:

```
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_162
set GIT_HOME=H:\Program Files\Git
...
"%GIT_HOME%\bin\git" config --global http.sslCAInfo "%GIT_HOME%\mingw64\ssl\cert.pem"
```

Both the "Build/Run" and "Build & Debug" this time working good without any exception thrown. 

I also gave some tests to Git functionalities in Moonshine, they seem to working expected way in my tests. 

However, I don't have an easy way to determine if the `sslCAInfo` command affects correctly since this command requires to overcome one particular test-case and I don't have that environment available to test. Running the batch file in command-line, didn't thrown any error, though.

@JoelProminic this issue is ready for your test.

**Comment by piotrzarzycki21** [comment] 2020-10-07 20:43
No please @Aszusz can you test?

**Comment by Aszusz** [comment] 2020-10-08 09:44
While Java and Git paths seem to be properly escaped I can still reproduce the core of this issue with different sdks' paths (Apache Royale).

My test scenario:
1. Rename SKDs folder `MoonshineSDKs` -> `Moonshine SDKs`
2. Update all paths in the Settings
3. After Build & Run I get ` 'C:\Moonshine' is not recognized as an internal or external command`

**Comment by piotrzarzycki21** [comment] 2020-10-08 09:53
Well if we are able to use Moonshine having setup GIT and Java - issue with space in paths for SDK is something which we can leave as is. It is also well known issue to me. I'm using path to sdk without space for a long time.

**Comment by rat-moonshine** [comment] 2020-10-08 15:35
> My test scenario:
> 
> 1. Rename SKDs folder MoonshineSDKs -> Moonshine SDKs
> 2. Update all paths in the Settings
> 3. After Build & Run I get 'C:\Moonshine' is not recognized as an internal or external command

Yeah... Thanks for reporting this @Aszusz . Can you email me your `setLocalEnvironment.cmd` (you can find it under C:\Users\$user\AppData\Roaming\com.moonshine-ide\Local Store)?

I tried to give a test by the way you did. I was able to build and run successfully when the SDKs are residing in a path value having space. As an additional step, I also tried to place the project-folder in a directory that has space in its name. That also ran well for me.

**Comment by Aszusz** [comment] 2020-10-08 16:59
@rat-moonshine

Here's the content of the I had when I originally run the test:
```
@echo off
set JAVA_HOME=C:\Program Files\OpenJDK\jdk-15
set ANT_HOME=C:\ProgramData\chocolatey\lib\ant\tools\apache-ant-1.10.8
set GIT_HOME=C:\Moonshine SDKs\Git\git-2.20.1
set ROYALE_HOME=C:\Moonshine SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs
set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%ROYALE_HOME%\bin;%PATH%
"%GIT_HOME%\bin\git" config --global http.sslCAInfo "%GIT_HOME%\mingw64\ssl\cert.pem"
set ROYALE_HOME="C:\Moonshine^ SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs"&& set && "C:\Moonshine^ SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\js\bin\mxmlc.bat" -load-config+=obj/NewJavaScriptBrowserProjectConfig.xml -debug=true   -compiler.targets=JSRoyale -js-output="C:\Data\Documents\NewJavaScriptBrowserProject"
```

After I collected the file I went to `Help -> About` to make sure I'm using the correct build (it is 3.0.0 build 250) I saw the spinner spinning and Moonshine IDE detecting my SDKs one by one. Then, I noticed the file has changed. Here's the new content:

```
@echo off
set JAVA_HOME=C:\Program Files\OpenJDK\jdk-15
set ANT_HOME=C:\ProgramData\chocolatey\lib\ant\tools\apache-ant-1.10.8
set GIT_HOME=C:\Moonshine SDKs\Git\git-2.20.1
set ROYALE_HOME=C:\Moonshine SDKs\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs
set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%ROYALE_HOME%\bin;%PATH%
"%GIT_HOME%\bin\git" config --global http.sslCAInfo "%GIT_HOME%\mingw64\ssl\cert.pem"
"C:\Program Files (x86)\HCL\Notes/nsd.exe" -version
```

I still couldn't build a project.

For a reference, when I switched back to a path without a space I had no problem building a project. Here's setLocalEnvironment.cmd file that works OK for me:
```

@echo off
set JAVA_HOME=C:\Program Files\OpenJDK\jdk-15
set ANT_HOME=C:\ProgramData\chocolatey\lib\ant\tools\apache-ant-1.10.8
set GIT_HOME=C:\Moonshine SDKs\Git\git-2.20.1
set ROYALE_HOME=C:\moonsdk\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs
set PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin;%ROYALE_HOME%\bin;%PATH%
"%GIT_HOME%\bin\git" config --global http.sslCAInfo "%GIT_HOME%\mingw64\ssl\cert.pem"
set ROYALE_HOME="C:\moonsdk\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs"&& set && "C:\moonsdk\Royale_SDK\apache-royale-0.9.8-bin-js\royale-asjs\js\bin\mxmlc.bat" -load-config+=obj/NewJavaScriptBrowserProjectConfig.xml -debug=true   -compiler.targets=JSRoyale -js-output="C:\Data\Documents\NewJavaScriptBrowserProject"
```

**Comment by JoelProminic** [comment] 2020-10-08 17:18
> However, I don't have an easy way to determine if the `sslCAInfo` command affects correctly since this command requires to overcome one particular test-case and I don't have that environment available to test. Running the batch file in command-line, didn't thrown any error, though.

I found the old issue for this here #487.  This was triggering because Git expected the SSL certs to be in the default directory under Program Files.   So, the only requirement to check this is that Git is not installed in the default location (but this is the specific setup we were testing for this issue).

Since this set globally, I verified the that the property was set properly from a CMD prompt:  `git config --global http.sslCAInfo`

**Comment by rat-moonshine** [comment] 2020-10-09 09:05
> I still couldn't build a project.
> 
> For a reference, when I switched back to a path without a space I had no problem building a project. Here's setLocalEnvironment.cmd file that works OK for me:

Yeah, this appears to be more of a Royale SDK-only problem but Flex. When I was able to compile and run a Flex project having space in the path for its SDK and Java, Git, SVN etc., changing the Royale SDK path with space breaks the compilation in my test.

I'd suggest you create an issue so this remains on our radar and re-visit when time is appropriate.

**Comment by piotrzarzycki21** [comment] 2020-10-09 17:07
It looks like we are good with this issue ?

**Comment by rat-moonshine** [comment] 2020-10-12 04:29
Better create an issue on [this](https://github.com/prominic/Moonshine-IDE/issues/739#issuecomment-706063869) finding, set it to 3.1 and let's close this issue, and push for v3.0 release.

**Comment by Aszusz** [comment] 2020-10-12 13:18
I'm closing this issue and opening https://github.com/prominic/Moonshine-IDE/issues/741

**Closed by Aszusz** 2020-10-12 13:18 UTC
Labels: bug
