### ISSUE TITLE
Commiting and Reverting changes doesn't work when Git path contains whitespaces

### ISSUE THREAD

**Issue by Aszusz** [prominic/Moonshine-IDE#763] opened 2020-12-11 18:00 UTC
When I was testing our Git integration today I discovered I can no longer commit or revert changes.

After Git -> Commit:
![image](https://user-images.githubusercontent.com/7197014/101937376-140d5d80-3be2-11eb-8c71-e4be516d3504.png)

After Git -> Status -> Select File -> Revert Selected
![image](https://user-images.githubusercontent.com/7197014/101937513-3d2dee00-3be2-11eb-9520-34eb04cb3d44.png)
It looks like a success but the file is unchanged and the file is still present in Status window. The change was a simple line addition, nothing fancy.

My Git path:
![image](https://user-images.githubusercontent.com/7197014/101937745-8da54b80-3be2-11eb-954d-918914385a07.png)

Tested on:
![image](https://user-images.githubusercontent.com/7197014/101937835-aca3dd80-3be2-11eb-9e27-c3777175eec4.png)
(Dec 11 nightly)

Related issues: #739 #741

**Comment by rat-moonshine** [comment] 2020-12-14 05:05
Yeah, this is a known issue and reported as #641 in past. I didn't have any solution till the time of the investigation. We need to re-visit this at some time.

**Comment by JoelProminic** [comment] 2020-12-16 17:46
It looks to me like this is duplicate of #641.  I'm closing this issue and we'll continue work in #641.

**Closed by JoelProminic** 2020-12-16 17:46 UTC
Labels: bug
