### ISSUE TITLE
Build and Run Command doesn't work

### ISSUE THREAD

**Issue by Nisaba** [prominic/Moonshine-IDE#252] opened 2018-04-28 17:56 UTC
Hi,
For some reason, the Control + Enter command doesn't work anymore on my project; although it worked well before...

The project builds well but it doesn't run anymore...

**Comment by piotrzarzycki21** [comment] 2018-04-28 19:37
Try following steps:
- Close all projects
- Reset all settings - you should find option for that in general settings.
- Setup everything and open project again

**Comment by Nisaba** [comment] 2018-04-28 19:49
done,
but the project doesn't run...

**Comment by piotrzarzycki21** [comment] 2018-04-29 03:07
What do you see in the console when you choose from menu Build & Run?

**Comment by piotrzarzycki21** [comment] 2018-04-29 11:25
I think I see that one with one of my Apache Royale project. I thought it something wrong with my project, but it looks like not. It's hard to reproduce, but I will try to take a look into that tomorrow! 

Thanks for trying Moonshine!

**Comment by piotrzarzycki21** [comment] 2018-04-30 15:59
I couldn't find root cause of that issue, but I have added console logs when application is launching and started. Once next version will be release I will ask you for some retest.

**Comment by Nisaba** [comment] 2018-04-30 18:44
ok, no problem !

**Comment by apintex** [comment] 2018-05-11 11:08
Hello,

I have the same problem on macOS. 
Is a project Actionscript Desktop and try to run in AIR 29
I sent you images of the problem
<img width="1026" alt="captura de ecra 2018-05-11 as 11 54 30" src="https://user-images.githubusercontent.com/6188954/39921758-ffb3654e-5513-11e8-9966-37e364f215f8.png">
<img width="1048" alt="captura de ecra 2018-05-11 as 11 55 13" src="https://user-images.githubusercontent.com/6188954/39921759-ffd1d060-5513-11e8-9f9b-3274ea0650c2.png">
<img width="1920" alt="captura de ecra 2018-05-11 as 11 56 03" src="https://user-images.githubusercontent.com/6188954/39921760-ffee0550-5513-11e8-85ab-ce1aa9a56a75.png">
<img width="1919" alt="captura de ecra 2018-05-11 as 12 01 23" src="https://user-images.githubusercontent.com/6188954/39921761-000c367e-5514-11e8-8295-64f117546500.png">





<img width="1048" alt="captura de ecra 2018-05-11 as 11 55 13" src="https://user-images.githubusercontent.com/6188954/39921713-e123315e-5513-11e8-8c95-ac4d62d19b74.png">
<img width="1920" alt="captura de ecra 2018-05-11 as 11 56 03" src="https://user-images.githubusercontent.com/6188954/39921714-e1405f2c-5513-11e8-9a2c-fc3a4e1e10bb.png">
<img width="1919" alt="captura de ecra 2018-05-11 as 12 01 23" src="https://user-images.githubusercontent.com/6188954/39921715-e15df92e-5513-11e8-9527-67c61d66eaa2.png">

**Comment by piotrzarzycki21** [comment] 2018-05-11 11:10
@apintex can you show me what is in Test01-app.xml ? If this is an tests project can you attach it here ?

**Comment by Nisaba** [comment] 2018-05-11 11:32
Piotr,
My problem remains with the 1.12.0 version.

Here is the console log : 

: bin-debug/GeoDomaine.swf (3982901 bytes)
: (fcsh) 
: Copying resource: Geo-Domaine-Moonshine
: Project Build Successfully.

**Comment by piotrzarzycki21** [comment] 2018-05-11 11:34
@Nisaba how big those resources are ? Is it couple of megabytes ?

**Comment by Nisaba** [comment] 2018-05-11 11:38
You speak about the swf ?
Its size is 1929 KB.

Geo-Domaine-Moonshine is the entire project directory and its size is 268 MB

**Comment by piotrzarzycki21** [comment] 2018-05-11 11:40
Let me ask you in a different way - What do you have setup here ? In project Settings.
![resource_folders](https://user-images.githubusercontent.com/24554795/39922744-ce740e68-5520-11e8-937b-aa69c7a9e79b.png)

**Comment by piotrzarzycki21** [comment] 2018-05-11 11:44
@Nisaba I would like to resolve that problem. If I prepare for you Moonshine version with some additional logs will have time to test and send me console results? If you want it can be in a private message by email.

**Comment by Nisaba** [comment] 2018-05-11 12:15
The src path size is only 790 KB
The lib path size is 290 KB
The ane path size 19 MB.
It contains the webviewane extension that is very big (also many dlls in the compiler path)

Ok for the version with additional log.

**Comment by piotrzarzycki21** [comment] 2018-05-11 12:40
@Nisaba Can you send me an email to piotrzarzycki21@gmail.com - I will respond you back with the build. Are you using Win or Mac ?

**Comment by apintex** [comment] 2018-05-15 14:43
Of course yes. I'm waiting

António Pinto
apintex@gmail.com

**Comment by piotrzarzycki21** [comment] 2018-05-16 10:06
@rat-moonshine After several emails with @Nisaba I was able to locate what was wrong. He simply import project from Flash Builder and in project "Settings" -> "Paths" -> "Resource folders" were added path: "/" - which means copy everything what you have in the project directory - which is not correct. That's why copying simply failing. Do you have any idea how could we avoid that 

I do think that we may not interpret something from Flash Builder correctly. Could you check that area once you get time ? 

I'm going to work a bit on Resource copying mechanism. I think it should be part of the build at some point. I'm simply going to change it in the following way:

Once build of swc is finished, start copying resource (this is how it works right now), BUT do not notify user about finished/successful build  - rather wait till copying will be finished.

**Comment by rat-moonshine** [comment] 2018-05-16 11:27
> He simply import project from Flash Builder and in project "Settings" -> "Paths" -> "Resource folders" were added path: "/" - which means copy everything what you have in the project directory - which is not correct. That's why copying simply failing. Do you have any idea how could we avoid that

I think in practical scenario we should force the user to map a valid path other than the default "/" entry which is adding when "Click to Add" button pressed:
![image](https://user-images.githubusercontent.com/24370870/40114084-30f7104c-5929-11e8-93ff-817239754d1a.png)

Irrespective of the fact that "/" is a valid path, this may not be an intentional input by design. So my thought is to prevent showing "/" after "Click to Add" button press and add some conditional check to accept the entry unless user locate a physical path by file browser dialog. 

I think most of the requisite parts already we're reading from a Flash Builder project (I need to see about Native Extension - I didn't covered that part during this parsing) to populate requisite class paths, library paths etc. However, Flash Builder do not has any concept of saving "Resource Folders". FB has its own mechanism to point out the assets type of files from the project and get copied to the bin-debug folder. We have "Resource Folders" in that place in Moonshine (to get copied the marked folders). 

> Once build of swc is finished, start copying resource (this is how it works right now), BUT do not notify user about finished/successful build - rather wait till copying will be finished.

Unfortunately, I'm not clear about the above part.

**Comment by rat-moonshine** [comment] 2018-05-16 11:31
I confirm the problem raised by @apintex .

**Comment by piotrzarzycki21** [comment] 2018-05-16 11:32
> I think in practical scenario we should force the user to map a valid path other than the default "/" entry which is adding when "Click to Add" button pressed:
> image
> 
> Irrespective of the fact that "/" is a valid path, this may not be an intentional input by design. So my thought is to prevent showing "/" after "Click to Add" button press and add some conditional check to accept the entry unless user locate a physical path by file browser dialog.

Agree with you on that part!

As for the building and my changes I'm simply trying to achieve following order:

![image](https://user-images.githubusercontent.com/24554795/40114502-7800901a-590d-11e8-842f-a154586f8d5a.png)

As you can see I'm notifying user that project is successfully build once resources are copied, not before as it is working now. Those changes are not yet committed - I'm testing several scenarios.

**Comment by piotrzarzycki21** [comment] 2018-05-16 11:33
> I confirm the problem raised by @apintex .

Ohh! Great! Are you going to fix that? If not send me some details I will do that.

**Comment by rat-moonshine** [comment] 2018-05-16 11:42
I can take a look into this.

**Comment by piotrzarzycki21** [comment] 2018-05-16 11:43
Thank you!

**Comment by rat-moonshine** [comment] 2018-05-16 12:30
Initially I had a broken downloaded Flex SDK with AIR 29.0 (missing swf launcher file in the SDK) which results me the same scenario as @apintex reported. Once I re-downloaded a fresh copy of the SDK, I couldn't able to reproduce the problem anymore with 1.12.0. 

The error message in @apintex 's first image - invalid application descriptor - unknown namespace.. - generally this is not supposed to come as Moonshine adjust the namespace version of descriptor file based on the running SDK/AIR at the time of compilation/launching. I can only ask to provide us some more information to pin-point the problem, by providing the demo project you were using @apintex .

**Comment by piotrzarzycki21** [comment] 2018-05-16 13:58
I'm done with the changes here. I improved copying resources. We have left in that issue with path problem "/" and @apintex issue. I'm leaving to you the rest @rat-moonshine . I will assist with @apintex issue if needed.

**Comment by apintex** [comment] 2018-05-17 10:28
Hi,

The project demo is a simple Actionscript project desktop standard, create with the template of Moonshine, without any modifications.

António Pinto
apintex@gmail.com



> No dia 16/05/2018, às 13:30, devsena <notifications@github.com> escreveu:
> 
> Initially I had a broken downloaded Flex SDK with AIR 29.0 (missing swf launcher file in the SDK) which results me the same scenario as @apintex <https://github.com/apintex> reported. Once I re-downloaded a fresh copy of the SDK, I couldn't able to reproduce the problem anymore with 1.12.0.
> 
> The error message in @apintex <https://github.com/apintex> 's first image - invalid application descriptor - unknown namespace.. - generally this is not supposed to come as Moonshine adjust the namespace version of descriptor file based on the running SDK/AIR at the time of compilation/launching. I can only ask to provide us some more information to pin-point the problem, by providing the demo project you were using @apintex <https://github.com/apintex> .
>

**Comment by rat-moonshine** [comment] 2018-05-17 13:26
@piotrzarzycki21 can you give a try on Windows with Flex/AIR 29.0 and see if you can reproduce the problem @apintex reported with Moonshine 1.12.0 (?)

**Comment by piotrzarzycki21** [comment] 2018-05-17 13:27
Antonio contacted with me and I tried on Mac and Windows. Everything working perfectly with Moonshine 1.12.0.

**Comment by piotrzarzycki21** [comment] 2018-05-17 13:27
If you could fix problem with path witch experience @Nisaba that would be good

**Comment by piotrzarzycki21** [comment] 2018-05-17 13:28
One more think I propose to him send my SDK to see whether he experience same issue. I would like to exclude scenario which you have run into where SDK was broken.

**Comment by piotrzarzycki21** [comment] 2018-05-18 09:25
@rat-moonshine I got from @apintex following screenshot where he tried build pure AS3 Desktop application and it didn't run:

![img_project](https://user-images.githubusercontent.com/24554795/40226804-fa1e200a-5a8c-11e8-9996-10ff89b47abf.png)

His Mac build is yesterdays one which you have sent me. In the console log we can see that application is trying launch, so we are [here](https://github.com/prominic/Moonshine-IDE/blob/f1aea7f953ea13c70f3c77c0cda179553e53cd23/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/as3project/mxmlc/MXMLCPlugin.as#L1041).

Next what we should get in the console logs is this [log](https://github.com/prominic/Moonshine-IDE/blob/f1aea7f953ea13c70f3c77c0cda179553e53cd23/ide/MoonshineDESKTOPevolved/src/actionScripts/plugins/swflauncher/SWFLauncherPlugin.as#L87). Do you have any idea why that method is not fire by the event? What is happening that this event didn't pass there ?

**Comment by rat-moonshine** [comment] 2018-05-18 09:44
In my earlier test case (where my build failed because a broken SDK), That was also fall flat at the time of launching the SWF. Unfortunately, I don't have any immediate idea to support against this issue, until we have a clear way to reproduce the problem. 

I've added new feature plan which might help us in future in likewise cases #268 , though.

**Comment by piotrzarzycki21** [comment] 2018-05-18 11:29
I suggest send me development build for Mac once you will have some code ready for #268. I will send @apintex to see whether we have some exception. Btw. Can you build version with debug = "true" ? That may help to discover what actually is happening.

**Comment by JustinProminic** [comment] 2018-05-18 11:51
Some code already added against #268. That should print something to the console for now.

**Comment by rat-moonshine** [comment] 2018-05-18 11:56
Some code already added to #268 that should print something to console for now. A package installer do not print anything irrespective of debug=true. You can send him the .app as well for this test; That should work, too.

**Comment by piotrzarzycki21** [comment] 2018-05-18 12:15
We have had some problems with running .app, so avoid any disturbance if you could provide me installer. The other options is provide me an instruction how to prepare installer on Mac. It can be through email.

**Comment by piotrzarzycki21** [comment] 2018-05-22 11:05
@rat-moonshine I have sent Antonio latest build and he reported that it's working now. I'm not 100% sure what has happened. However we are good with that issue.

**Closed by piotrzarzycki21** 2018-05-22 11:05 UTC
Labels: bug

**Comment by atingupta2005** [comment] 2018-05-23 04:38
Please provide a test case to reproduce the reported issue. There are a lot of comments in the issue and thus its not very much clear that what should be tested

**Comment by piotrzarzycki21** [comment] 2018-05-23 06:13
@atingupta2005 actually if you do tests for #272 we will be good here as well.
