### ISSUE TITLE
Find Resources Search String Does Not Automatically Clear When Typing While Selected.

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#177] opened 2018-02-08 21:07 UTC
I noticed this bug with the Find Resources prompt:
1. Open Moonshine
2. Edit > Find Resources
3. Enter a search string. The list filters properly
4. Use the mouse or CTRL-A to select the search string.
5. Press a key
6. BUG:  the selection clears, but the text is not cleared.  The typed key is appended to the end of the string.

If I used the Backspace or Delete key on the selected text, the search string is cleared properly.

**Comment by piotrzarzycki21** [comment] 2018-04-06 10:32
I think that's ok!

**Comment by JoelProminic** [comment] 2018-04-06 17:02
The selected text behaves the way I expect with the latest update:
- Typing text overwrites the selected string
- Delete or Backspace work to clear the string
- The arrow keys can be used to clear the selection.


I did notice an unexpected behavior with the arrow keys:
1. Enter a search string
2. Press the down arrow.  The selected result row changes
3. Press the right arrow.  The search string text is selected.   This was unexpected, but I don't see an obvious problem with it.
4. Press the right arrow again.  The selection clears, and the left and right arrow keys work normally on the search string text.
5. Press the down arrow.  The focus shifts to the results again
6. Press a letter key.  The search string is cleared and replaced with the entered string.  I feel this behavior could be annoying to some users, but I don't know how frequently it would be triggered.

@piotrzarzycki21, did you intentionally implement this behavior?   I don't have strong feelings about this behavior, so I don't mind keeping it if you have a preference for this behavior.

@rat-moonshine reported in Flash Builder, the only way to return to the search field is to use Shift-Tab.

**Comment by piotrzarzycki21** [comment] 2018-04-09 12:09
@JoelProminic In case of steps 1-2 when you press down arrow and selected row changes - Yes that part I did implement intentionally. 

I'm using that window very often and ninety percent of usage is by keyboard not mouse clicking. Since I need find something very fast following scenario was annoying to me a lot.
1. I'm opening Find Resources by shortcut
2. Enter a search string and Got for example 5 results. Mine is for example in the 3 row.
3. I'm selecting row by keyboard 
4. Confirm by Enter 

Absolutely no mouse usage.

Previously I had to press two times arrow down on keyboard to move selection.
First press: Make List focused
Second press: Make second row selected

My implementation makes things easier. I will definitely look into the rest of unexpected behavior. I think  pressing right arrow (step 3) should jump cursor at the end of search string.

**Comment by piotrzarzycki21** [comment] 2018-04-09 12:37
@JoelProminic I have pushed fix. It is note ideal but I think it mainly resolves problems in steps 3 and 6.

**Comment by JoelProminic** [comment] 2018-04-09 15:33
@piotrzarzycki21, I agree with your desire to reduce the dependencency on the mouse.  I like the current down-arrow functionality - it feels very natural.

The update feels pretty good to me.  The behavior seemed pretty intuitive and comfortable.

Something to consider:  Using the right-arrow to return to the search field is a bit unnecessary now, since pressing any key will automatically start typing in the field anyway.   If you have a use case to quickly replace the current search string and type a new one, then it may make sense to select the entire string when using the right-arrow (though you could do the same thing with CTRL-A).  I know this is the same behavior I reported as "unexpected", but I don't have a problem with it if you find it to be useful functionality.

**Comment by rat-moonshine** [comment] 2018-04-10 07:04
I have a slight different test case in my tests. Perhaps, we want to restrict to move the cursor at the end of the entered text by left and right arrow only. Here is why I think this:

- Open a project having large amount of files to test this (i.e. MoonshineDESKTOPevolved)
- Open project search window
- Type "con" - this shall filter the result list
- Press down arrow to activate key navigation into the result list
- Press "t" - this will highlight the first file instance start with "t", which looks good
- Press "t" again to select/highlight next file instance start with "t"
- List filtered because cursor already auto-moved to the search input when we entered our first "t" [not right]

Based on last two steps above, the functionality against key-presses are not similar.

**Comment by JoelProminic** [comment] 2018-04-10 17:02
I confirmed the behavior that @rat-moonshine reported above.   This behavior did not trigger for me in my earlier tests because the character I typed did not match the first character of either of the results.

So, we have two different strategies for handling characters entered while the focus is on the result list:
1. Update the filter with the entered character
2. Go to the next result that starts with that letter.  This can be used repeatedly to iterate through the list

However, the current code will use solution 2 for the first character (if it matches), and solution 1 for any additional characters.  I would like to resolve this inconsistent behavior either way.

To me, option 1 seems like something I would use more commonly.   @rat-moonshine preferred solution 2, though.  @piotrzarzycki21, do you have an opinion on this?

**Comment by rat-moonshine** [comment] 2018-04-11 03:30
My suggestion is to keep goodness of both the worlds by restricting keys:

- While using arrow keys, restrict left and right arrow key to return the cursor back to the input field (right hand), this should satisfy @piotrzarzycki21 's preference of working
- Using any keys other than the arrow keys should continue follow the List component's regular behavior, i.e. selecting next result that start by the letter pressed (left hand)

**Comment by piotrzarzycki21** [comment] 2018-04-13 13:55
@rat-moonshine have you done those changes with restriction ? Is this issue finished ?

**Comment by JoelProminic** [comment] 2018-04-13 16:30
I confirmed that pressing characters in the result panel behaves as @rat-moonshine described above - the selection shifts to the next result that starts with that character.

This makes it possible to browse to a result without moving your hands from home row:
1. Type search string
2. Hit Tab 
3. Type the first letter of the desired class until it is selected
4. Hit Enter 

However, the Tab key currently shifts the focus to the filter button instead.  No actions can be performed on this button.  Pressing Tab again will shift the focus to the results.   If we can change the focus order so that you can go directly to the results, that will make this more intuitive.

**Comment by rat-moonshine** [comment] 2018-04-16 06:34
Tab and Shift+Tab handlers now added to the interface. Following are the test results:

1. Type search string
2. Press Tab
3. Result list focused with having the pointer to its last selected item
4. Type any letter key to jump to the desired item starts by the letter
5. Type Shift+Tab, this will return the cursor to the search input field (similar by pressing Left/Right arrow)

**Closed by rat-moonshine** 2018-04-16 06:34 UTC
Labels: bug

**Comment by JoelProminic** [comment] 2018-04-16 16:09
Tab and Shift-Tab seem to work like I expect now.
