### ISSUE TITLE
Improvement for "Select SDK" window - better describe similar sdk

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#767] opened 2020-12-18 10:37 UTC
As part of this issue we need to improve "Select SDK" window where user have list of his sdk's which he can pickup. We need to take care of scenario where we could open two or more times for example Flex SDK. Entries showed on the list may confuses user cause Description column will contains same value. 

Example where I have same SDK, but different location. 
![same_sdk](https://user-images.githubusercontent.com/24554795/102605273-56282900-4125-11eb-936b-03c2883b1b25.png)

**Comment by piotrzarzycki21** [comment] 2020-12-18 10:37
@JoelProminic over the call noticed also some issue on Mac with cached SDKs - we should take care of that as part of this issue as well.

**Comment by rat-moonshine** [comment] 2021-01-04 10:17
The first part of this issue is now addressed. You can now edit/custom-name an SDK without having any problem with usage. 

The second part which is a bug, I'm looking into that.

**Comment by rat-moonshine** [comment] 2021-01-04 11:40
Duplication of "bundled" items in sdk-list on macOS is now fixed.

**Comment by JoelProminic** [comment] 2021-01-04 18:27
The duplicate SDKs were mostly cleaned up for me in this update.   The remaining problems may be SDKs I added manually at some point.   I deleted these entries and I'll watch for them to reappear again.

I confirmed that I can set a custom SDK name, but I found the process awkward:
1. Open the SDK list
2. Click Add
3. Type a custom label
4. Choose the SDK path
5. The custom label is overwritten by the default label for the selected SDK
6. Type the custom label again.

I think if we switch the order of the fields, this will be more intuitive.  If the user selects the path first, then the default label will be available for a small edit.
1. Open the SDK list
2. Click Add
3. Choose the SDK path
4. The label is populated
5. Edit or replace the label, or use the default label if desired.

The user could still choose to start with the custom label first, though, so we may also want to prevent ovewriting the label after choosing the path if the user has already entered a value.

**Comment by rat-moonshine** [comment] 2021-01-05 06:14
Updates:

- Field ordering is now changed giving preference to browse field
- Prevented overwriting to the "name" field after choosing a path if the user already entered some value to the field

**Comment by piotrzarzycki21** [comment] 2021-01-05 10:53
Would it be possible to have editable column in grid ? It would be much more convenient than clicking on edit.

**Comment by rat-moonshine** [comment] 2021-01-06 11:21
Updates:

- Re-browsing SDK directory does not update the name-field - fixed 
- Modified name-value saves with "(js)" suffix for Royale project in the sdk-list - fixed

**Comment by JoelProminic** [comment] 2021-01-06 17:37
The updates seem good.  Here are some additional requests from our discussion today:
- Open Edit prompt when double-clicking on an entry
- When editing, the "Create" button should be "Update"
- Show a tooltip with the full path when hovering over the Path in the Edit window

**Comment by rat-moonshine** [comment] 2021-01-07 06:45
It is possibly double-click event is not available to the GridView in Feathers (or as I couldn't found in its API/doc). Adding a double-click event to the grid doesn't work. 

The other two requests addressed. 
> 
> When editing, the "Create" button should be "Update"
> Show a tooltip with the full path when hovering over the Path in the Edit window

**Comment by rat-moonshine** [comment] 2021-01-07 16:20
@joshtynjala do we have double-click event available to Feathers GridView (?) I couldn't found any reference of the event in the API doc but I could be wrong.

**Comment by joshtynjala** [comment] 2021-01-07 17:33
It's possible to add the standard MouseEvent.DOUBLE_CLICK to anything in Feathers UI, including the cell renderers in GridView. Be sure to set doubleClickEnabled to true, of course. You can do this in the cellRendererRecycler.

I should probably update the GridViewEvent to add ITEM_DOUBLE_CLICK, though. That would probably be easier, since you can be sure to have access to the GridViewItemState in the listener. Until then, you can access the ItemRenderer's data property in the listener, which should be enough.

**Comment by rat-moonshine** [comment] 2021-01-08 07:40
Thank you for the startup tip, @joshtynjala . Based on my limited understanding to these codes, I managed to have this constructed in this way:

descriptionColumn.cellRendererRecycler = DisplayObjectRecycler.withClass(ItemRenderer, (target, state:GridViewCellState) -> {
	target.text = state.text;
	target.toolTip = state.text;
	target.doubleClickEnabled = true;
});

I see the `target` here is an ItemRenderer which has `doubleClickEnabled` property (in debug) so which should be good to be set in this way.

If the above part was how you meant to be the way, I failed to find a proper location where to add the DOUBLE_CLICK listener next. 

I tried with both of the following but I didn't received any double-clicked event:
```
descriptionColumn.addEventListener(MouseEvent.DOUBLE_CLICK, sdkGrid_doubleClickHandler);
// or
this.sdkGrid.doubleClickEnabled = true;
this.sdkGrid.addEventListener(MouseEvent.DOUBLE_CLICK, sdkGrid_doubleClickHandler);
```

**Comment by joshtynjala** [comment] 2021-01-08 17:07
```hx
descriptionColumn.cellRendererRecycler = DisplayObjectRecycler.withClass(ItemRenderer, (target, state:GridViewCellState) -> {
	target.text = state.text;
	target.toolTip = state.text;
	target.doubleClickEnabled = true;
	target.addEventListener(MouseEvent.DOUBLE_CLICK, sdkGrid_doubleClickHandler);
});
```

**Comment by rat-moonshine** [comment] 2021-01-08 17:25
The second `(target, state:GridViewCellState) ->` I suppose it is the reset part (?) Do we need to declare the 'destroy' part also to remove the listeners, or reset automatically get called during the gc?

**Comment by joshtynjala** [comment] 2021-01-08 18:04
Yes, that's the `reset` function that goes along with `update`. A `destroy` function usually isn't needed, unless there's something that you did in the `create` function that needs to be cleaned up.

The `reset` is function is guaranteed to be called before an item renderer is either reused or destroyed.

**Comment by rat-moonshine** [comment] 2021-01-11 09:34
Thank you @joshtynjala . I tried to follow by the steps, but I'm not receiving any double-click event yet. Here's my [updates](https://github.com/prominic/Moonshine-IDE/commit/1392ceb26137c091e6fc46bf9a603ee3adf4406f), perhaps you can point me to any other thing that I might missed (?)

**Comment by joshtynjala** [comment] 2021-01-11 18:10
I feel like I always run into trouble with DOUBLE_CLICK events in Flash. Try setting mouseChildren = false on the ItemRenderer too. Sometimes, that's required to listen for clicks and double-clicks because Flash won't dispatch those events if the child mouse target changes between the initial MOUSE_DOWN and the final MOUSE_UP. If the ItemRenderer's current skin or something is changing based on the mouse state, that could be why. mouseChildren will force the target to always be the ItemRenderer.

**Comment by joshtynjala** [comment] 2021-01-11 21:17
I just noticed that I needed to set mouseChildren = false similarly to get DOUBLE_CLICK working with an ItemRenderer in LocationsView:

https://github.com/prominic/Moonshine-IDE/blob/v3.0.0/ide/MoonshineGUICore/src/moonshine/plugin/locations/view/LocationsView.hx#L109

**Comment by rat-moonshine** [comment] 2021-01-12 05:08
Yeah, that worked. Thanks!

This issue is now ready for test and close.

**Comment by JoelProminic** [comment] 2021-01-12 18:15
Double-clicking to edit works fine now.

The only remaining issue I see is that edits to the bundled SDK names do not persist:
1. Double-click on the "Apache Flex 4.16.1..." entry
2. Add "Edit" to the end of the label
3. Save the settings
4. Restart Moonsine
5. BUG:  The SDK does not show the edited name.

I see two solutions for this:
- Allow the user to edit the labels for the bundled SDKs and have Moonshine check the path name.
- Disable edits on the bundled SDKs.  I think this is how we handled this previously, and I think it makes sense to keep these names consistent.

**Comment by rat-moonshine** [comment] 2021-01-13 06:20
It is better to continue preventing the bundled items from edit/remove rather than complicating stuff by managing the names separately. I'm preventing the way. 

@joshtynjala how can we access any static/const variable through an extern class? As an example SDKUtils has static variable which I want to access through https://github.com/prominic/Moonshine-IDE/blob/master/ide/MoonshineGUICore/externs/actionScripts/utils/SDKUtils.hx.

**Comment by piotrzarzycki21** [comment] 2021-01-13 06:21
Are you saying that Editing some of the SDK won’t be possible?

**Comment by rat-moonshine** [comment] 2021-01-13 06:25
This particularly applicable on macOS build where you can see the "BUNDLED" status next to a few SDKs which parsed by Moonshine itself. Those shall remain un-editable.

**Comment by piotrzarzycki21** [comment] 2021-01-13 07:01
> This particularly applicable on macOS build where you can see the "BUNDLED" status next to a few SDKs which parsed by Moonshine itself. Those shall remain un-editable, for now.

To me it doesn't make sense to have such restriction, but I won't oppose to much, cause client who raises above issue is using Windows.

**Comment by rat-moonshine** [comment] 2021-01-13 08:48
We can visit this later for some adjustment. For now, I don't want to spend much time on this anymore. Let's close this if the basic requirement met.

**Comment by piotrzarzycki21** [comment] 2021-01-13 09:01
Yes let's close it.

**Comment by joshtynjala** [comment] 2021-01-13 17:01
@rat-moonshine Feel free to add anything that's missing to the externs. Check out the ConstantsCoreVO.hx extern for an example of a static constant.

**Comment by rat-moonshine** [comment] 2021-01-13 17:27
> @rat-moonshine Feel free to add anything that's missing to the externs. Check out the ConstantsCoreVO.hx extern for an example of a static constant.

Ah! I did try as `public static final MOONSHINE_IDE_LABEL:String` but didn't compile probably because I declared a value too (?) I shall give this a re-try again. Thank you!

**Comment by joshtynjala** [comment] 2021-01-13 17:48
Yeah, it's likely that Haxe externs aren't supposed to include values of variables or constants.

**Comment by piotrzarzycki21** [comment] 2021-01-18 12:40
@rat-moonshine did you finish that ? Can we close it ?

**Comment by rat-moonshine** [comment] 2021-01-18 13:01
Ah! Yes. Let's close it unless we found any problem.

**Closed by rat-moonshine** 2021-01-18 13:01 UTC
Labels: bug, enhancement, test-ready
