### ISSUE TITLE
Throws error on closing resulted tab from "Find Symbol in Workspace"

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#727] opened 2020-09-15 11:21 UTC
- Open window from `View -> Find Symbol in Workspace`
- Search for any symbol
- Double-click on any filtered list item shall open the reference as a new tab
- Try to close the tab by clicking on its close icon 
- Moonshine throws following errors

```
: Error #1009
: TypeError: Error #1009
: 	at actionScripts.utils::SharedObjectUtil$/removeLocationOfEditorFile()
: 	at actionScripts.ui.editor::BasicTextEditor/closeTabHandler()
: 	at actionScripts.ui.editor::LanguageServerTextEditor/closeTabHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.ui::MainView/handleTabClose()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at actionScripts.ui.tabview::TabView/onTabClose()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at mx.core::UIComponent/dispatchEvent()
: 	at actionScripts.ui.tabview::TabViewTab/closeThisTab()
: 	at actionScripts.ui.tabview::TabViewTab/closeButtonClicked()
:
: Click here to Report a Bug
```

**Comment by rat-moonshine** [comment] 2020-09-17 11:51
This should be fixed now.

**Comment by piotrzarzycki21** [comment] 2020-09-17 15:45
@rat-moonshine If have pushed fix to master - it didn't build. @JoelProminic  could you take a look into bamboo

**Comment by JoelProminic** [comment] 2020-09-17 16:13
@piotrzarzycki21 Unfortunately, the Windows build will be broken until we get a new certificate.  @JustinProminic and I will work on this soon.

**Comment by JoelProminic** [comment] 2020-09-21 15:54
The bug no longer reproduced for me on macOS with the latest version.   I saw some issues with searching the symbol list, but it looks like this is covered by #724.

**Comment by piotrzarzycki21** [comment] 2020-10-05 12:19
Closing this one since it is not reproducible anymore.

**Closed by piotrzarzycki21** 2020-10-05 12:19 UTC
Labels: bug, test-ready

**Comment by JoelProminic** [comment] 2020-10-05 15:44
I don't see any errors for Find Symbol in the Windows build, either.
