### ISSUE TITLE
Language-server Java instance keep running after Application exit [Windows]

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#325] opened 2018-07-06 10:36 UTC
**Tested on platform:** Windows 7
**Re-producible:** Every time
**Steps to reproduce:**

This test needs two projects opened at a time

1. Make sure when Moonshine starts it opens with two projects auto-opened to the sidebar
2. Open Task Manager - you should see two Java instances running against two opened projects
3. Close every project one after another - that steps should also close both the running Java instances from the Task Manager
4. Re-open both the same projects once again one after another
5. You should see two Java instances running at this point 
6. Exit Moonshine in a fashioned manner
7. One Java instance removes while another keeps running in the Task Manager

**Comment by joshtynjala** [comment] 2018-07-16 17:48
I cannot reproduce this issue. I tested on Windows 10.

> 6. Exit Moonshine in a fashioned manner

I tried exiting in two different ways, and they both correctly closed the two Java processes in Task Manager.

1) Close the window with the X button in the corner.

2) File -> Quit

**Comment by rat-moonshine** [comment] 2018-07-17 08:41
I have recently did a fresh Windows 10 installation to my system. I can able to reproduce the issue every time, following is a recording to the same:

![ref_325_recording](https://user-images.githubusercontent.com/24370870/42806152-59682b60-89cb-11e8-8f76-1d5b7ddf1e62.gif)

**Comment by piotrzarzycki21** [comment] 2018-07-17 08:52
Could you also try menu File - Exit Moonshine?

**Comment by joshtynjala** [comment] 2018-07-17 15:09
I wonder if this is happening because the language server is still busy compiling the code when you close the window (as you can see from the high CPU usage when you quit). It queues up the shutdown request until the main thread is free, but Moonshine might be exiting before the whole process is complete. Exiting the language server is a two-step process. Moonshine sends a "shutdown" request, waits for a response from the language server, and then it sends a final "exit" notification. The language server process won't end until it receives the "exit" notification.

Perhaps, on my computer, the messages are getting sent in time and the language server exits successfully. Maybe on your computer, Moonshine exits before it sends that final "exit" notification to the language server.

Maybe this is another situation where it's important to listen for when all LanguageClient instances dispatch their Event.CLOSE event.

**Comment by joshtynjala** [comment] 2018-08-13 19:37
I've fixed this issue on my `java-language-server` branch. When things are more stable in that branch, we can merge it in.

**Comment by rat-moonshine** [comment] 2018-09-07 15:52
I'm updating this issue as a continuation of #336 language-server related problem (as the reported issue is similar to the issue reported here). 

For easy reference, the user in aforementioned issue reported non-working of language-server/code-completion on Windows. Upon investigation, Josh suspected (and confirmed) that the user didn't updated with newer version of language-server for some reason. 

More investigation on the possible cause, we've found running Java instances on Windows can prevent the language-server from updation:

> I confirm @joshtynjala assumption. I took out some simple steps by downloading both 1.13.0 and 1.14.0. Following are my test steps:
> 
> - Uninstalled any existing Moonshine 
> - Installed 1.13.0
> - Ran Moonshine - made sure no projects is open at the time and no language server instance running 
> - Updated to 1.14.0 using in-built updater/downloader
> - Moonshine started with 1.14.0 and I didn't found any problem with language-server
> 
> Next tests:
> 
> - Uninstalled existing Moonshine again
> - Installed 1.13.0
> - Opened two projects at a time - made sure two Java instance running in Task Manager
> - Through the updater prompt in Moonshine downloaded 1.14.0
> - After having it downloaded Moonshine auto-exit
> - Both the Java instance shown keep running in Task Manager - this is similar to the issue reported in #325 
> - Moonshine installed - Java instances keep running
> - Upon starting Moonshine 1.14.0 - language-server is not working anymore

**Comment by joshtynjala** [comment] 2018-09-17 17:09
The `java-language-server` branch has been merged into `master`. Moonshine should now wait for all language servers to exit before it finishes exiting.

Before testing, be sure to kill any processes that may have be started by previous instances of Moonshine that still had this bug! 😜

**Closed** 2018-09-25 18:56 UTC
Labels: bug

**Comment by rat-moonshine** [comment] 2018-09-26 05:56
I tried to test by the previous steps, after new language-server merge:

- Made sure there is no language server instance running in Task Manager
- Started Moonshine
- Opened multiple projects at a time, confirmed that code-completion works accordingly 
- Opened Task Manager, but this time I didn't found any Java instance running entry like we use to see with previous versions (maybe this is something new change with the newer language-server codes)

Since I didn't found any running entry against the language-servers manually (to Task Manager), I was not able to say whether all instances of servers closes during Moonshine exit or not. If we found any related issue again, we can re-visit this issue.
