### ISSUE TITLE
Duplicate File is being Created

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#418] opened 2018-11-14 04:00 UTC
Hi @piotrzarzycki21 

I found an issue while testing the DXL to Moonshine conversion task.

The issue is that after conversion when I open the project in Moonshine its created 2 xhtml files for each xml.

Refer to below screenshot:

I am sure that before conversion the export directory was clean and the duplicate file is created once I open the project in Moonshine.

Thanks
Atin

**Comment by piotrzarzycki21** [comment] 2018-11-14 11:57
@atinprominic can you send me through the email that project ? Separately files which you were copying.

**Comment by piotrzarzycki21** [comment] 2018-11-14 11:59
@atinprominic I see the email now, so I will look into the issue once I get time for that.

**Comment by rat-moonshine** [comment] 2018-11-23 05:05
This could be a related issue as described [here](https://github.com/prominic/Moonshine-IDE/issues/420#issuecomment-441023864). @atinprominic please, download the latest build from Bamboo and see if the recent fixes also fixed the problem those you have faced on entry duplication.

**Comment by atinprominic** [comment] 2018-11-23 06:33
@piotrzarzycki21 
@rat-moonshine 
I took the latest build and checked again as per your suggestion. 

The issue is still there.

**Comment by rat-moonshine** [comment] 2018-11-23 07:32
@atinprominic please email me the 'after conversion' project that demonstrates duplication of file after opening in Moonshine. I'm basically expecting the project that I can import into Moonshine and see the same thing that you reported.

**Comment by rat-moonshine** [comment] 2018-11-26 05:51
Since this issue being created before we fixed actual duplication issue as #420 , I don't want to mark this issue as 'invalid' or 'non-reproducible' - it's possible the part of the problem that @atinprominic reported were valid and may-not valid. However, with current build tests, we couldn't able to reproduce the problem that Atin reported. Thus, I'm closing this.

**Closed by rat-moonshine** 2018-11-26 05:51 UTC
Labels: PrimeFaces, bug
