### ISSUE TITLE
Start/Stop Preview server for Visual Editor Project creates confusion

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#484] opened 2019-03-19 06:26 UTC
1. First thing that confused me while using Visual Editor project is the option under `Project -> Stop Preview`. It took me some time to understand and then guess that the option might be for the time when a preview server already ran. From an user point of view having the option enable only cretes confusion, perhaps we disable the option until a preview server ran by Moonshine
![image](https://user-images.githubusercontent.com/24370870/54584525-97b20e80-4a3d-11e9-8ee3-f8359db49a6b.png)
2. Being not very fluent-user to Visual Editor process, I found difficulty to find the option to start preview server (however, at the end I found it's inside the context menu associated to the .xhtml file). Since this is an important and notable part of this project type, I expect the option to be available in more primary location like `Project` menu.
3. I again found myself in difficulty while filling following fields prior to a preview run. Why can't we auto-populate them with most basic options to have the preview server run without forcing the user to input manually? For the `Maven Settings File` perhaps Moonshine try to search most basic location in the project and auto-populate the path (we does such basic location search in case of `Project -> Build with Apache Ant` against a project)
![image](https://user-images.githubusercontent.com/24370870/54584937-bbc21f80-4a3e-11e9-8e0c-55ee7b065580.png)

**Comment by piotrzarzycki21** [comment] 2019-03-19 08:49
I will try to improve that one I finish #477 which is quite related to that, cause I'm changing menu Project.

**Comment by piotrzarzycki21** [comment] 2019-03-27 16:27
Button Preview on the right sight from Tab buttons in Visual Editor area.

**Comment by piotrzarzycki21** [comment] 2019-04-02 14:06
@JoelProminic This has been merged to master and it's ready for test. I noticed that there is problem at least in debug mode with stopping Payara server after my upgrade to newest version. I would like to see whether it is occurs from version on Bamboo. We can discuss tomorrow whether my solution for this issue is enough to close it.

**Comment by JoelProminic** [comment] 2019-04-02 15:34
The "Start Preview" button in the Visual Editor window did not work for me with the latest macOS Bamboo build.  I got this error:

    : Error #1034
    : TypeError: Error #1034
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at mx.core::UIComponent/dispatchEvent()
    : 	at actionScripts.plugins.help.view::VisualEditorView/onStartPreviewClick()
    : 	at actionScripts.plugins.help.view::VisualEditorView/___VisualEditorView_ButtonBarButton1_click()
    :
    : Click here to Report a Bug


Project > Start Preview worked properly, and then menu action updated to Stop Preview while it was running.  I noticed that the "Start Preview" button updated to "Starting Preview" as the server started, but it returned to "Start Preview" after the server was fully started.

If I started the preview server from the context menu in the Project sidebar, the Project menu updated properly, and the "Start Preview" button showed the same behavior.

**Comment by piotrzarzycki21** [comment] 2019-04-02 15:57
@JoelProminic I just pushed fix for that. It looks like I have missed one change during commit. Next bamboo build will have it. I should probably explain how I'm seeing this new button.
1. **Menu** -> **Start/Stop Preview** -> This is the only place where you can stop server preview and start it for main file of the project. Probably in the future if it is needed I may spend some time and give ability to that item run any selected file in side bar for preview, however now I would like to leave it as is, cause changing menu is always a pain.
2. Button **Start Preview** - Have two actions, but it doesn't have action of stopping preview server. Preview server is more of a global instance, so I would like to avoid scenario where you in ONE view have started preview and in another stopped it. - This leads you to the situation where you have to start it again and wait again a bit longer for it instead run preview immediately. 
**Action 1**: Start preview - it's starting for the first time preview and run in the browser selected tab
**Action 2**: Run preview - if preview server is being started we are running stuff in the browser instantly 

Maybe name of that button should be different, maybe it should be called Preview as it is now in context menu.

**Comment by piotrzarzycki21** [comment] 2019-04-03 11:58
I can confirm that Payara is not being closed once server is stopped on Windows. On Mac it is working fine. I will investigate what is happening.

**Comment by piotrzarzycki21** [comment] 2019-04-03 13:08
I cannot figure out what is happening. Server is getting [command for shutdown](https://github.com/prominic/Moonshine-IDE/blob/fe6b5c9f68cc214a3951e517dc41ffacdbbb238c/ide/MoonshineSharedCore/src/elements/projects/PayaraEmbeddedLauncher/src/main/java/net/prominic/PayaraEmbeddedLauncher.java#L49), but I still see java process running.

![payara_running](https://user-images.githubusercontent.com/24554795/55481201-215b0200-5622-11e9-978b-ccef185ba989.png)

Console output in Moonshine. I see at the end exception form Glassfish but it doesn't say to much to me. 

 ```
Preview server has been successfully started for project NewVisualEditorProject
: Apr 03, 2019 3:01:22 PM com.sun.web.security.realmadapter.JaspicRealm getAppContextID
: INFO: Context path from ServletContext:  differs from path from bundle: /
: Apr 03, 2019 3:02:10 PM fish.payara.nucleus.hazelcast.HazelcastCore unbindFromJNDI
: INFO: Hazelcast Instance Unbound from JNDI at payara/Hazelcast
: Apr 03, 2019 3:02:10 PM fish.payara.nucleus.hazelcast.HazelcastCore unbindFromJNDI
: INFO: JSR107 Caching Provider Unbound from JNDI at payara/CachingProvider
: Apr 03, 2019 3:02:10 PM fish.payara.nucleus.hazelcast.HazelcastCore unbindFromJNDI
: INFO: JSR107 Cache Manager Unbound from JNDI at payara/CacheManager
: Apr 03, 2019 3:02:10 PM com.hazelcast.core.LifecycleService
: INFO: [192.168.1.3]:4900 [development] [3.11.1] [192.168.1.3]:4900 is SHUTTING_DOWN
: Apr 03, 2019 3:02:10 PM com.hazelcast.internal.partition.impl.MigrationManager
: INFO: [192.168.1.3]:4900 [development] [3.11.1] Shutdown request of [192.168.1.3]:4900 is handled
: Apr 03, 2019 3:02:10 PM com.hazelcast.instance.Node
: INFO: [192.168.1.3]:4900 [development] [3.11.1] Shutting down connection manager...
: Apr 03, 2019 3:02:10 PM com.hazelcast.instance.Node
: INFO: [192.168.1.3]:4900 [development] [3.11.1] Shutting down node engine...
: Apr 03, 2019 3:02:10 PM com.hazelcast.instance.NodeExtension
: INFO: [192.168.1.3]:4900 [development] [3.11.1] Destroying node NodeExtension.
: Apr 03, 2019 3:02:10 PM com.hazelcast.instance.Node
: INFO: [192.168.1.3]:4900 [development] [3.11.1] Hazelcast Shutdown is completed in 37 ms.
: Apr 03, 2019 3:02:10 PM com.hazelcast.core.LifecycleService
: INFO: [192.168.1.3]:4900 [development] [3.11.1] [192.168.1.3]:4900 is SHUTDOWN
: Apr 03, 2019 3:02:10 PM fish.payara.nucleus.hazelcast.HazelcastCore shutdownHazelcast
: INFO: Shutdown Hazelcast
: Apr 03, 2019 3:02:10 PM com.sun.enterprise.v3.server.AppServerStartup stop
: INFO: Shutdown procedure finished
: JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]
: Preview server for project NewVisualEditorProject has been shutdown.
```

**Comment by piotrzarzycki21** [comment] 2019-04-04 10:57
I was able to fix that issue by adding System.exit(0) and I did change how Glassfish server is closing. If you found the time take a look into that.

**Comment by piotrzarzycki21** [comment] 2019-04-05 14:22
Reopen if I have to do something differently.

**Comment by JoelProminic** [comment] 2019-04-17 22:58
I was able to get the preview server in a state where Moonshine could not close it like this:
1. Restart Moonshine
2. Open a PrimeFaces Project
3. Open a xhtml file in the visual editor
4. Click the Preview button - the server starts, and the page opens
5. Click the Preview button again - the page opens
6. BUG:  The Project > Stop Preview action is not available in the menu.  The Start Preview menu action is visible instead.
7. The server remains running.

**Comment by piotrzarzycki21** [comment] 2019-04-18 09:21
> I was able to get the preview server in a state where Moonshine could not close it like this:
> 
> 1. Restart Moonshine
> 2. Open a PrimeFaces Project
> 3. Open a xhtml file in the visual editor
> 4. Click the Preview button - the server starts, and the page opens
> 5. Click the Preview button again - the page opens
> 6. BUG:  The Project > Stop Preview action is not available in the menu.  The Start Preview menu action is visible instead.
> 7. The server remains running.

I was able fix that issue. Review today and close if it's working.

**Comment by JoelProminic** [comment] 2019-04-18 16:30
This seems to be working properly now.  I tried some variations on my test procedure, but I wasn't able to trigger the problem. again.

**Closed by JoelProminic** 2019-04-18 16:30 UTC
Labels: enhancement
