### ISSUE TITLE
Open/Import zip archive which contains Moonshine project

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#424] opened 2018-11-29 08:51 UTC
Idea of this feature is to have an ability in Moonshine where user can point zip archive which contains valid project and open it in IDE.

**Scenario and requirements:**
1. User downloads zip archive which contains Moonshine project (Doesn't matter what type of the project it is)

2. User using one of the following options:
- Home Tab: **Open Apache Flex/Royale project...**
- Menu **Project** -> **Open/Import Flex project...** (IMO maybe both options should be changed to more generic name -> ** Open project...**

Can point zip archive which contains project.
**If it's possible we should validate whether archive contains valid project without unzipping it to avoid unnecessary overhead.** 

3. If zip archive contains valid project we should ask user:
"Do you want to unzip project in the same location as archive?" - Prompt can be adjusted by @JoelProminic 

No - We should ask for the location standard window for open folder
Yes - Operation of unzip should be perform. We should see some busy indicator (It would be great to create some generic busy indicator which can be used in other place in Moonshine - I need it to notify user when I'm opening Visual Editor file - Raise separate issue for that if needed)
Cancel - For stop whole operation

Unzipping should be separated operation. - I should be able to use that one in whatever place of our application I wanted to. It shouldn't be baked into process of opening. It should be started there and eventually you should get results and notify open operation what is happening.

**Comment by piotrzarzycki21** [comment] 2018-11-30 14:02
> Currently the open/import project opens the file browser in directory selection mode, so user can select the project directory, and therefore Moonshine starts its task to determine if this a valid project directory. We can change this behavior to select anything, like files or folders. But I don't likes to change the behavior what it is now. This is an often used functionality, and I think most of the people are habituate by the type of behavior (to select/open a project), I don't likes creates any confusion either between selecting what kind of file during a project open. Thus, in my agreement I don't want to change the current functionality or behavior.
> 
> Being said that, I don't likes to put a prompt before the user, before opening the project either - prompt like whether they wants to select a project folder, or an archive. This could be lot much irritating in time.
> 
> My vote is to introduce separate option to open archive - if we want to have the archive specific to Visual Editor project, or for any project.

I agree on above - it's completely eliminates need of prompt user if we have separate option.

> On the above note, if we want to provide option to open archive for any project, although I don't see any practical need for that at this moment - we can therefore re-use the project verification process that we have for every project - to determine if it's a valid project archive.

We don't need this, but why not to do this - If you see problem and can take you let's say 5 days more - OK I agree to have this for future when we have more times, but if it's not the case let's do this for all of our projects. The other sight is - If you let's say do that for VisualEditor project only - you will have to have in menu some weird name which distinguish option from other project. - Let's avoid that.

> In initial tests I didn't found that File API can detect any file inside an archive file. I shall need to check if the archive API we are using provides some way to do that.

That's not good. Please investigate more, cause I would really like to avoid unzipping archive if it's not needed. 

> On Piotr's, "Unzipping should be separated operation. - I should be able to use that one in whatever place of our application I wanted to. It shouldn't be baked into process of opening." - the archive API is a separate API anyway - which returns necessary notification upon its every steps; Were your thoughts to separate operation more broad than this basic, or something more?

If we have those things separated already - That's cool - I just didn't know.

Btw. My suggestion is to also start working on branch feature/....

**Comment by JoelProminic** [comment] 2018-12-07 00:09
The import form looks like this:
![image](https://user-images.githubusercontent.com/24532731/49619319-b5250600-f981-11e8-8b95-1c90fc262fee.png)

A couple tweaks to the text:
- "Archive File to Project" should just be "Archive File"
- "Directory to Save" should be "Target Directory".  I'm not 100% happy with this choice, but I think it will make more sense.

I confirmed that the project name and .veditorproj file are updated to match the "Project name" selected in this prompt.   I think this makes more sense than keeping the original project name.

**Comment by piotrzarzycki21** [comment] 2018-12-11 11:13
@rat-moonshine I have discovered issue where I'm getting following stack trace: 

```
[Fault] exception, information=Error: Error #2037: Functions called in incorrect sequence, or earlier call was unsuccessful.
at Error$/throwError()
at flash.filesystem::File/resolveComponents()
at flash.filesystem::File/resolvePath()
at actionScripts.plugins.as3project::ImportArchiveProject/onProjectPathChanged()[D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineDESKTOPevolved\src\actionScripts\plugins\as3project\ImportArchiveProject.as:300]
at flash.events::EventDispatcher/dispatchEventFunction()
at flash.events::EventDispatcher/dispatchEvent()
at actionScripts.plugin.settings.renderers::PathRenderer/onCreationCompletes()[D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\renderers\PathRenderer.mxml:238]
at actionScripts.plugin.settings.renderers::PathRenderer/___PathRenderer_VGroup1_creationComplete()[D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\renderers\PathRenderer.mxml:32]
at flash.events::EventDispatcher/dispatchEventFunction()
at flash.events::EventDispatcher/dispatchEvent()
at mx.core::UIComponent/dispatchEvent()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\core\UIComponent.as:13688]
at mx.core::UIComponent/set initialized()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\core\UIComponent.as:1839]
at mx.managers::LayoutManager/validateClient()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\managers\LayoutManager.as:1099]
at mx.core::UIComponent/validateNow()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\core\UIComponent.as:8609]
at actionScripts.plugin.settings::SettingsView/buildSettings()[D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:409]
at actionScripts.plugin.settings::SettingsView/onSettingsViewCreationComplete()[D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:347]
at actionScripts.plugin.settings::SettingsView/___SettingsView_BorderContainer1_creationComplete()[D:\Work\projects\Prominic.NET\Moonshine-IDE\ide\MoonshineSharedCore\src\actionScripts\plugin\settings\SettingsView.mxml:26]
at flash.events::EventDispatcher/dispatchEventFunction()
at flash.events::EventDispatcher/dispatchEvent()
at mx.core::UIComponent/dispatchEvent()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\core\UIComponent.as:13688]
at mx.core::UIComponent/set initialized()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\core\UIComponent.as:1839]
at mx.managers::LayoutManager/doPhasedInstantiation()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\managers\LayoutManager.as:848]
at mx.managers::LayoutManager/doPhasedInstantiationCallback()[D:\flex_sdk\Sources\flex-sdk\frameworks\projects\framework\src\mx\managers\LayoutManager.as:1191]
```

**Scenario:**
1. User is installing Moonshine for the first time in the system. In order to reproduce that issue first got to **File** -> **Settings** -> **General** -> **Reset all Settings**
2. Switch OFF Moonshine and remove settings folder `c:\Users\{user}\AppData\Roaming\com.moonshine-ide.development` or `idToBeReplacedByANT`
3. Start Moonshine and go to **Project** -> **Import Project Archive** <- Above exception occurs.

**Comment by rat-moonshine** [comment] 2018-12-11 11:53
Ah, that's a good observation. Thank you! I'm looking into this.

**Comment by rat-moonshine** [comment] 2018-12-11 12:32
The above problem should be fix now. However, one incident I noticed that when there is no default SDK set to Moonshine (i.e. when reset all settings happened), option to import archive file turn disable. At this moment, I didn't found the reason behind this disabling, I need to look more.

**Comment by piotrzarzycki21** [comment] 2018-12-12 11:17
I have tested this one and reported issue is fixed. However I see couple of observations.
1. pom.xml file have in `<artifactId>$ProjectName</artifactId>` and `<name>$ProjectName</name>` - I believe we could do something with that. Maybe inject project name in that places ? 
2. Current IDE file for project is outdated - we need to provide to Andrii new one. It's enough if we create new Visual Editor project and give him file - of course removing previously all the paths from it.
3. There is no main application file after conversion. It means that when we start Preview by clicking on root folder it will try to open following address `http://localhost:8180/NsfConverter.xhtml` - which won't exists. I'm not sure what to do with that yet. 
Of course clicking on any specific file and choosing **Preview** will work.

**Comment by rat-moonshine** [comment] 2018-12-12 12:18
> pom.xml file have in <artifactId>$ProjectName</artifactId> and <name>$ProjectName</name> - I believe we could do something with that. Maybe inject project name in that places ?

We actually already doing this. Based on existing project validation policy, we detect project's configuration file instead, so it's easy to read into and get the project name from there. If you do not provide any custom name by yourself, and select the archive file through file browser, you can see that auto-project name applied to the project name field. However, if custom name entered by the user, the process do not overrides the entered name then. 

> Current IDE file for project is outdated - we need to provide to Andrii new one. It's enough if we create new Visual Editor project and give him file - of course removing previously all the paths from it.

Can you tell me something more what you pointed by IDE file?

**Comment by piotrzarzycki21** [comment] 2018-12-12 13:32
> We actually already doing this. Based on existing project validation policy, we detect project's configuration file instead, so it's easy to read into and get the project name from there. If you do not provide any custom name by yourself, and select the archive file through file browser, you can see that auto-project name applied to the project name field. However, if custom name entered by the user, the process do not overrides the entered name then. Custom naming given preference in the process.

If you are doing that for the main pom.xml file - it doesn't work right now. Try to open project which is provided by converter on the website. 

> Can you tell me something more what you pointed by IDE file?

I'm talking about IDE file with extension *.as3proj

**Comment by rat-moonshine** [comment] 2018-12-12 15:05
> If you are doing that for the main pom.xml file - it doesn't work right now. Try to open project which is provided by converter on the website.

By existing logic to validate a project folder - archive also looks for the project configuration file (i.e. .as3proj or .veditorproj). It do not reads pom.xml file. If this do not works for you, then we might need to re-check this.

**Comment by piotrzarzycki21** [comment] 2018-12-12 15:09
> By existing logic to validate a project folder - archive also looks for the project configuration file (i.e. .as3proj or .veditorproj) - to keep everything in standard procedure, which applies for any other project types, as well. It do not reads pom.xml file. If this do not works for you, then we might need to re-check this.

I understand that it looks for the project configuration file, but probably should also look for pom.xml if exists and replace those special tokens. 

The newest configuration file should be also provided to Andrii for update his template which he is using to create project by converter.

**Comment by rat-moonshine** [comment] 2018-12-12 16:57
I understood what you meant by that @piotrzarzycki21 . Looking into the converted project as downloaded from the converter website once, it looks like there is only one file which requires to update the token for project name:

![image](https://user-images.githubusercontent.com/24370870/49885369-0f7c0600-fe5d-11e8-8132-b52fc8f6c6c5.png)

This shall be updated while a custom name entered through the import archive project dialog. I shall re-download an archive to ensure, if any new files/token been added elsewhere.

**Comment by piotrzarzycki21** [comment] 2019-01-31 12:39
@rat-moonshine any more work here to do ?

**Comment by rat-moonshine** [comment] 2019-01-31 15:21
I guess no. I probably need to close this and likewise few others too, soon.

**Closed** 2019-02-01 05:59 UTC
Labels: enhancement
