### ISSUE TITLE
Presenting founded lines of code in the results of global search

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#184] opened 2018-02-13 09:23 UTC
It would be great to have lines of code displayed in the results of global search instead number of lines only. It has been extracted from issue #169.

![image](https://user-images.githubusercontent.com/24554795/36142280-e27e24d8-10a7-11e8-9030-b7755a78ae09.png)

**Comment by rat-moonshine** [comment] 2018-02-15 09:10
![image](https://user-images.githubusercontent.com/24370870/36248635-33a22172-125e-11e8-8c5a-c5802d4f6ac8.png)

**Comment by rat-moonshine** [comment] 2018-02-19 11:59
Updates:
- [BUG] While option selected for search through additional class paths projects/directories (_Include external source paths_), search was failing if any invalid path mentioned in the project's _Class Paths_ section; Search was silently failing and search progress bar not removed - Fixed
- @JoelProminic had shown some UI disorientation while expanding/collapsing folder/file entries the other day - I noticed that was causing by some other reason but double-clicking, now fixed
- Double-clicking on line information entries now opens the corresponding file and scroll the cursor to the targeted line
- New class/file icon now added against the file rows

Other notes:
- Line information entries still need some work, i.e. highlight colour, tab spaces needs to get remove from showing code-line
- Horizontal scroll needs to shown up when showing large line information row
- Codes are still very dirty needs cleanup

**Comment by rat-moonshine** [comment] 2018-02-19 16:41
@JoelProminic suggested a few things to recent updates:
- Scroll to the line (after double-clicking a line information row) would have been best if the targeted line always scrolled to the vertically middle of the editor. At present targeted line either shows at top of the editor or somewhere at bottom
- At this moment the cursor is only blinks at the beginning of the targeted line, which is not prominent. Two improvements suggested (based on their priority) - a) temporary line highlighting against the targeted line, b) move the cursor before the highlighted searched text

**Comment by JoelProminic** [comment] 2018-02-19 20:56
I tested the behavior with missing and existing class path entries, and they both worked as expected.

I was not able to reproduce the tree issues I reported on Friday.

Double clicking the files opens the file and puts the cursor at the top of the file.  Double-clicking the line entries will put the cursor on that line and shift the scrollable area so that it is visible.  The basic functionality for this seems fine.

Some additional thoughts with the line opening logic:
![image](https://user-images.githubusercontent.com/24532731/36396703-10711e86-1585-11e8-8bee-2ad2bbca83a7.png)
1. If line would not be visible with the default/current scroll position, the scroll is shifted so that the result is at the top of the page (if the file was already open in an editor) or the bottom of the page (if the file was not open in the editor).   I would prefer to have this in the middle so that there was some context before and after the line of code.
2. The highlighting is the same for the current match and the other matches, so only the cursor indicates which one the user actually selected.   The selected match could be set to different color, or the line could be highlighted
3. The cursor is placed at the begining of the line rather than on the match.  This only really matters when there are multiple matches on a line, or if the user wanted to immediately start editing at the matched location.

**Comment by JoelProminic** [comment] 2018-02-20 16:39
I see that there is whitespace added between the line number and the line text to allow for space for more digits.  I did a quick test to confirm how the interface would handle a large number of digits:
![image](https://user-images.githubusercontent.com/24532731/36436487-fe8f0f20-1629-11e8-9213-ca1fc2298033.png)

The interface supports up to 5 digits.  There is overlap with the 6th digit. 

The only files I would expect to have more than 10,000 lines in normal circumstances are log files, so it may be overkill to support more.

However, I found that I could not open search results for line numbers at 9999 or greater (I did not check the exact number).  I don't see an error in the interface, but the editor never opens.

Here is my test file.   Search for "Hello":
[2018_02_20__TestManyLines.zip](https://github.com/prominic/Moonshine-IDE/files/1740940/2018_02_20__TestManyLines.zip)

**Comment by rat-moonshine** [comment] 2018-02-21 08:44
Updates:
- MouseWheel problem now resolved to the editor
- Double-clicking line-information row select/highlights the searched word in editor

**Comment by rat-moonshine** [comment] 2018-02-21 09:25
> However, I found that I could not open search results for line numbers at 9999 or greater (I did not check the exact number). I don't see an error in the interface, but the editor never opens.

I think there are some restrictions to the current text editor which already discussed somewhere. @piotrzarzycki21 you have any memory on this (restriction)?

**Comment by piotrzarzycki21** [comment] 2018-02-21 09:31
I don't remember any restriction. Maybe in that case we have some silent fail, which is not reported in the release version. You will have to open similar file having Moonshine run in debugging mode.

**Comment by rat-moonshine** [comment] 2018-02-21 09:39
Okay, thank you for confirming that @piotrzarzycki21 .

@JoelProminic , when I tested in debug mode, I noticed the given text file does opened/rendered to the editor, however since its large number of lines to render, this took a few seconds to completely rendered to the editor. In my tests generally it took 4 seconds. 

![screenshot](https://user-images.githubusercontent.com/24370870/36472897-1991228c-1719-11e8-9ac4-3f5e8c5756ce.png)

However, once everything loaded, the search selection goes well (as shown above).

**Comment by rat-moonshine** [comment] 2018-02-21 11:40
I think I've added the same _styleName_ (`verticalScrollBarStyleName="black"`) to the tree component used in this section as was in TreeView component, but the scrollbar is coming white - @piotrzarzycki21 do you have any suggestion on this?

**Comment by piotrzarzycki21** [comment] 2018-02-21 11:46
Try to set this style using AS code in creationComplete event setStyle("verticalScrollBarStyleName", "black"); - Let me know if it helped.

**Comment by rat-moonshine** [comment] 2018-02-21 11:58
I added the style to the tree component's `creationComplete` event, but that didn't worked either, unfortunately.

**Comment by piotrzarzycki21** [comment] 2018-02-21 14:58
@rat-moonshine I just pushed fix for your issue. It looks like for some reason "black" style wasn't visible in that view. I just declared inside that view style and it's working.

**Comment by JoelProminic** [comment] 2018-02-21 20:38
I noticed some cases when the line opening logic did not work, but they did not reproduce consistently.  The problem generally triggered in a situation like this:
# Run a search that will produce multiple matches in a file (I was using TestManyLines.txt)
# Double-click that file.  The editor opens
# Close the editor
# Double-click the line entries.  BUG:  the editor does not open, bug there are no errors displayed in popups or on the console

**Comment by JoelProminic** [comment] 2018-02-21 20:43
With the updated highlighting logic, the search screen will be selected on the target line in the editor when you double-click the search result for a line.  

This will allow you to immediately replace the string by typing in the editor.  However, if you didn't want to replace the string, you need to use the mouse or error keys to cancel the selection.

If this behavior is inconvenient for normal use, we may want change this to use highlighting only, rather than selection.

**Comment by rat-moonshine** [comment] 2018-02-28 04:51
I'm closing this for next release. Please reopen, if bug found.

**Closed by rat-moonshine** 2018-02-28 04:51 UTC
Labels: enhancement
