### ISSUE TITLE
Project with mvn layout cant be loaded anymore

### ISSUE THREAD

**Issue by joerg-rade** [prominic/Moonshine-IDE#358] opened 2018-08-24 15:47 UTC
## Environment
Windows 7, Moonshine 1.14.0

## Description
I use a maven FS layout (/src/main/flex/..) and have changed paths in xml files (roViz.as3proj, build.xml, roVizConfig.xml). 
Compiling indicated diverging package names.

## Steps to Reproduce
https://github.com/joerg-rade/roViz/tree/royale

## Expected Behavior
Accept mvn layout, load project

## Actual Behavior/Errors
Project is still listed under Home->RECENT but can not be loaded anymore.

### Errors
Error #1085
TypeError: Error #1085
	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
	at actionScripts.impls::IFlexCoreBridgeImp/parseFlashDevelop()
	at actionScripts.plugin.project::ProjectPlugin/openPreviouslyOpenedProject()
	at actionScripts.plugin.project::ProjectPlugin/handleShowPreviouslyOpenedProjects()
	at flash.events::EventDispatcher/dispatchEvent()
	at MethodInfo-14590()
	at SetIntervalTimer/onTimer()
	at flash.utils::Timer/tick()

Error #1085
TypeError: Error #1085
	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
	at actionScripts.impls::IFlexCoreBridgeImp/parseFlashDevelop()
	at components.views.splashscreen::SplashScreen/getProjectBasedOnFileOption()
	at components.views.splashscreen::SplashScreen/openRecentItem()
	at components.views.splashscreen::SplashScreen/handleRecentClick()
	at flash.events::EventDispatcher/dispatchEvent()
	at mx.core::UIComponent/dispatchEvent()
	at components.renderers::RecentProjectRenderer/handleClick()

**Comment by piotrzarzycki21** [comment] 2018-08-24 16:49
@rat-moonshine please take a look into that. I just did a quick look and couldn't even setup that project in Moonshine 1.14.0 with existing sources, but in our development build I was able to. 
If we don't have an issue with 1.15.0 Dev, let's think about release very soon.

**Comment by piotrzarzycki21** [comment] 2018-08-27 07:58
Here is my steps in 1.14.0
1) I checkout the project on branch "royale", because that one is pointed in the link.
2) I pointed project using **Open Apache Flex/Royale Project...** and got standard popup which is saying that project doesn't have Moonshine project files.
3) I tried to Browse source files in order to point main application file, but 1.14.0 do not show file list.
![no_sources](https://user-images.githubusercontent.com/24554795/44647715-25190d00-a9df-11e8-91c2-a2e6863c503c.png)

In 1.15.0 I don't have such problems.
![sources_ok](https://user-images.githubusercontent.com/24554795/44647750-3cf09100-a9df-11e8-8412-c952ed54de6d.png)

I think we should release new version. We have enough updates there. 

As part of that issue I would change one thing. When you use **Open Apache Flex/Royale Project...** to open new project without Moonshine files - suggested project name is "External Project" - Maybe it will have sense to suggest project name as root folder name ? 
![project_name](https://user-images.githubusercontent.com/24554795/44647845-91940c00-a9df-11e8-81c7-822aa854d7d7.png)

**Comment by rat-moonshine** [comment] 2018-08-27 08:33
I see we have the said problem listed at [here](https://github.com/prominic/Moonshine-IDE/issues/342), and targeted to 1.15.0 release.

> Maybe it will have sense to suggest project name as root folder name ?

That is a good suggestion, though.

**Comment by rat-moonshine** [comment] 2018-08-30 07:47
@atinprominic , can you please test tor produce issue reported by @joerg-rade with latest dev build from Bamboo (?)

@piotrzarzycki21 , can you able to reproduce the problem reported here with latest build of Moonshine? If both you and Atin not able to reproduce it, then we perhaps need to close the issue as  non reproducible.

**Comment by piotrzarzycki21** [comment] 2018-08-30 08:27
I wasn't able to reproduce that.

**Comment by atinprominic** [comment] 2018-09-03 06:00
@rat-moonshine and @piotrzarzycki21 I tested following the steps as suggested -https://github.com/prominic/Moonshine-IDE/issues/358#issuecomment-416138578

I have found no any issue as reported.

However I was not able to use the Git Clone feature inside Moonshine. I am reporting a new issue for this.

**Comment by rat-moonshine** [comment] 2018-09-03 06:31
Thank you for confirming with your test results @atinprominic .

@joerg-rade , if the reported problem still persists for you, I'd suggest you to provide with detailed steps to reproduce. At this moment, we couldn't able to reproduce the scenario reported here.

**Comment by joerg-rade** [comment] 2018-09-03 07:02
OK – I’ll check again against 1.15



Kühne + Nagel (AG & Co.) KG
Rechtsform: Kommanditgesellschaft, Bremen HRA 21928, USt-IdNr.: DE 812773878.
Geschäftsleitung Kühne + Nagel (AG & Co.) KG: Dr. Hansjörg Rodi (Vors. ), Tom Ban, Martin Brinkmann, Holger Ketz, Jan-Hendrik Köstergarten, Nicholas Minde, Lars Wedel, Matthias Weiner.
Persönlich haftende Gesellschafterin: Kühne & Nagel A.G., Rechtsform: Aktiengesellschaft nach luxemburgischem Recht, HR-Nr.: B 18745, Geschäftsführendes Verwaltungsratsmitglied: Karl Gernandt.
Geschäftsleitung Region Zentral- und Osteuropa: Dr. Hansjörg Rodi (Vors.), Tom Ban, Dominic Edmonds, Thierry Held, Uwe Hött, Richard Huhn, Holger Ketz, Jan-Hendrik Köstergarten, Jan Kunze.

Wir arbeiten ausschließlich auf Grundlage der Allgemeinen Deutschen Spediteurbedingungen 2017 (ADSp 2017). Hinweis: Die ADSp 2017 weichen in Ziffer 23 hinsichtlich des Haftungshöchstbetrages für Güterschäden (§ 431 HGB) vom Gesetz ab, indem sie die Haftung bei multimodalen Transporten unter Einschluss einer Seebeförderung und bei unbekanntem Schadenort auf 2 SZR/kg und im Übrigen die Regelhaftung von 8,33 SZR/kg zusätzlich auf 1,25 Millionen Euro je Schadenfall sowie 2,5 Millionen Euro je Schadenereignis, mindestens aber 2 SZR/kg, beschränken. Die ADSp sind auf unserer Webseite als Download erhältlich. Auf Anfrage senden wir Ihnen diese auch gerne zu.

**Comment by piotrzarzycki21** [comment] 2018-09-03 09:07
@rat-moonshine let's resolve that one and see whether @joerg-rade have problems in upcoming 1.15.0 release.

**Comment by rat-moonshine** [comment] 2018-09-04 05:41
I'm closing this issue as non-producible. Feel free to re-open this if producible with specific steps.

**Closed by rat-moonshine** 2018-09-04 05:41 UTC
Labels: bug

**Comment by JoelProminic** [comment] 2020-02-11 16:05
Another user reported an error with a similar stack trace, but a different error code.

    : Error #1090
    : TypeError: Error #1090
    : 	at actionScripts.plugins.as3project.importer::FlashDevelopImporter$/parse()
    : 	at actionScripts.impls::IFlexCoreBridgeImp/parseFlashDevelop()
    : 	at actionScripts.plugin.project::ProjectPlugin/openPreviouslyOpenedProject()
    : 	at actionScripts.plugin.project::ProjectPlugin/handleShowPreviouslyOpenedProjects()
    : 	at flash.events::EventDispatcher/dispatchEvent()
    : 	at MethodInfo-17196()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug
    : Java language server exited unexpectedly. Close the example project and re-open it to enable code intelligence. 


On further investigation, he found that there were unresolved Git conflicts in the -app.xml file.

![image](https://user-images.githubusercontent.com/24532731/74254361-f4519400-4cb5-11ea-9aeb-4290a4f40223.png)

I doubt this is the same problem that was originally reported, but I'm reporting it in case someone else has the same problem.

**Comment by piotrzarzycki21** [comment] 2020-02-11 16:14
> On further investigation, he found that there were unresolved Git conflicts in the -app.xml file.

I'm not sure actually what file do you have in mind ?

**Comment by JoelProminic** [comment] 2020-02-11 17:24
I mean the application descriptor, src/<project>-app.xml.

**Comment by piotrzarzycki21** [comment] 2020-02-11 18:23
Ok you are talking about file attached with the project, so template is broken - However I'm not sure - I will look tomorrow.
