### ISSUE TITLE
Error # 3001 while collapsing / expanding the src folder in project side bar

### ISSUE THREAD

**Issue by atinprominic** [prominic/Moonshine-IDE#343] opened 2018-08-08 08:13 UTC
OS: MAC

1. Open Moonshine and open any project.
2. In the project sidebar in the left, expand and collapse the src folder multiple times repeatedly.
3. Below error log is being thrown:

```
: /bin/bash: /Applications/Xcode.app/Contents/Developer/usr/bin/git: No such file or directory 
: Moonshine IDE 1.14.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 28.0.0.125
: Error #3001
: Error: Error #3001
: 	at actionScripts.impls::IFileBridgeImp/save()
: 	at actionScripts.plugin.actionscript.as3project.vo::MXMLCConfigVO/writeApplicationConfig()
: 	at actionScripts.plugin.actionscript.as3project.vo::MXMLCConfigVO/write()
: 	at actionScripts.plugin.actionscript.as3project.vo::AS3ProjectVO/updateConfig()
: 	at actionScripts.languageServer::ActionScriptLanguageServerForProject/sendProjectConfiguration()
: 	at actionScripts.languageServer::ActionScriptLanguageServerForProject/languageClient_initHandler()
: 	at flash.events::EventDispatcher/dispatchEvent()
: 	at actionScripts.languageServer::LanguageClient/sendInitialized()
: 	at actionScripts.languageServer::LanguageClient/parseMessage()
: 	at actionScripts.languageServer::LanguageClient/parseMessageBuffer()
: 	at actionScripts.languageServer::LanguageClient/input_onData()
:
: Click here to Report a Bug

```

**Comment by rat-moonshine** [comment] 2018-08-08 10:33
I couldn't able to reproduce this in my initial tests. 

Can you provide some more information like, against which project type you had this error, did you had SDK setup, or language-server setup, is this error thrown after Moonshine starts with project auto-opened, or during a project open etc.

**Comment by rat-moonshine** [comment] 2018-08-09 08:59
@atinprominic , please send following files from your system to investigate further:

1. The project that thrown you error 
2. `/Users/${username}/Library/Containers/com.moonshine-ide` (zipped)

**Comment by piotrzarzycki21** [comment] 2018-08-09 09:02
@atinprominic please attach those files here.

**Comment by atinprominic** [comment] 2018-08-13 05:06
[com.moonshine-ide.zip](https://github.com/prominic/Moonshine-IDE/files/2281798/com.moonshine-ide.zip)

**Comment by atinprominic** [comment] 2018-08-13 09:28
[PF090818.zip](https://github.com/prominic/Moonshine-IDE/files/2282440/PF090818.zip)

**Comment by piotrzarzycki21** [comment] 2019-04-09 10:46
I couldn't reproduce that issue as well. Let's close it.

**Closed by piotrzarzycki21** 2019-04-09 10:46 UTC
Labels: Investigation
