### ISSUE TITLE
Non-sandbox build wrongly showing as "App Store Version" in its About section

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#816] opened 2021-04-27 14:45 UTC
In case of a non-sandbox build run, the About section was supposed to omit the "App Store Version" label but in sandbox build.

**Comment by rat-moonshine** [comment] 2021-04-28 05:52
Surprisingly, I don't find anywhere any reference where a file is suppose to get updated based on which Moonshine determines if it's an App Store version; Unless, I'm forgetting something.

**Comment by rat-moonshine** [comment] 2021-04-28 11:11
I couldn't found any previous codes anymore related to this. I tried to determine the build-type based on its entitlements - but it seems macOS do not like to let the relevant command run from application environment. 

I have re-wrote something in the build-script file, this should re-enable now to properly detects between an App Store download build or a non-sandbox one.

**Comment by JoelProminic** [comment] 2021-04-28 16:38
I still don't see the source icon for Flex, Royale, or Haxe projects on macOS Catalina.   Since I'm the who has this problem, and it does not break functionality, this is a lower priority.

**Comment by JoelProminic** [comment] 2021-04-28 17:35
I confirmed this was fixed with build 1909 on macOS Catalina.

**Closed by JoelProminic** 2021-04-28 17:35 UTC
Labels: Mac, bug
