### ISSUE TITLE
FlexJS Invalid SDK error

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#16] opened 2017-09-19 03:04 UTC
When trying to Build as JavaScript or Build and Run as JavaScript, result is as below 

![ms sdk error](https://user-images.githubusercontent.com/32083838/30573968-79679962-9d29-11e7-91f9-fa14cd79c7a5.png)

The sdk is correctly selected however and mouse-over pop-ups and suggestion lists on typing all appear correctly. Project settings as below

![ms project settings](https://user-images.githubusercontent.com/32083838/30573995-b1461a52-9d29-11e7-9d17-baca920e9e80.png)

Tried deleting (including Users com.moonshine-ide file) and re-installing Moonshine, but result is the same.

Choosing other sdk 0.8.0 makes no difference. In fact all build options instantly generate the Alert.

**Comment by rat-moonshine** [comment] 2017-09-19 05:30
Looking into the last screenshot, it seems you have "Additional compiler options" sets as "+configname=air". Technically that suppose to be a compiler option for Adobe AIR project. I'm wondering if you have copied the options from some project else (?)

If its not a FlexJS MDL project, then you can remove almost all the compiler options! Try to remove unnecessary compiler options and give it a try.

**Comment by doug777** [comment] 2017-10-11 07:46
Actually the problem is that when you remove all the text from any item in Settings, it appears as if it is removed, but when you return to Settings or close and reopen the program, the settings are still there. If you replace the string with an empty space, you can permanently delete it - except for the space.

**Comment by rat-moonshine** [comment] 2017-10-11 10:23
> Actually the problem is that when you remove all the text from any item in Settings, it appears as if it is removed, but when you return to Settings or close and reopen the program, the settings are still there.

You mean if you removes them but not clicking the Save button?

**Comment by doug777** [comment] 2017-10-12 00:26
Obviously you have to click Save otherwise you couldn't change it to a space. If you enter a string into any of the places where you can do this in Settings, you can change it to anything else you want, but you cannot return it to null. After you click Save, it looks as though the entry has been completely deleted until you close and reopen the program. You can set these strings to anything but you can never return them to null.

Doug

**Comment by rat-moonshine** [comment] 2017-10-12 05:16
I confirm the issue. 

In some scenario, when there's no value against certain fields, Moonshine auto-generates default values to them to easy the process. But the issue @doug777 reported is also visible at some point that its not default value (Moonshine auto-generating) but re-populating exact same values even they've deleted in past. That needs to be investigated.

**Comment by rat-moonshine** [comment] 2017-10-12 06:26
Text items in Settings should properly saves now blank or no values.

Note: There are certain text properties in Settings may auto-populates even user chose to save them blank (i.e. in case of AIR project additional compiler argument repopulates `+configname=air`, etc.), to easy in process.

**Comment by JoelProminic** [comment] 2017-10-12 23:21
@doug777, was this project converted from an AIR project?

@rat-moonshine and I had a discussion today about how Moonshine detects the project type.  The steps below worked for me on a simple test project.   

1. Delete the application descriptor file (i.e. src/<project>-app.xml)

2. Open <project>.as3proj

3. Find this line:
```
    <option additional="+configname=air"/>
```

Clear the value and save:
```
    <option additional=""/>
```

This will resolve the SDK error.  The Moonshine logic prevented this from being changed in the Moonshine settings.  @rat-moonshine will review this.

4. In <options>, change this line:
```
    <option testMovie="AIR"/>
```

To:
```
    <option testMovie=""/>
```

This will allow the application to launch from Build & Run as Javascript

5. Also change these lines in <moonshineRunCustomization>:
```
    <option projectType="1"/>
    <option targetPlatform="1"/>
```

To:
```
    <option projectType="2"/>
    <option targetPlatform="2"/>
```


6. Save <project>.as3proj

7. Close the project in Moonshine

8. Reopen the project.

At this point, Project > Build & Run As Javascript should work properly.

**Comment by doug777** [comment] 2017-10-13 00:58
It was originally <s:Application ... /> to run in a browser under Flash. Once you don't have "Additional compiler options" set as "+configname=air", the problem disappears. It kept reappearing only because the compiler option was never really reset to null although it appeared to be, see my comment from 2 days ago.

Doug

**Comment by doug777** [comment] 2017-10-13 02:15
The settings in .as3proj all look correct now except that option testMovie="OpenDocument". Everything seems to be working correctly now so not sure whether I need to change this to "" or not or perhaps it makes no difference?

**Comment by doug777** [comment] 2017-10-18 02:19
Sadly the Invalid SDK error has returned even though Additional compiler options are empty string. I changed something in the Application tag and the fault reappeared. I reset it back to exactly as it was before but the fault remains. Tried changing sdk, downloading latest nightly build and changing to that, but nothing works.

If I create a new js project and copy the code from the old project into the new project, there is no error and the compile works correctly.

The only difference I can find between the old and new project is that in the new project's <option urlToLaunch=""/> is empty string whereas in the old project it has a value that points correctly to the index.html file.

I then set this line to empty string in the old project, and now there is no error.

Doug

**Comment by doug777** [comment] 2017-10-18 02:29
However I am totally unable to stop the Invalid SDK error occurring in a project using the latest nightly build and flexjs changed to royale in the namespace definitions and imports. Can anyone help with this?

**Comment by doug777** [comment] 2017-10-18 03:50
Now changed royale back to flexjs and flex, but no change. Invalid sdk appears the instant I click Build as Javascript. So this old project has no mention of royale.

Created a new project and copied the entire code of the old project into the new project. It all works and compiles correctly.

So I'm now in the crazy situation where apart from the project name, I have two identical projects with identical as3proj files and identical Config.xml files. Yet one throws the Invalid SDK error and one has no problem at all.

Doug

**Comment by piotrzarzycki21** [comment] 2017-10-18 04:11
Hi Doug,

We are slowly moving FlexJS to Royale - for now I recommend you to use FlexJS nightly - till Moonshine official support Royale. - I will create for that work soon issue. 

As for your problem - is there any possibility to attach your project with problems here? Just wanted to confirm whether we have some problems in created project or not. 

Thanks!

**Comment by piotrzarzycki21** [comment] 2017-10-18 04:15
@doug777 ,

Another question - are you setup SDK in project settings or in global settings? Can you clear project settings and setup as main SDK global settings? 

Let me know what's the result then.

Thanks!

**Comment by doug777** [comment] 2017-10-18 04:19
This is the identical code in both projects - actually Alex's code -

<?xml version="1.0" encoding="utf-8"?>
<js:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
                 xmlns:js="library://ns.apache.org/flexjs/basic"
                 xmlns:mdl="library://ns.apache.org/flexjs/mdl"
                 xmlns:local="*"
				 applicationComplete="sendIt()">

    <fx:Script>
		<![CDATA[
			import org.apache.flex.net.events.FaultEvent;
			import org.apache.flex.net.events.ResultEvent;
			
			protected function sendIt():void
			{
                service.send("getUTCDateTimeNow", []);
			}
			
			private function onResult(evt:ResultEvent):void
			{
				trace("Result=" + evt.data);
				if (evt.data is String)
					received.text = "Received: " + evt.data;
			}
			
			private function onFault(evt:FaultEvent):void
			{
				trace("Fault=" + evt.message);
			}
			
		]]>
	</fx:Script>

    <js:beads>
        <js:ClassAliasBead />
        <js:RemoteObject id="service" result="onResult(event)" fault="onFault(event)"
                         endPoint = "http://www.booxotel.com/flex2gateway/"
                         destination = "ColdFusion"
                         source = "1_2_0.STime"/>
    </js:beads>

    <js:initialView>
        <js:View>
            <js:beads>
                <js:VerticalLayout />
            </js:beads>
            <js:TextButton text="Send request to CF" click="sendIt()"/>
			<js:Label id="received" width="300"/>
        </js:View>
    </js:initialView>

    <js:valuesImpl>
        <js:SimpleCSSValuesImpl />
    </js:valuesImpl>

</js:Application>

This is as3proj in both projects (apart from project name)

<?xml version="1.0" encoding="utf-8"?>
<project>
  <output>
    <movie height="600"/>
    <movie version="23"/>
    <movie disabled="False"/>
    <movie path="bin-debug/TestAlex.swf"/>
    <movie background="#FFFFFF"/>
    <movie fps="60"/>
    <movie width="800"/>
    <movie input=""/>
  </output>
  &lt;!-- Other classes to be compiled into your SWF --&gt;
  <classpaths>
    <class path="src"/>
  </classpaths>
  <moonshineResourcePaths></moonshineResourcePaths>
  <build>
    <option showUnusedTypeSelectorWarnings="True"/>
    <option locale=""/>
    <option strict="True"/>
    <option accessible="False"/>
    <option useNetwork="True"/>
    <option allowSourcePathOverlap="False"/>
    <option useResourceBundleMetadata="True"/>
    <option customSDK="C:\FlexJSSDKs\090Nightly"/>
    <option benchmark="False"/>
    <option warnings="True"/>
    <option additional=""/>
    <option verboseStackTraces="False"/>
    <option loadConfig=""/>
    <option linkReport=""/>
    <option optimize="False"/>
    <option es="False"/>
    <option showActionScriptWarnings="True"/>
    <option staticLinkRSL="False"/>
    <option showBindingWarnings="True"/>
    <option compilerConstants=""/>
    <option showDeprecationWarnings="True"/>
    <option antBuildPath="build/build.xml"/>
  </build>
  <includeLibraries></includeLibraries>
  <libraryPaths></libraryPaths>
  <externalLibraryPaths></externalLibraryPaths>
  <rslPaths></rslPaths>
  <intrinsics></intrinsics>
  <library></library>
  <compileTargets>
    <compile path="src/TestAlex.mxml"/>
  </compileTargets>
  <hiddenPaths></hiddenPaths>
  <preBuildCommand>null</preBuildCommand>
  <postBuildCommand alwaysRun="False">null</postBuildCommand>
  <options>
    <option testMovie=""/>
    <option testMovieCommand=""/>
    <option defaultBuildTargets=""/>
    <option showHiddenPaths="False"/>
  </options>
  <moonshineRunCustomization>
    <option targetPlatform="2"/>
    <option deviceSimulator="null"/>
    <option launchMethod="Simulator"/>
    <option projectType="2"/>
    <option urlToLaunch=""/>
  </moonshineRunCustomization>
</project>

The "old" project where I changed the code in the Application tag has the Invalid SDK error.

The "new" project has no error and compiles correctly.

Doug

**Comment by doug777** [comment] 2017-10-18 04:30
If I reset the project settings then in the as3proj file option testMovie changes to "OpenDocument" and option urlToLaunch changes to the path to index.html.

Clean project and try Build as Javascript again but still Invalid SDK.

The new project with the identical code now also fails with the same error.

Doug

**Comment by doug777** [comment] 2017-10-18 04:34
Can't find a way to display the as3proj file in this list. It seems to have been converted to Other classes to be compiled into your SWF  null null

**Comment by piotrzarzycki21** [comment] 2017-10-18 04:49
https://github.com/prominic/Moonshine-IDE/issues/16#issuecomment-337457412,

But in that case once you clean path to SDK in project settings, you have setup SDK in File -> Settings ?

Just wanted to confirm whether we are on the same page.

**Comment by doug777** [comment] 2017-10-18 06:07
I haven't reset the SDK just selected Modify then Reset for FlexJS projects in the global settings.

Looking at this step-by-step it looks to me as though some global variable that is checked when you select Build as Javascript can get set to false, but is not changed when the fault is corrected.

For example all is working well and then I change the Application tag to look for Royale namespaces. This then failed and probably this was correct, but when I changed it back to the way it was before, it still fails - the global variable is not reset. I create a new project with no mention of Royale and it works first time - could this be using some different variable? Then I reset the global variables and now the incorrectly set variable gets applied to the new project as well, so now that fails as well.

Closing and re-opening Moonshine never makes any difference to whatever this global variable is.

That's the way it looks to me.

Doug

**Comment by rat-moonshine** [comment] 2017-10-18 06:10
Hi @doug777 , thank you for this detail reporting and helping us identified the problems, and we're sorry for the trouble you're in, too.

* I started by creating a new Flex browser project, and copied the FlexJS source (that you've provided) and also ensured the `.as3proj` file content is same as yours (except the file name)
* I changed the custom SDK to the project from Flex SDK to FlexJS 0.9.0 
* I tried **Build & Run** and **Build & Run as JavaScript** - both thrown me invalid SDK error
* I closed the project from sidebar panel and re-opened - that fixed the invalid SDK problem and Moonshine started the compilation process

> Sadly the Invalid SDK error has returned even though Additional compiler options are empty string. I changed something in the Application tag and the fault reappeared. I reset it back to exactly as it was before but the fault remains. Tried changing sdk, downloading latest nightly build and changing to that, but nothing works.

Recently we've noticed that even keeping blank value against Additional Compiler Options in `.as3proj` file, when Moonshine loads the project it was setting some default value to the compiler option anyway, and leaving it not blank. This problem exists in 1.6.0. The problem fixed in current development build - https://github.com/prominic/Moonshine-IDE/commit/9d7d9cb9df5fa38425c0925ea850dfc7ba0a3384. 

> If I create a new js project and copy the code from the old project into the new project, there is no error and the compile works correctly.
> 
> The only difference I can find between the old and new project is that in the new project's option urlToLaunch="" is empty string whereas in the old project it has a value that points correctly to the index.html file.
> 
> I then set this line to empty string in the old project, and now there is no error.

Moonshine determines whether a project is Flex or FlexJS type of, at the time of loading the project. So if I opens a project as Flex, copied FlexJS source to the project and tried to run as FlexJS - it reports the invalid SDK error. If I close and reopen the project, it set the FlexJS flag properly against the project.

Looking through your test case, we probably need to re-think on this determination process and make it more run-time than load-time. We will plan to work on this.

Regarding `urlToLaunch` field in .as3proj, Moonshine set an automatic value to the field based on project type (i.e. in case of Flex `bin-debug/projectName.html`, in case of FlexJS `bin/js-debug/index.html`).

> If I reset the project settings then in the as3proj file option testMovie changes to "OpenDocument" and option urlToLaunch changes to the path to index.html.

There were some changes to `testMovie` value setter also, in recent development version - 83fd8d34cd47690f257385d7f38cb635763e5f3d.

**Comment by doug777** [comment] 2017-10-18 06:32
Thanks for your detailed explanation.

Despite these odd bugs, I like using Moonshine. Being built with Flex it feels kinda homely.

There's lots of rough edges, obviously, in something this complex with only volunteer development, but I think overall it's just great and I look forward to using it more and more every day.

Doug

**Comment by rat-moonshine** [comment] 2017-10-18 07:16
Based on @doug777 test cases, determination process between Flex and FlexJS project now moved from load-time to run-time.

@piotrzarzycki21 @JoelProminic please give some tests with latest build, if you shall have some time, based on Doug's test cases.

**Comment by rat-moonshine** [comment] 2017-10-18 18:07
In details, following are my test results with latest development build:

- Create a new Flex browser project and ensure it runs with a Flex SDK
- Tried to run **Build & Run** - it compiles the project as .swf and runs on browser (it runs the .swf file instead of .html - which is a bug reported here https://github.com/prominic/Moonshine-IDE/issues/48)
- Copied FlexJS source to the project 
- Changed the SDK to build with FlexJS SDK
- Run the project with **Build & Run as JavaScript**
- Project compiles and opens the .swf file to the browser - this is due to already set `URL to Launch` value pointing to `bin-debug` folder
- Moved to project's `Settings > Run > URL to Launch` field, and changed the URL to open JavaScript's html file instead - `bin/js-debug/index.html`
- Re-run with **Build & Run as JavaScript** option - this time after compilation done it opens the JavaScript html file
- Opened the project's `Settings > Run` section again, and cleared `URL to Launch` value, and saved settings
- Tried to run with **Build & Run as JavaScript**, it compiles and re-opened the `bin/js-debug/index.html` file
- Re-opening project's `Settings > Run` section, I noticed Moonshine auto-generated `URL to Launch` field with a valid URL pointed to `bin/js-debug/index.html`
- Closed and tried to run with **Build & Run**, project compiled and run the .swf file to the browser this time

Let me know if others have different results than mine, or something you likes to point.

**Comment by piotrzarzycki21** [comment] 2017-10-30 10:16
@rat-moonshine ,
One more user reported problem on Royale Dev list which may be related to that. I will got through your test cases today with development build and try to reproduce his issue in 1.6. We need make sure that issue is sorted out before release.

**Comment by piotrzarzycki21** [comment] 2017-10-30 10:53
@rat-moonshine ,

My results are exactly the same in each steps, but I had one additional issue. When I was doing here:

- Copied FlexJS source to the project
- Changed the SDK to build with FlexJS SDK

I had report in console all the time. `<js:Application` wasn't recognized. After close and reopen project everything was working and problems went away.  

`: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets
: Unknown tag:compiler.targets`

**Comment by rat-moonshine** [comment] 2017-10-30 11:14
I re-tried this current development version in Windows, and the steps you mentioned, worked good for me. 

After copying FlexJS source to the application file, I able to run both 'Build & Run' and 'Build & Run as JavaScript'. I did require to change `Settings > Run > URL to Launch` between the tests to open correct HTML file, though.

**Comment by piotrzarzycki21** [comment] 2017-10-30 11:18
@rat-moonshine I haven't say that build wasn't working. It just some code completion engine reported that tag was wrong, but compilation did work as we expected and as I said after reopen the project those warnings went away.

**Comment by rat-moonshine** [comment] 2017-10-30 11:28
Okay. Thanks for the clarification, @piotrzarzycki21 .

**Closed** 2017-11-10 10:02 UTC
Labels: bug, help wanted
