### ISSUE TITLE
Air Configuration Wizard

### ISSUE THREAD

**Issue by TheSzRaPnEL** [prominic/Moonshine-IDE#125] opened 2017-12-30 12:45 UTC
Not clear where to set {airHome} - wizard option missing?

**Comment by piotrzarzycki21** [comment] 2017-12-30 12:47
Hi @TheSzRaPnEL ,

What do you mean by airHome ? Air SDK itself or is it some compilation option ?

**Comment by TheSzRaPnEL** [comment] 2017-12-30 12:50
Yes, during compilation there is an error:
Error: unable to open '{airHome}/frameworks/libs/air/airglobal.swc
But couldn't find the place to set it so far. So it's not as intuitive as Apache Flex Configuration Wizard :)

**Comment by piotrzarzycki21** [comment] 2017-12-30 12:52
How did you download Apache Flex ? Using [Apache Flex Installer](https://flex.apache.org/installer.html) ?

**Comment by TheSzRaPnEL** [comment] 2017-12-30 12:53
I guess those files (AIR library) are inside Apache Flex.
There is a bug in the newest version that doesnt set proper air settings (location) ?

**Comment by TheSzRaPnEL** [comment] 2017-12-30 12:55
I have downloaded Apache Flex throught Moonshine 1.7.1 wizard (apache flex installer):
4.16.1 with fp 28 (not as default 27)

**Comment by piotrzarzycki21** [comment] 2017-12-30 12:56
Nope. Adobe Air is a separate SDK developed by Adobe. Apache Flex is an open source framework. If you would like to use it with some version of Air, please install Apache Flex Installer and use wizard there.

Our internal wizard need to be updated, cause it has one major issue where there is a problem with downloading Apache Flex with Adobe Air greater than 23.

**Comment by TheSzRaPnEL** [comment] 2017-12-30 12:57
I guess airHome property needs to be set (updated) in windows

**Comment by piotrzarzycki21** [comment] 2017-12-30 12:58
I will check our internal wizard to confirm my above assumption. - In the meantime please try to use Apache Flex Installer.

**Comment by TheSzRaPnEL** [comment] 2017-12-30 13:05
Ok I'll try.

**Comment by piotrzarzycki21** [comment] 2017-12-30 13:06
@TheSzRaPnEL I just updated appropriate file and installer will be showing from now on Adobe Air and Flash Player 28 as default.

**Comment by TheSzRaPnEL** [comment] 2017-12-30 13:08
How to update Moonshine? Does it have some auto updater?

**Comment by piotrzarzycki21** [comment] 2017-12-30 13:13
Once we release new version you should get prompt about it when you start your 1.7.1 version. I believe we will release 1.8.0 at the beginning of January. I cannot guarantee that internal Moonshine wizard will be fixed there. Apart of that you can follow us on Twitter, FB or LinkedIn where we will announce release. 

Once you download Apache Flex through Apache Flex Installer you will be able to build Flex/Air applications without the problem.

**Comment by TheSzRaPnEL** [comment] 2017-12-30 13:15
I have Apache Flex SDK from 4_14 fp 19 up to 4_15 fp 23.
After switching to 4_15 fp23 all works like a charm :)

thx for extremely quick answers :)

**Comment by piotrzarzycki21** [comment] 2017-12-30 13:18
I just confirmed that internal wizard need to be updated. @rat-moonshine I prefer live it to you. It can be done after 1.8.0 if we won't have capacity. I will assist you with installer swc preparation if needed.

**Comment by piotrzarzycki21** [comment] 2017-12-30 13:19
@TheSzRaPnEL I'm glad that is working! Thank you for trying Moonshine! More feedback is welcome! :)

**Comment by piotrzarzycki21** [comment] 2018-01-18 10:36
This problems are related to work in #119, where installer is being updated.

**Comment by piotrzarzycki21** [comment] 2018-01-23 13:34
@rat-moonshine since you did update installer - it looks like we are good to resolve that issue ?

**Comment by TheSzRaPnEL** [comment] 2018-01-23 13:59
No more installer issue for me.

**Comment by piotrzarzycki21** [comment] 2018-01-23 14:48
External installer should work for you, but our internal had issues. @rat-moonshine fixed them and in the version Moonshine 1.9.0 you should be able to download SDK using Moonshine. However let's wait for the confirmation.

**Comment by piotrzarzycki21** [comment] 2018-02-09 05:43
I don't see any reason to keep it open. Let's see what users will say if they try installer in 1.9.0

**Closed by piotrzarzycki21** 2018-02-09 05:43 UTC
Labels: bug
