### ISSUE TITLE
Renaming file end up with displaying in the console warning "Could not find source.."

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#201] opened 2018-03-14 07:49 UTC
When I rename file in the project I'm getting in the console several warnings:

```
Could not find source D:\Work\projects\Prominic.NET\Moonshine Tests\TabNavigatorTest\src\TabNavigatorWithOrientationSkin.mxml
: 3
```

**Scenario:** 
1. Create new project
1. Create MXML file 
1. Open created MXML file
1. Rename it

**Workaround:**
Close and reopen project.

**Comment by rat-moonshine** [comment] 2018-03-15 05:45
We worked on the file/folder renaming issue some time back - https://github.com/prominic/Moonshine-IDE/issues/147. 

I tried to follow your steps but couldn't able to reproduce the error, @piotrzarzycki21 . Following were my test steps.

- Created a new Flex Desktop project
- Created a new MXML file in the same source directory - Hello.mxml
- Added a reference of the newly created file in the main application file
- **Build & Run** worked good
- Renamed Hello.mxml to Hello2.mxml
- Tried to **Build & Run** - since the main application file was still holding reference to Hello.mxml in code, project thrown compiler error as expected
- Once changed the file reference with the renamed one, project build successfully again

I'm wondering what could be the difference between your and my test processes, though.

**Comment by piotrzarzycki21** [comment] 2018-03-15 09:11
I just found that I miss one step. I updated description. Open file before renaming.

**Comment by rat-moonshine** [comment] 2018-03-15 09:38
I followed the updated steps but still not seeing any problem. Following were my test procedures:

- Created a new Flex Desktop project
- Created a new MXML file in the same source directory - Hello.mxml
- Added a reference of the newly created file in the main application file
- Build & Run worked good
- **Open Hello.mxml to the editor**
- Renamed Hello.mxml to Hello2.mxml
- (previously) Hello.mxml editor tab title changed to 'Hello2.mxml'
- Tried to Build & Run - since the main application file was still holding reference to Hello.mxml in code, project thrown compiler error as expected
- Once changed the file reference with the renamed one, project build successfully again

**Comment by piotrzarzycki21** [comment] 2018-03-15 09:42
Are you doing it from FlashBuilder or installed version ? Are doing it on Mac ?

**Comment by rat-moonshine** [comment] 2018-03-15 09:45
I tested by installed Windows version, compiled with latest 'master' copy.

**Comment by piotrzarzycki21** [comment] 2018-03-15 10:06
Try this project. Open `ScrollerTesdsfsfdtSki` file and rename it. 
[ClassCastExceptionTest.zip](https://github.com/prominic/Moonshine-IDE/files/1814855/ClassCastExceptionTest.zip)

**Comment by rat-moonshine** [comment] 2018-03-15 10:24
I able to reproduce the issue with given test project, @piotrzarzycki21 . 

> : Could not find source C:\Users\Santanu\Desktop\ClassCastExceptionTest\src\ScrollerTesdsfsfdtSki_modified.mxml
> : 2

With my initial search I couldn't found any reference of the string display 'Could not find source' in main Moonshine source. I'm wondering if its something triggers from the language-server code (?) I noticed that this problem is not happening to a newly created file - but to the existing files after project being opened. 

I'm not sure why this triggers at this moment, @joshtynjala can you thought about any possible reason that could trigger these errors?

**Comment by piotrzarzycki21** [comment] 2018-03-15 10:44
Cool that you reproduced it. I cannot reproduce it in VSCode with extension 0.10.0

**Comment by joshtynjala** [comment] 2018-03-15 15:26
This and #204 are actually the same issue. The language server expects its client, such as Visual 
Studio Code or Moonshine, to listen for changes to the file system in the project folder and send a notification if anything is created, deleted, or changed. I don't think Moonshine is currently notifying the language server when something is created or deleted (which would affect renaming too).

I don't think AIR has a built in file system watcher, though. It may be possible to create one by manually polling the modified date of files (and checking if the list of files in a folder has changed), but it will probably be buggy while we work out the kinks, and it might not perform well. The language server adds its own file system watchers for source paths that are outside of the project folder, since Visual Studio Code can't do that. I could possibly add a special case where the language server adds a file system watcher in the project folder if it detects that Moonshine is the client.

**Comment by piotrzarzycki21** [comment] 2018-03-15 17:11
What actually I have to do in order to notify Language Server ? Operation like Create, Remove or Delete seems to be users choose, so I can send something to the server once it happens.

**Comment by joshtynjala** [comment] 2018-03-15 17:26
I don't think that you can make AIR watch for file changes and dispatch an event. You'd probably need to create a Timer and loop through the project folder to check for changes at an interval of a certain number of milliseconds.

As I was saying, though, I don't think that's a good idea. Java's file system watchers are probably more optimized and battle hardened, so I'd prefer to handle this in the language server. I'm already watching source-path folders outside of the project (starting in version v0.11), so it won't be difficult to watch for files inside the main project folder too.

**Comment by rat-moonshine** [comment] 2018-03-15 17:36
> I don't think that you can make AIR watch for file changes and dispatch an event. You'd probably need to create a Timer and loop through the project folder to check for changes at an interval of a certain number of milliseconds.

All the file/folder addition/deletion/renaming done through different Moonshine classes. We can dispatch event to language server notifying the changes. I'm not sure why you think the above check can be done through Timer loop (?)

**Comment by joshtynjala** [comment] 2018-03-15 17:45
@rat-moonshine That won't work if a file is created/deleted/modified outside of Moonshine.

**Comment by rat-moonshine** [comment] 2018-03-15 17:52
Ok, understood, @joshtynjala.

On a worst case scenario, after file changes outside of Moonshine, user needs to refresh the project tree (to get those changes displayed in sidebar). At that time if language server could somehow notified with any file changes.

**Comment by joshtynjala** [comment] 2020-01-08 23:23
This doesn't seem to reproduce anymore, so I'm closing it.

**Closed** 2020-01-08 23:23 UTC
Labels: bug
