### ISSUE TITLE
Error with Version 1.14.0

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#336] opened 2018-07-31 02:09 UTC
Windows 10 Pro 64-bit v1803

On opening Moonshine v13 offered upgrade to version 14. Accept. Upgrade successful.
When Moonshine reopens, the following is reported in Console

: Moonshine IDE 1.14.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 30.0.0.107
: 'git' is not recognized as an internal or external command,
: operable program or batch file.
: Error: Unable to access jarfile C:\Program Files (x86)\Moonshine\elements\codecompletion.jar
: 'git' is not recognized as an internal or external command,
: operable program or batch file.

Code completion does not work. (Everything else is OK)

On inspection, folder C:\Program Files (x86)\Moonshine\elements contains 
codecompletion.jar.r8023 (29,325KB) and
codecompletion.jar.r8025 (29,390KB)

Renaming either of these files to codecompletion.jar on reopening Moonshine Console shows

: Moonshine IDE 1.14.0
: Source code is under Apache License, Version 2.0
: https://github.com/prominic/Moonshine-IDE
: Uses as3abc (LGPL), as3swf (MIT), fzip (ZLIB), asblocks (Apache License 2.0), NativeApplicationUpdater (LGPL)
: Running on Adobe AIR 30.0.0.107
: 'git' is not recognized as an internal or external command,
: operable program or batch file.
: Error: Missing moonshine.port
: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
: 'git' is not recognized as an internal or external command,
: operable program or batch file.

Code completion still does not work.

On clicking Report Issue I get error 500.

Doug

**Comment by rat-moonshine** [comment] 2018-07-31 09:30
Thank you for reporting this @doug777 .

Looking into the console output provides by Doug, I assume Moonshine tries to test projects (when opened) if a Git repository:

> : 'git' is not recognized as an internal or external command

Unfortunately, I see we have missed a conditional check to not to run the test if user's system do not have Git installed at all.

I able to confirm the situation by:

- Uninstalling Git completely from my system
- Tested 'git' command throws as unrecognized command on command-line
- Installed 1.14.0 from the Moonshine website

But I couldn't able to reproduce the language-server issue Doug reported. @piotrzarzycki21 , @joshtynjala do you have any thought behind any reason to this (?)

To overcome the _git_ console output:

- Requisite condition now added to test if Git installed at all before testing any project if _git_ repository
- On macOS, _git_ binary access permission window now opens at startup, user can grant permission or skip the window - latter shall not avail Git functionality to Moonshine as it was suppose to be
- Latter also avail new menu option "Git > Grant Permission" if user wants to revisit the requirement at sometime again

We need to evaluate if we want a minor release with the above fixes.

**Comment by piotrzarzycki21** [comment] 2018-07-31 09:37
@rat-moonshine Are you saying that if @doug777 will install GIT in hist system he will be ok in that case ?

**Comment by rat-moonshine** [comment] 2018-07-31 10:31
Not exactly. Because without having git installed on my system, I couldn't able to reproduce the language-server error Doug reported, but only the 'git unrecognized command' console output. 

Measure taken to check if Git installed on user's system - that fixed the git repository test against project opening - which was causing the 'git unrecognized command' console output. 

But that does not related to the language-server access problem Doug reported.

**Comment by joshtynjala** [comment] 2018-07-31 13:57
> Error: Missing moonshine.port

This error indicates that Doug has an old version of codecompletion.jar, for some reason.

**Comment by piotrzarzycki21** [comment] 2018-07-31 14:00
WOW! I just upgrade Moonshine in the same way as @doug777 did it and have same issue.

**Comment by rat-moonshine** [comment] 2018-07-31 15:24
This now question me how this is happened? Everytime before package building at Bamboo, it builds Codecompletion.jar separately and placed under the source of `MoonshineSharedCore/src/elements`. This build suppose to be happen taking the most latest source from Git only. 

Practically, this even doesn't matter what codecompletion.jar is avail at Git repository under `MoonshineSharedCore/src/elements/codecompletion.jar` - Bamboo builds a latest .jar prior to Moonshine package build. This probably needs an investigation then.

**Comment by piotrzarzycki21** [comment] 2018-07-31 15:28
@rat-moonshine Moonshine 1.14.0 have correct codecompletion.jar, because after uninstalling whatever version you have and installing new one - everything is working correctly. It is just upgrade process doesn't update that file for whatever reason.

**Comment by rat-moonshine** [comment] 2018-07-31 15:29
That is srange!

**Comment by piotrzarzycki21** [comment] 2018-07-31 15:33
That's why I need some new issue and give Atin to make tests on both platform, using upgrade mechanism.

**Comment by rat-moonshine** [comment] 2018-07-31 15:37
> It is just upgrade process doesn't update that file for whatever reason.

As a consideration, I didn't upgraded through the in-built downloader, but I also didn't uninstalled and then fresh installed 1.14.0. I just ran 1.14.0 over existing installation, but that seems worked and didn't thrown me the language-server error. Technically, in-built update process downloads the same binary and only ran it.

I also need to see the way you've described, this sound strange.

**Comment by joshtynjala** [comment] 2018-07-31 15:41
If the language server is currently running, maybe the installer can't overwrite it?

**Comment by rat-moonshine** [comment] 2018-07-31 15:52
I confirm @joshtynjala assumption. I took out some simple steps by downloading both 1.13.0 and 1.14.0. Following are my test steps:

- Uninstalled any existing Moonshine 
- Installed 1.13.0
- Ran Moonshine - made sure no projects is open at the time and no language server instance running 
- Updated to 1.14.0 using in-built updater/downloader
- Moonshine started with 1.14.0 and I didn't found any problem with language-server

Next tests:

- Uninstalled existing Moonshine again
- Installed 1.13.0
- Opened two projects at a time - made sure two Java instance running in Task Manager
- Through the updater prompt in Moonshine downloaded 1.14.0
- After having it downloaded Moonshine auto-exit
- Both the Java instance shown keep running in Task Manager - this is similar to the issue reported in #325 
- Moonshine installed - Java instances keep running
- Upon starting Moonshine 1.14.0 - language-server is not working anymore

Huh, that was easy!

**Comment by rat-moonshine** [comment] 2018-09-07 15:54
Without creating a new duplicate language-server issue, I have updated the 2nd part of the problem discussed here to #325 as known issue. 

I'm closing this issue for 1.15.0 now.

**Closed by rat-moonshine** 2018-09-07 15:54 UTC
Labels: Investigation, bug
