### ISSUE TITLE
Support for Nightly builds

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#70] opened 2017-11-19 05:53 UTC
Re: Added partial support for Apache Royale. User is able to open, build
project and write code using Nightly build of Apache Royale.

I am converting old Flex browser project to JS.
Up to now I am working with Royale 0.8.0. Problems panel correctly shows errors for classes in 0.9.0 but not in 0.8.0, and other items I have yet to resolve.

Upgrade to 1.6.1 and download latest FlexJS Nightly with AIr 23 and Flash 23. Change project to new sdk.

Problems panel now shows following only :

unknown configuration variable 'compiler.fxg-base-class'. -path-\frameworks\flex-config.xml (line 127)

line 127 of this file is <fxg-base-class>flash.display.Sprite</fxg-base-class>

Doug

**Comment by piotrzarzycki21** [comment] 2017-11-19 10:56
Hi @doug777 ,

I think you got an explanation and workaround for that issue from Josh #23. You will experience that whenever you download fresh nightly, so you have to proceed with workaround. This issue is a duplicate of #23.

Thanks,
Piotr

**Closed by piotrzarzycki21** 2017-11-19 10:56 UTC
Labels: duplicate
