### ISSUE TITLE
Cursor Flashes in Console Without Focus

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#130] opened 2018-01-08 22:29 UTC
While testing #114, I noticed that the console cursor keeps flashing as if it has focus even after I have moved focus to an editor
1. Open a project in Moonshine
2. Click in the console
3. Run "help"
4. Click in the editor
5. BUG: The cursor keeps flashing in the console
6. Press a key
7. CORRECT:  the text is added in the editor
8. BUG: The cursor keeps flashing in the console

**Comment by atinprominic** [comment] 2018-01-30 13:09
I still found the issue. Steps to reproduce are:

1. Open a source file.
2. Click anywhere in the source code file opened in work area.
3. Click in the Console.
4. Click on the Help Menu on Top.

Now you will notice that the curser is blinking at all the 3 positions.

**Comment by atinprominic** [comment] 2018-01-31 09:51
I am still able to see 3 cursors flashing. Please find the attached screenshot:

![screen shot 2018-01-31 at 3 16 35 pm](https://user-images.githubusercontent.com/34882311/35616134-5d53a8a8-069a-11e8-9f4b-4a3cff79d241.png)

**Comment by piotrzarzycki21** [comment] 2018-01-31 10:21
I see where the problem is. It's working on Windows, but Mac's menu is a different story in connection with flashing cursor. I don't have access to my Mac today, but will investigate it tomorrow.

**Comment by rat-moonshine** [comment] 2018-04-05 05:34
I revisited this issue again today, and gave some tests to verify if this issue is still valid, or we can close it keeping this as low priority. 

While I've found Atin's last test report is still valid on macOS (although, I'm not worried about the cursor blinks on editor) but it would have been better if we could remove the blink cursor from console while clicking on the application menu.

Further test results are as follows:

#### Correct
- Click once on the console input, cursor blinks to the console
- Click once on the opened editor, cursor blink removes from the console

#### Bug
- Click once on the console input, cursor blinks to the console
- Click on the macOS search icon (magnifying glass icon at top-right in system statusbar), this shall open OS' search field on screen
- Above removes the blink cursor from console
- Click back again on console input - you can write something but it does not shows blink-cursor anymore

#### If we can fix
- From Atin's test report if we can remove the blink cursor from console while clicking on application menu

I try to give some investigation if could find a fix, specially the buggy one. If this would take long time, I would close this as known and won't fix issue.

**Comment by rat-moonshine** [comment] 2018-04-05 09:13
After spending some time, most possible event listener I felt is [SandboxMouseEvent](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/events/SandboxMouseEvent.html). However, opposite to its expected behaviour (as mentioned in the Adobe Doc), only `MOUSE_UP_SOMEWHERE` fired in my tests, and that is also not by Mouse-up/down but when mouse-out from the application frame/window. I was hoping to get a mouse up/down event anywhere out of the application sandbox, but this event didn't worked well in my tests on macOS. 

I also tried to get menu open even from macOS NativeMenu. NativeMenu fires its `Event.SELECT` event on children item click but not when the topmost menu item clicked. I could anyway pass `Event.DISPLAY` event against menu item (and listen for it in console input section), but this will fire for each items in submenu (i.e. if File menu has 5 items in its submenu, opening the submenu will fire 5 individual `Event.DISPLAY` events). I think this is a bit overkilling.

Because of the above problem, I didn't found any other workaround as well. I documented these above so we can have investigation we did noted.

The **Bug** from my last comment has taken care of.

I'm closing this as won't fix. Please, reopen this if you have a plan to investigate on this further.

**Closed by rat-moonshine** 2018-04-05 09:13 UTC
Labels: Mac, bug

**Comment by piotrzarzycki21** [comment] 2018-04-05 09:53
I think I come up to the same results as you. I'm glad that you did look into that with fresh eye. :)

**Comment by JoelProminic** [comment] 2018-04-05 16:02
I can still see the cursor flashing in multiple locations while the focus is on the console.   I created a separate issue for the Editor logic:  #222
