### ISSUE TITLE
Cursor Flashing and Focus Behavior for Editor

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#222] opened 2018-04-05 16:00 UTC
While reviewing #130, I noticed similar cursor issues for the Editor window.

1. Click in the Editor.  The cursor flashes
2. Click on the Console.  BUG:  The cursor flashes on both the console and the Editor
3. Type a command.  The text appears on the console only
4. Switch focus to another window.  The cursor stops flashing on the console.  BUG:  the cursor is still flashing in the editor
5. Click on the application header to bring focus back to Moonshine.  BUG: Both the console and the editor flash again
6. Type a command.  The text appears on the console

I can envision a situation where a user sees the cursor flashing in the editor as the switch back to Moonshine, but can't type in editor because the focus is on the console instead.

Unfortunately, @rat-moonshine reported that the editor is more complicated than a simple text input, so this would take more work to fix.  I have created a separate issue so that we can track and prioritize this separately.

**Comment by rat-moonshine** [comment] 2018-04-06 04:34
Per my past observation, Moonshine editor manages cursor by its own cursor manager classes. Generally, in an application against multiple regular text input/area components, changing text input focus manages only one cursor at a time. Since the editor has its own manager class responsible to show cursor by its own logic, the regular behavior of cursor do not fits in.

While we can investigate to manage one cursor at a point inside Moonshine sandbox, determining click event in another sandbox application (or outside of the Moonshine application) may not possible. In general cases, clicking outside of the application lost text input focus inside the application. Since Moonshine now may needs to trap click event to manage only cursor in the application, in different scenarios to keep the cursor focused/not-focused we may need to determine mouse click outside of the application. 

In my last investigation in #130 , I have found the most possible API ([SandboxMouseEvent](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/mx/events/SandboxMouseEvent.html)) that was suppose to inform us on this outside click events in ActionScript, does not works on macOS. Thus, we may or may not effectively lost focus from the editor when Moonshine is not active. 

At this moment, we shall target to keep only cursor inside the application only.

**Comment by JoelProminic** [comment] 2018-04-06 16:55
I confirmed that the cursor disappears from the editor window in these cases:
- Cursor moved to console
- Click on Projects sidebar
- Open a popup like Edit > Find Resources

The cursor reappears when focus is returned to the Editor tab.  You can click on the tab to gain focus without changing the cursor position.  

The cursor still does not disappear when switching to a different application.   I suggest that you try to show/hide the cursor based on the application gaining/losing focus, rather than click events on other applications (https://forums.adobe.com/thread/1139517 ).

**Comment by rat-moonshine** [comment] 2018-04-09 05:09
Application state focus now handled, as well.

**Comment by JoelProminic** [comment] 2018-05-21 19:05
In my tests today, I noticed that the cursor stayed flashing in the editor when I switched to other applications.  I'm not sure when this behavior started again, but it behaved this way even if I opened new files or restarted Moonshine.  I am testing on MacOS Yosemite.

**Comment by rat-moonshine** [comment] 2018-05-22 06:20
Measure taken, please have a look.

**Comment by JoelProminic** [comment] 2018-05-22 16:13
I was not able to reproduce the issue I reported after @rat-moonshine 's update.  I also retested and confirmed some of the other cases we discussed above:
- Moving cursor between console and editor
- Cursor hidden after opening Find Resource prompt

I noticed that the cursor stays flashing in this case:
1. Open an editor window
2. Click on the Project sidebar - the cursor stays flashing
3. Type text.  The text does not appear at the cursor position in the editor.

If the editor still had focus, I would not mind if the cursor stayed flashing.  However, the Projects panel uses the text input to move between the files in the tree (it moves to the next file that starts with the letter you typed).

**Comment by rat-moonshine** [comment] 2018-05-23 05:59
The above said problem has rectified. 

While testing, I have found another issue by following steps:

1. Let console command line has the focus - it should show its blinking cursor 
2. Expand/collapse the project node in sidebar by clicking on the arrow icon - do not select the row
3. Console command editor lost its blinking cursor
4. Type something, console continue to prints them in the command line

The above scenario is also now fixed. Please, check.

**Comment by piotrzarzycki21** [comment] 2018-05-23 06:15
Guys if there is any fix for console, please postpone it for now, because I'm working on reorganization #214 the bottom panel and there is already a lot of changes in that area. I would like to avoid huge conflicts.

**Closed** 2018-05-25 09:27 UTC
Labels: Investigation, enhancement

**Comment by atinprominic** [comment] 2018-05-31 08:06
I have tested on MAC and tried to reproduce the issue but I am unable to reproduce the issue of cursor flashing. So it seems to be working as expected.

**Comment by piotrzarzycki21** [comment] 2018-05-31 13:11
After latest changes related to console this may not occurs anymore. @JoelProminic can you give a try.

**Comment by JoelProminic** [comment] 2018-05-31 15:34
I tested moving the cursor to:
- Console
- Editor
- Projects sidebar
- Property in Visual Editor
- Popup (Find / Find Resources)
- Updated debug window

In each of these cases, the cursor disappeared in the old location, and characters were received in the new panel (there were no actions for characters in the Debug window).

I also confirmed that the flashing cursor is hidden when moving focus to a different application.

I confirmed @rat-moonshine's last reported.  When I expand/collapses project nodes in the Projects sidebar, this does not cause the cursor to move to the sidebar.

I don't see any remaining issues.
