### ISSUE TITLE
Global Git Configuration File Ignored on macOS

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#328] opened 2018-07-17 19:55 UTC
While testing #295, I noticed that Moonshine did not use the global configuration file for git on macOS:
1. Create a new project from Moonshine
2. Run git init on the project
3. Use "git config --global --edit" to ensure that you have set a custom user and email
4. From Moonshine, make a commit to the new project
5. Run "git log". BUG:  the log message for the commit shows the default user and email instead (computed from the workstation name)

I get the same error even if I add an entry for my home directory in File > Access Manager

Moonshine Git uses the correct user and email on Windows.

See this page for more information on the global configuration for Git:  https://git-scm.com/docs/git-config

**Comment by santanu4ver** [comment] 2018-07-19 10:08
I've spent some time on this testing different way in sandbox application, but all were failed so far. 

The kind of behaviour we've noticed, seems similar to the problem discussed at here: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/ (**Commits are not linked to any user**).

I noticed that locally a git project's configuration file does have `user.name` and `user.email` value properly set. For some reason when Moonshine commits, this value is not using. I tried to manually re-set the value to the configuration file before a commit in Moonshine.

In development mode, when I manually set the current project's config `user.name/email` details and therefore execute the commit command, that worked expectedly. Following was the order of the processes in Moonshine:

```
// additional setup even I had user.email set in the project's directory
git config user.email "devsena@yahoo.com"
// execute the commit command
git commit -m "my message"
```

Since above worked, I modified code to get the project's `user.email/name` before even re-setup it:

```
// get by the current project's configuration
git config user.name
// after getting above info re-setup the user name details before commit
git config user.name &{user.name}
// execute commit
git commit -m "my message"
```

However, all of the above commands passed execution successfully in development/debug mode but in sandbox mode. 

Strangely, `git config user.name` or `git config --global user.name` does not returns ANYTHING (no std.error, no std.data). 

Since above command do not returns, I'm not sure how to get the project's user name/email without prompting the user, but I think the process is non-intuitive. 

Later, I just tried to static run following command in sandbox Moonshine before commit:

`git config user.email "devsena@yahoo.com"`

I see that did not effect at all, instead executing the above command returns me following report on console:

```
:  Committer: devsena@yahoo.com <myPcName@myPcName-MacBook-Pro.local>
: Your name and email address were configured automatically based
: on your username and hostname. Please check that they are accurate.
: You can suppress this message by setting them explicitly. Run the
: following command and follow the instructions in your editor to edit
: your configuration file:
:     git config --global --edit
: After doing this, you may fix the identity used for this commit with:
:     git commit --amend --reset-author
:  2 files changed, 3 insertions(+), 3 deletions(-)
```

**Comment by JoelProminic** [comment] 2018-07-19 17:29
Here is my proposed workaround:

Read the name and email that will be used in the git commit with these commands.

    git config user.name
    git config user.email

Do not use the "--global" flag here.  "git config" will check the global configuration automatically if there is no local configuration for the property.

If the returned value for the commands is blank, then report the value as "<Default>".

Add a line in the Commit panel between the file selection control and the commit message field.  The text should be like this:

    Author:  <user.name> (<user.email>) [How can I change this?]

    # Examples:
    Author:  JoelProminic (JoelProminic@test.com) [How can I change this?]
    Author:  <Default> (<Default>) [How can I change this?]

The "How can I change this?" text should be a link or button that shows a panel like this:

" See <this page>(https://gizmodo.com/elon-musk-should-tweet-more-1827696251) for instructions on changing the user name and email for your commits.
"
" NOTE:  The macOS version of Moonshine does not have access to the global configuration file for git.  You will need to define your name and email for each project.

As a further improvement, we could let the user set the local config values from this panel.

**Comment by santanu4ver** [comment] 2018-07-20 10:55
Requisite steps added to fetch local/global git user name/email to notify in the commit selection window. 

However, the URL to the instruction seems wrong, we shall need to change this.

**Comment by JoelProminic** [comment] 2018-07-20 14:36
Oops! :P  
Here is the correct address:  https://help.github.com/articles/setting-your-commit-email-address-in-git/

**Comment by JoelProminic** [comment] 2018-07-20 17:14
During testing today, @rat-moonshine found that the name and email values were not being overwritten if the later values were blank:
1. Global git configuration values has following name and email - 'devsena', 'devsena@yaoo.com'
2. New project created, closed the project
3. Ran 'git init' to the project
4. Ran 'git config user.name "devsena_local"' and 'git config user.email "devsena_local@yahoo.com"' to the project's directory
5. Re-started Moonshine with the project, and opened Git > Commit
6. Author: devsena_local (devsena_local@yahoo.com)
7. Ran 'git config --unset user.name' and 'git config --unset user.email' to local project's directory through Terminal
8. Immediately ran 'git config user.name' and 'git config user.email' to the local project's directory through Terminal
9. I see both the values were reset with the global configuration value
10. Ran Git > Commit in Moonshine
11. Author: devsena_local (devsena_local@yahoo.com)
12. Re-started Moonshine and re-run Git > Commit
13. Author: \<Default> (\<Default>)
14. Ran 'git config --global --unset' to both user name and email on Terminal
15. Tested returns nothing when ran 'git config --global user.name' or email on Terminal
16. At this moment do not have any global or local configuration user name and email
17. Ran Git > Commit in Moonshine
18. Author: \<Default> (\<Default>)
19. Restarted Moonshine and Git > Commit
20. Author: \<Default> (\<Default>) 


I noticed this behavior:
1. Close all projects
2. Open a Git project
3. Open a non-Git project
4. Restart Moonshine.  The non-Git project is selected
5. Select the Git project and run Git > Commit.  The Author text is *not* populated. 

IMAGE

Also, I intended for the instructions panel to have text instead of the full link, but the format got messed up in my comment:

> See [this page](https://help.github.com/articles/setting-your-commit-email-address-in-git/) for instructions on changing the user name and email for your commits.
>
> NOTE: The macOS version of Moonshine does not have access to the global configuration file for git. You will need to define your name and email for each project.

**Comment by JoelProminic** [comment] 2018-07-23 17:44
I checked @rat-moonshine's updates, and they seem to work well on macOS.

This behavior is still triggering for me on Windows, even after the update later in the chat:
1. Close all projects
2. Open a Git project
3. Open a non-Git project
4. Restart Moonshine.  The non-Git project is selected
5. Select the Git project and run Git > Commit.  The Author text is *not* populated.

**Comment by rat-moonshine** [comment] 2018-07-24 07:59
I still couldn't able to reproduce by above steps on Windows 10 tests. Every time author information did come up without a fail, for me. However, I did see some miliseconds' of delay as the executions are queued. 

_.git_ folder now added to the project deletion list.

**Comment by JoelProminic** [comment] 2018-07-24 20:22
Git project deletion now works.

The restart issue I reported has been triggering consistently for me, but not for @rat-moonshine.  It is possible that this is something specific to my workstation.    This behavior does not need to hold up the release, so I am closing this issue.

**Comment by rat-moonshine** [comment] 2018-07-25 04:52
We may can track the above result by a separate issue if we want. I shall ask Piotr to give some tests on his workstation, and open a new issue if he also find same. Since the original issue is now addressed, I'm closing this one.

**Closed by rat-moonshine** 2018-07-25 04:52 UTC
Labels: bug
