### ISSUE TITLE
Open all previously opened project/tree-state when Moonshine starts

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#106] opened 2017-12-11 13:02 UTC
[This enhancement request is related to #86 ]

Since #86 is now working good, I suggest to start Moonshine with its sidebar open, containing all the last opened project and their tree state. This will be very handy revisiting the last worked projects.

**Comment by piotrzarzycki21** [comment] 2017-12-11 13:11
This option should be also configurable through the settings.

**Comment by piotrzarzycki21** [comment] 2017-12-14 18:46
I have finished implementing that. Previously opened projects now reopening after startup, options for switching off this feature is available in settings.

In the future if users will complaining about some lag in open we may want to implement some spinner for loading projects.

**Comment by rat-moonshine** [comment] 2017-12-15 08:40
Can you point me to the codes where previously opened projects opened to the sidebar (based on `SaveFilePlugin.openPreviouslyOpenedProjects`)? I would like to tweak on its opening time.

**Comment by piotrzarzycki21** [comment] 2017-12-15 08:56
This is the place -> [ProjectPlugin](https://github.com/prominic/Moonshine-IDE/blob/19b319b89cbbd8060389c336c7856c39a0328ccf/ide/MoonshineSharedCore/src/actionScripts/plugin/project/ProjectPlugin.as#L334)

**Comment by rat-moonshine** [comment] 2017-12-18 11:04
I noticed some trouble while testing in Moonshine on macOS, when there were multiple projects opened. 

- Had different projects opened at a time - say one is FlexJS and another is browser SWF
- From both the projects some files were opened on editors, branches were expanded as well
- Upon restart, Moonshine did able to auto-load all the projects to the sidebar and also opened previous files in editors
- At the same time I received this error in my debug test:

```
RangeError: Error #1125: The index 20 is out of range 1.
	at actionScripts.ui.editor.text::DiagnosticsManager/showDiagnostics()[/Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/ide/MoonshineSharedCore/src/actionScripts/ui/editor/text/DiagnosticsManager.as:73]
	at actionScripts.ui.editor.text::TextEditor/showDiagnostics()[/Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/ide/MoonshineSharedCore/src/actionScripts/ui/editor/text/TextEditor.as:742]
	at actionScripts.ui.editor::ActionScriptTextEditor/showDiagnosticsHandler()[/Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/ide/MoonshineSharedCore/src/actionScripts/ui/editor/ActionScriptTextEditor.as:352]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at actionScripts.utils::LanguageServerForProject/textDocument__publishDiagnostics()[/Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/ide/MoonshineDESKTOPevolved/src/actionScripts/utils/LanguageServerForProject.as:534]
	at actionScripts.utils::LanguageServerForProject/onIncomingData()[/Users/devsena/Documents/Adobe Flash Builder 4.7/ProminicGITBranch/ide/MoonshineDESKTOPevolved/src/actionScripts/utils/LanguageServerForProject.as:653]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at flash.net::XMLSocket/scanAndSendEvent()
```

@piotrzarzycki21 can you please take a look?

**Comment by piotrzarzycki21** [comment] 2017-12-18 12:18
@rat-moonshine I saw that issue and had fix for that for a long time, but I couldn't reproduce it later on. I just pushed fix.

**Comment by JoelProminic** [comment] 2017-12-19 22:38
I saw this behavior in my testing with multiple projects.  This could be related to #73, but it seemed to mainly trigger with restarting Moonshine.

1. Open Moonshine
2. Open two projects
3. Open one file from each project
4. Restart Moonshine. 
5. Both files reopen
6. Right-click on a tab and select "Close All" (or File > Close All)
7. Restart Moonshine
8. BUG:  Both files open again when Moonshine is restarted

On another run I saw:

1. Open Moonshine
2. Open two projects
3. Open one file from each project
4. Restart Moonshine. 
5. BUG:  only on file reopened
6. Reopen the other file
7. Right-click on a tab and select "Close All" (or File > Close All)
8. Restart Moonshine
9. BUG:  Both files open again when Moonshine is restarted

**Comment by rat-moonshine** [comment] 2017-12-20 07:28
As an initial alarm - I noticed the following case (while working on different issue) moving through many opened tabs, activating them through the hamburger menu AND having states on Moonshine after restarts. 

At some time I noticed I have duplicate tabs opened to the editor. Generally when opened through the sidebar it checks if the given path file already opened to the editor - if yes, it activates the opened tab only. 

![duplicatetab](https://user-images.githubusercontent.com/24370870/34195817-66fd180c-e585-11e7-940f-73b2bdf1c66f.png)

I couldn't found a proper way to reproduce this again, but lets keep an eye on this.

**Comment by rat-moonshine** [comment] 2017-12-20 08:14
I able to reproduce the above problem in following manner:

- At a time I had these tabs opened in Moonshine stage (without any hamburger menu) - FileA, FileB, FileC, FileD, Search, FileE
- Restrated Moonshine
- I found auto-opened tabs in random orders now, no Search tab (expectedly), but a hamburger menu this time
- The hamburger menu consists of one file which was already a visible tab
- Clicking on the item from hamburger menu generates a duplicate tab to the same file

**Comment by rat-moonshine** [comment] 2017-12-20 12:08
On a separate note, I think we want to do some changes in re-opening logic. At this moment, the 3rd option a little confusing:

![image](https://user-images.githubusercontent.com/24370870/34206263-de1ba40a-e5ab-11e7-9888-03326138ab90.png)

Perhaps, we want to keep projects' branch opening as a thumb rule when the 1st option (Open previously opened projects on startup) is selected. If user opens a project from recent list or Open Project dialog, we can consider to think that the user closed the project intentionally previously, or do not want it to populate in sidebar next time Moonshine starts, and open the project without branch history.

We can keep the other two options default selected. @JoelProminic what you suggest on this (?)

**Comment by piotrzarzycki21** [comment] 2017-12-20 12:19
Quick info here: I was able to reproduce duplicate Tabs issue and I have found the cause. Working on a fix!

**Comment by piotrzarzycki21** [comment] 2017-12-20 13:17
Issues with duplication Tab and Close All has been handled. However it may occurs for you again, cause you may have some old values in shared object. Resetting settings will help for sure, but closing not necessary. Issue was with saving/removing tabs from shared object where I based on active project which not necessary have to be correct during reopen project scenario.

**Comment by piotrzarzycki21** [comment] 2017-12-26 10:57
@rat-moonshine I have extracted your question to separate issue.

**Closed by piotrzarzycki21** 2017-12-26 10:57 UTC
Labels: enhancement

**Comment by atinprominic** [comment] 2017-12-27 08:38
I would suggest to somehow save the opened projects as Workspace, then it would be better. For example - The developer is working on multiple assignments. In 1 assignment there are 2 projects and in 2nd assignment there are 4 projects. The developer should have flexibility to create 2 sets and open each when required.

Thanks
Atin

**Comment by piotrzarzycki21** [comment] 2017-12-28 10:48
@atinprominic nice idea, but I don't see that Moonshine have any kind of work space as default. We are not force on the user at the beginning creation of workspace. I bet that most of the users (including me) will never use workspace. This addition is to me rather separate feature with not so high priority. Please extract it to separate issue if you really see it as part of Moonshine.
