### ISSUE TITLE
Improve workspaces mechanism in Moonshine

### ISSUE THREAD

**Issue by piotrzarzycki21** [prominic/Moonshine-IDE#416] opened 2018-11-09 14:32 UTC
Real world use case scenario related to Workspaces:
Let's say that I have two customers **A** and **B** for whom I develop applications. If I have some presentation/demo call I don't want to see mixed project on ProjectTree from customer **A** and **B** nor have some list of lately opened files in Home tab.

**Comment by rat-moonshine** [comment] 2018-11-19 15:17
This is something how we used to see things in Eclipse, too. However, since this been a long time, and many involvement - I feel hard to remember what is the present functionality for the existing workspace concept that we have in Moonshine:

![image](https://user-images.githubusercontent.com/24370870/48715914-205da100-ec3c-11e8-988e-a91d57883850.png)

I think the existing workspace concept in Moonshine is more basic in nature, however I'd also ask this once with Joel if he can help me remember, too.

**Comment by rat-moonshine** [comment] 2018-11-19 15:40
> Even if it was basic, what was the concept in general. It would be great to know if it's even possible.

Yes, that is what I would like to re-explore with Joel.

**Comment by rat-moonshine** [comment] 2018-11-20 05:47
Upon discussing this with Joel, we couldn't able to recall much about its initial goal or where it had been (in past), unfortunately. This is probably sad its initial goal has long lost somewhere in the past. 

I went through the codes, and didn't found much about its workingness, either. Beside storing a path value against `Moonshine > Settings > General > Moonshine Workspace`, I did not found the stored data using elsewhere.

Moving ahead, I mock-down some idea how we want the feature probably in Moonshine, providing how a workspace concept that suppose to work in an IDE, that also meet Piotr's needs.

![image](https://user-images.githubusercontent.com/24370870/48753855-9520f180-ecb5-11e8-9a5d-4b0b1271fe34.png)

As an additional usefulness of the default-workspace path, we can provide a checkbox in project creation dialog, too (as we use to see in Eclipse) to choose between earlier saved/suggested path and the default workspace path (at present, Moonshine suggests by last-project-saving path).

**Comment by rat-moonshine** [comment] 2018-11-21 08:44
@JoelProminic proposed an interesting way (to maintain workspace) which is non-conventional but modern, which is non-directory based rather cookie-based. His idea is not to group projects by conventional directory-path but grouping of projects by modifying the existing project-open-at-startup logic/data.

As he explained his idea to this proposed design:

1. Moonshine starts initially with a Default Workspace. If the user does not do anything with the workspace, this will effectively work like Moonshine does now (restoring open projects on restart)
2. The user opens some related projects
3. The user clicks Workspaces > Save as Workspace. If they user wanted to treat the current set of projects as a new workspace, they would click Workspace > Save As instead
3a. The user will be prompted for a label.
3b. The current projects will be "linked" to this workspace label
3c. Moonshine will use the "new" workspace as the active workspace
4. As the user opens/closes more projects, the current workspace will be updated
5. The user wants to create a different group of projects (i.e. for a different customer). They click "Workspace > New", this close all open projects, and enter a label. The new workspace is now active
6. The user opens the desired projects, which are automatically added to the active workspace
7. The user wants to switch back to the old workspace. They go to Workspace > Open and select the old workspace (or select from a "recents" menu)

However, like all design the above design has some of its cavities, as Joel pointed:

- Since all the grouped data stores to Moonshine state/cookie, if the data got cleaned for some reason, all these grouping will also lost
- Since the design enforce auto-update-self (upon project open/close), user may mistakenly close one or multiple projects during a session, which will also got updated to the workspace data

I liked this new design, and this will also eliminate to lookup for workspace-directories; I think we anyway needs to save those directories to Moonshine cookie and opened projects against them. However, I questioned on auto-updating feature in step.4 - where user may not wants to have a project saved/updated to the active workspace (of course, s/he can remove the project later on if decide not to update). Thus, I suggested a notification against every workspace update:

I envisioned a small popup at bottom corner Moonshine (like we use to see in Visual Code Editor), mentioning that the active workspace updated (on project open/close), which will also have an Undo button; User can choose to do nothing to that popup, the poup will disappear after a few seconds. If user choose to undo the recent update, Moonshine should update the workspace data accordingly.

@piotrzarzycki21 what is your thought on these (?)

**Comment by JoelProminic** [comment] 2019-04-19 19:32
As I was writing up #529 today, I realized that it could be used as a very basic implementation of workspaces.  

To switch workspaces with this method:
1. Close all open projects (we could add a single action for this if desired)
2. File > Open/Import Project and select the workspace directory
3. Moonshine gives a prompt listing all of the project.  You can then click a button to all of the projects.

This has the following limitations as workspaces implementation:
- It requires that user organizes the projects by directory
- The known workspaces are not tracked
- There are no workspace labels except the directory name
- It can't show a filtered list of projects in the same parent directory (although the user can deselect the directories as desired)

So, #529 is not a perfect solution for this issue, but there is at least some overlap between the functionality.

**Comment by rat-moonshine** [comment] 2020-07-06 16:24
@piotrzarzycki21 since we were discussing many different open issues on Moonshine, do you have any thought/input since the last comment from me or @JoelProminic in this one?

**Comment by piotrzarzycki21** [comment] 2020-07-08 08:35
> @JoelProminic proposed an interesting way (to maintain workspace) which is non-conventional but modern, which is non-directory based rather cookie-based. His idea is not to group projects by conventional directory-path but grouping of projects by modifying the existing project-open-at-startup logic/data.
> 
> As he explained his idea to this proposed design:
> 
> 1. Moonshine starts initially with a Default Workspace. If the user does not do anything with the workspace, this will effectively work like Moonshine does now (restoring open projects on restart)
> 2. The user opens some related projects
> 3. The user clicks Workspaces > Save as Workspace. If they user wanted to treat the current set of projects as a new workspace, they would click Workspace > Save As instead
>    3.1. The user will be prompted for a label.
>    3.2. The current projects will be "linked" to this workspace label
>    3.3. Moonshine will use the "new" workspace as the active workspace
> 4. As the user opens/closes more projects, the current workspace will be updated
> 5. The user wants to create a different group of projects (i.e. for a different customer). They click "Workspace > New", this close all open projects, and enter a label. The new workspace is now active
> 6. The user opens the desired projects, which are automatically added to the active workspace
> 7. The user wants to switch back to the old workspace. They go to Workspace > Open and select the old workspace (or select from a "recents" menu)
> 
> However, like all design the above design has some of its cavities, as Joel pointed:
> 
> * Since all the grouped data stores to Moonshine state/cookie, if the data got cleaned for some reason, all these grouping will also lost
> * Since the design enforce auto-update-self (upon project open/close), user may mistakenly close one or multiple projects during a session, which will also got updated to the workspace data
> 
> I liked this new design, and this will also eliminate to lookup for workspace-directories; I think we anyway needs to save those directories to Moonshine cookie and opened projects against them. However, I questioned on auto-updating feature in step.4 - where user may not wants to have a project saved/updated to the active workspace (of course, s/he can remove the project later on if decide not to update). Thus, I suggested a notification against every workspace update:
> 
> I envisioned a small popup at bottom corner Moonshine (like we use to see in Visual Code Editor), mentioning that the active workspace updated (on project open/close), which will also have an Undo button; User can choose to do nothing to that popup, the poup will disappear after a few seconds. If user choose to undo the recent update, Moonshine should update the workspace data accordingly.
> 
> @piotrzarzycki21 what is your thought on these (?)

I like the idea let's pursue in that direction.

**Comment by piotrzarzycki21** [comment] 2020-07-08 08:39
> Thus, I suggested a notification against every workspace update:
> 
> I envisioned a small popup at bottom corner Moonshine (like we use to see in Visual Code Editor), mentioning that the active workspace updated (on project open/close), which will also have an Undo button; User can choose to do nothing to that popup, the poup will disappear after a few seconds. If user choose to undo the recent update, Moonshine should update the workspace data accordingly.

I'm against any abrupt notification when I'm opening/closing project. What do you mean popup ? To me popup needs interaction. - This is again problem with our notification system which is based on popups, instead some fade away type of notifications. - If that what you mean without user interaction - it can be. If you go in that direction it should be implemented in a way that anyone can use it.

**Comment by piotrzarzycki21** [comment] 2020-07-08 08:39
> * Since the design enforce auto-update-self (upon project open/close), user may mistakenly close one or multiple projects during a session, which will also got updated to the workspace data

I would not bother about that at all. User get used to the way how it is working.

**Comment by rat-moonshine** [comment] 2020-07-13 06:45
Yeah, I like @JoelProminic suggestion, that is interesting. I'll see how I can spend time on this.

**Comment by rat-moonshine** [comment] 2020-09-23 11:00
This issue is now ready for the initial tests at: https://bamboo.prominic.net/browse/MS-MGOBB.

A new menu group named 'Workspace' now introduced under 'File':
![image](https://user-images.githubusercontent.com/24370870/94003885-7b70f980-fdb9-11ea-9663-9f06382f14b7.png)

Available options are:
- Save As New Workspace
- Create New Workspace
- Load From Workspace

**Comment by JoelProminic** [comment] 2020-09-23 17:39
The basic functionality of the workspaces interface seems good in my quick test.  However, I noticed long waits with this build of Moonshine when I start Moonshine with MoonshineDESKTOPevolved and MoonshineSharedCore open, and if I open a workspace that contains those two projects.  I see a the OS spinning icon for 30+ seconds at these steps.

**Comment by rat-moonshine** [comment] 2020-09-24 06:29
> I noticed long waits with this build of Moonshine when I start Moonshine with MoonshineDESKTOPevolved and MoonshineSharedCore open, and if I open a workspace that contains those two projects. I see a the OS spinning icon for 30+ seconds at these steps.

I think this is the same (language server or something) delay issue we noticed before. 

Tested with stable v3.0.0 on my macOS, opening the said two projects individually took me this amount of time:

MoonshineDESKTOP: 35 seconds
MoonshineSharedCore: 35 seconds

Opening the Moonshine with the above two projects opened, took me: 1:21 minutes.

I believe these remain the same with the newer builds. For note, when a workspace changed, it reopens each project from its list individually, so I won't surprise if I witness 1+ minutes to reopen MoonshineDESKTOP and MoonshineSharedCore during this event.

**Comment by JoelProminic** [comment] 2020-09-30 16:58
This was working great in my initial testing, but I'm concerned that the behavior will be confusing in practical use.   Once we have released 3.0.0, we should merge this and let the developers start experimenting with this.

**Comment by JoelProminic** [comment] 2020-11-18 17:56
Now that 3.0.0 is release, we should get this merged so that everyone can start testing with practical examples.

**Comment by rat-moonshine** [comment] 2020-11-19 05:06
This issue is now merged into the 'master', and ready for tests.

**Comment by piotrzarzycki21** [comment] 2020-11-19 08:54
> This issue is now merged into the 'master', and ready for tests.

@rat-moonshine Please whenever you merge stuff to master always make sure that bamboo has started - if not start yourself. - Right now it's not building stuff ,cause I don't see nightly update

**Comment by rat-moonshine** [comment] 2020-11-19 08:59
The Bamboo build system appears to be stuck, unfortunately; if you are looking for the Windows build only. You can try the macOS build for now until Joel restarts the Windows system.

**Comment by piotrzarzycki21** [comment] 2020-11-19 09:02
I'm daily using Windows that's why it is more important to me having that. I will wait.

**Comment by JoelProminic** [comment] 2020-11-19 20:34
The Windows build is working now.

Moonshine should automatically save the current open projects in the "IDE-Default" workspace on startup if there are no existing workspaces.  However, I saw in my testing that this did not trigger if the user did not have any open projects.  In this case, the open projects would be closed and would be recoverable when the user first creates a new workspace.

**Comment by rat-moonshine** [comment] 2020-11-20 07:17
Unlike in macOS, I was able to reproduce no-default workspace label in the workspace-dropdown on Windows. This problem is now fixed. During my tests I tried to ensure the following things:

1. A fresh installation of Moonshine always shows "IDE-Default" as the default workspace to its dropdown
2. Any previously opened project(s) automatically adds to "IDE-Default" workspace even there was no previous workspace data; This would prevent any chance of loss of opened-projects data in case of switching to a different workspace
3. Parity tests to ensure no-error thrown during new workspace creation and switching

**Comment by piotrzarzycki21** [comment] 2020-11-20 08:03
@rat-moonshine Where can I find information which workspace do I currently use ?

**Comment by rat-moonshine** [comment] 2020-11-20 09:33
> @rat-moonshine Where can I find information which workspace do I currently use ?

Currently, there is no obvious visual labeling on the currently selected workspace; One can open `File > Workspace > Load Workspace` to see the currently selected one. Do you prefer and suggest any place where the selected workspace labeling can be done?

Additionally, I'm working on some fixes and commit in an hour.

**Comment by piotrzarzycki21** [comment] 2020-11-20 09:45
It definitely has to be such things. Maybe in the title bar ? I need to think about that - if you come with something do not wait for me.

**Comment by rat-moonshine** [comment] 2020-11-20 09:55
Okay. I have committed the fix that I was working on. You can give a test with a new installer possibly generates in half-hour from now.

I shall discuss with @JoelProminic if he has any suggestion where we can put a label of the currently selected workspace.

**Comment by piotrzarzycki21** [comment] 2020-11-20 11:45
Another question - is there anywhere in the settings list of workspaces ?

**Comment by piotrzarzycki21** [comment] 2020-11-20 11:46
In my opinion we should change "Load from Workspace" to "Switch Workspace" -> It could display list of workspace as it is now.

**Comment by rat-moonshine** [comment] 2020-11-23 05:09
> Another question - is there anywhere in the settings list of workspaces ?

At this moment there's none. I was in conversation with @JoelProminic on how worthy to have a dedicated section for this in Settings; We mostly wanted this feature to be simpler.

> In my opinion we should change "Load from Workspace" to "Switch Workspace" -> It could display list of workspace as it is now.

In my opinion, Switch/Switching is more of a technical term. When the current label is more of a general English. I'd prefer to have the terminologies in menus more in general English. Saying so, I'm open to the suggestion for any other alternatives.

**Comment by piotrzarzycki21** [comment] 2020-11-23 10:23
> In my opinion, Switch/Switching is more of a technical term. When the current label is more of a general English. I'd prefer to have the terminologies in menus more in general English. Saying so, I'm open to the suggestion for any other alternatives.

Well for whom we are working on that IDE ? :) Have you ever saw Load from Workspace anywhere ? When I have seen first time menu to search how to switch between workspace - I didn't click into that, I was searching more and lost couple of minutes.

**Comment by piotrzarzycki21** [comment] 2020-11-23 10:24
> At this moment there's none. I was in conversation with @JoelProminic on how worthy to have a dedicated section for this in Settings; We mostly wanted this feature to be simpler.

I can agree on not having workspaces list, but info about what workspace we ware currently in is essential, so talk with Joel about that today.

**Comment by rat-moonshine** [comment] 2020-11-23 10:49
> > In my opinion, Switch/Switching is more of a technical term. When the current label is more of a general English. I'd prefer to have the terminologies in menus more in general English. Saying so, I'm open to the suggestion for any other alternatives.
> 
> Well for whom we are working on that IDE ? :) Have you ever saw Load from Workspace anywhere ? When I have seen first time menu to search how to switch between workspace - I didn't click into that, I was searching more and lost couple of minutes.

I still prefer the term to menu options to be in general English. I'm fine if we want to change from 'Load from Workspace' to something else, though.

**Comment by JoelProminic** [comment] 2020-11-23 22:18
"Load from Workspace" doesn't sound right to me, so I was meaning to think of a better name for.   "Load Workspace" would be fine, but I think "Switch Workspace" is more clear (and not too technical).   Rather than loading the projects from a workspace, we are switching the loaded projects and tracking the opened projects on a different workspace.

Could we put the current workspace name in the Projects sidebar header?   I would change the text color or formatting so it stands out less than the "Projects" label.  We could consider adding quick buttons for the workspace actions here, but that may take up too much space.:
![image](https://user-images.githubusercontent.com/24532731/100021400-087b0380-2da7-11eb-9f60-fa5b71fc344e.png)

Other options:
- As part of the application name.  I fear that this will be unclear (Moonshine 3.1.0 - IDE-Default), or to wordy (Moonshine 3.1.0 - Workspace:  IDE-Default)
- As part of the footer.  We should include the "Workspace:   " prefix here to avoid confusion.  This could eat to the space available for the status bar.
- In the first "row" of the Projects sidebar.  This would be similar to my suggestion above, but we would have more space available.

@piotrzarzycki21 is this working well for your regular tasks?  I'm concerned that it will be too easily to close all of the open projects and open a different set of projects, making the current workspace invalid for its intended purpose.

**Comment by rat-moonshine** [comment] 2020-11-24 05:55
From the given options for possible placement of workspace label/name, I think it'd be less complicated (code-aspect) to put this on sidebar header than the other options:

![image](https://user-images.githubusercontent.com/24370870/100054195-9c9ca780-2e47-11eb-97e8-fcc2c2cad13a.png)

**Comment by rat-moonshine** [comment] 2020-11-24 10:32
Although, I wanted to retain the word "Workspace:" in the UI it seems to take lots of static space. I think the following looks slimmer and serve the purpose:

![image](https://user-images.githubusercontent.com/24370870/100082590-6fafbb00-2e6e-11eb-985d-12ec7db678d6.png)

The "Load from Workspace" label also replaced with "Switch Workspace".

**Comment by piotrzarzycki21** [comment] 2020-11-24 15:47
> @piotrzarzycki21 is this working well for your regular tasks? I'm concerned that it will be too easily to close all of the open projects and open a different set of projects, making the current workspace invalid for its intended purpose.

I share that concerns, but I would prefer stay for now as is. If that would be the problem we will have to think that removing something from workspace shouldn't happen when project is closed, but rather under explicit demand. Let's see how it goes. We can close issue and move forward.

**Comment by JoelProminic** [comment] 2020-11-24 18:57
There was a bug with the Projects header which causes the "Projects" text to display differently (smaller, bold, different font?).

![image](https://user-images.githubusercontent.com/24532731/100139091-94973480-2e54-11eb-8cce-602e99485c27.png)

As I feared, leaving out "Workspace:  " is confusing for users who aren't aware of the new workspace feature:  https://github.com/prominic/Moonshine-IDE/issues/468#issuecomment-733134232

Some options we discussed:
- Change the name of the default workspace to "Default-Workspace"
- Change the title of this sidebar from "Projects (%workspace%)" to "Workspace: %workspace%".  

Do you have any preference for this, @piotrzarzycki21?

**Comment by piotrzarzycki21** [comment] 2020-11-25 10:06
> * Change the title of this sidebar from "Projects (%workspace%)" to "Workspace: %workspace%".

I would be in favor of this approach and I see @rat-moonshine did the changes.

**Comment by rat-moonshine** [comment] 2020-11-26 06:19
For some times @JoelProminic was reporting an error during a new workspace creation or switching to another:

```
: Error #1009: Cannot access a property or method of a null object reference.
: TypeError: Error #1009: Cannot access a property or method of a null object reference.
: 	at actionScripts.plugin.workspace::WorkspacePlugin/closeAllEditorAsync()
:       [/Users/devsena/ProminicGITBranch/Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/plugin/workspace/WorkspacePlugin.as:307]
: 	at actionScripts.plugin.workspace::WorkspacePlugin/handleNewWorkspaceEvent()[/Users/devsena/ProminicGITBranch/Moonshine-IDE/ide/MoonshineSharedCore/src/actionScripts/plugin/workspace/WorkspacePlugin.as:179]
```

Unfortunately, I couldn't able to reproduce the error during my tests until yesterday when he shared his using shared-object file with me.

It appears that I mistakenly overlooked a scenario where a project object could be null, due to a missing or deleted project from the user's system which still has a reference in the workspace cookies. This scenario is handled now, and I couldn't able to reproduce any more error even using Joel's shared-object file.

@JoelProminic , please give some tests with the latest 'master' build.

**Comment by JoelProminic** [comment] 2020-12-01 16:32
@rat-moonshine clarified that the deleted or missing project entries in the workspace configuration will not be cleaned up automatically, but the code will catch exceptions for missing projects so that there are no errors in the UI.

I tested this with a deleted and moved project, and I didn't see any errors when switching to and from the updated workspace.

**Comment by JoelProminic** [comment] 2020-12-02 17:25
This seems to be working well now, so I'm closing the issue.

**Closed by JoelProminic** 2020-12-02 17:25 UTC
Labels: enhancement, test-ready
