### ISSUE TITLE
Browse Repositories on Subversion Checkout

### ISSUE THREAD

**Issue by JoelProminic** [prominic/Moonshine-IDE#502] opened 2019-04-02 17:34 UTC
@JustinProminic has been requesting updates to the SVN support to make it easier to browse repositories.  Here is an example of the behavior we would like to see:
1. The user clicks Subversion > Checkout
2. The user enters a base repository path.  There may be subprojects underneath this path
3. The user fills out the other credentials for the server and clicks Next
4. Moonshine shows a list of the directories in that repository.  The directory can be explored as a tree.
5. The user selects the directory they want to checkout.  By default, the original base directory should be selected
6. The user selects a target directory.  The filechooser should open to the last used directory.
7. The user changes the name for the project, if desired.  This should default to the name of the selected SVN directory
8. The user clicks Checkout
9. The user clicks Subversion > Checkout again.   The previously used repository URL is available in a dropdown or with auto-completion for quick selection.

This will make it easier for users to checkout multiple projects from the same repository (which is a requirement for Prominic).  However, it does add extra clicks for users that know the exact repository path they want.  If we find that the tree population is slow, we may want to add a method for users to do a quick checkout.

Here is a mockup to help explain what I have in mind.  We don't need to use this exact design.
![2019_04_02__SVN_Checkout](https://user-images.githubusercontent.com/24532731/55423400-6eb47200-5543-11e9-8442-6a260fb5dc40.png)

You can list the remote files for SVN like this:

    $ svn ls --depth immediates <url>
    branches/
    tags/
    trunk/

Note that I used "--depth immediates" to only show one level of files.  Once a folder is expanded, you can run the command again to show its children.    It is also possible to use "--depth infinity" to show all of the nested files, but this will be impractical for a large repository.

Since Git doesn't have a build-in method to browse files (they can be browsed by HTML or by the GitHub API, but these will not be available for all Git projects), this update won't make sense for Git.

This is an early design, so I welcome comments or concerns.  Here is my mockup file, if you want to tweak the design:
[2019_04_02__SVN_Checkout.bmpr.zip](https://github.com/prominic/Moonshine-IDE/files/3035214/2019_04_02__SVN_Checkout.bmpr.zip)

**Comment by rat-moonshine** [comment] 2019-04-03 06:24
With an addition, I would like to have a restructure to the current SVN plugin-codes in Moonshine. It's been done long time back and I don't like its structure; However, I'm not sure if spending time on that would be a good idea at this moment.

**Comment by rat-moonshine** [comment] 2019-04-05 12:10
![image](https://user-images.githubusercontent.com/24370870/55626387-0aa2df80-57c9-11e9-82ee-6fb302c09bed.png)

All the above should work now. 

Few points to be noted:

1. Git _type_ option disabled in "Add Repository" window - we'll enable it after v2.2
2. At this moment, one folder-list fetching at a time from remote (in browse repository); This is due to the current codes structure in SVN classes, multiple calls at a time requires queued execution but this requires me to change the current structure; I didn't modified the current structure much as this would cost me additional time
3. Git checkout window also updated to accept target folder name

**Comment by piotrzarzycki21** [comment] 2019-04-05 15:15
After update I got error cause we have several type of projects not only AS3 anymore:
![otherprojects](https://user-images.githubusercontent.com/24554795/55637928-615aea00-57c6-11e9-9083-77dbe398dada.png)

**Comment by rat-moonshine** [comment] 2019-04-05 15:17
> 
> 
> After update I got error cause we have several type of projects not only AS3 anymore:
> ![otherprojects](https://user-images.githubusercontent.com/24554795/55637928-615aea00-57c6-11e9-9083-77dbe398dada.png)

We probably want to move the `menuType` to base project VO, I guess that is avail for all project types.

**Comment by JoelProminic** [comment] 2019-04-05 23:05
The basic functionality for the SVN repository browser seems to be working well. I was able to test this with single and multiple projects.

A couple thoughts:
- Since the loaded tree nodes are cached (which is good), it would be helpful to have a button or menu action to refresh a node, so that the user can see updates without restarting Moonshine
- A "Collapse All" button may be useful, for resetting the tree if the user expands a lot of entries.  I'm not sure where this would fit well in the current interface, though.

**Comment by rat-moonshine** [comment] 2019-04-08 07:14
- Refresh and Collapse All option added to the items' context menu
- Busy indicator now showing against item that is currently updating
- Fix: List fetch against folder containing no file, not releasing busy indicator from the UI

**Comment by rat-moonshine** [comment] 2019-04-11 11:47
Following are some of the updates after our last night meeting:

1. Title fix to file-browsing window after parent directory selection (title referring for 'Git')
2. User name was not populating to the authentication window when you're in middle of repository browsing and for some reason saved SVN authentication removed
3. Temporary save option label in authentication window changed to "Save until Moonshine exits" (let me know if we need any amendment)
4. This fix detailed in **Temporary Saved Authentication** section below

### Temporary Saved Authentication

I have noticed following problems during my tests today between authentication to SVN and removing authentication from SVN software/keychain:
- User do not have any saved authentication to SVN software
- User saved a repository with a user name 'abc'
- Upon browsing the repository Moonshine asks for the authentication
- Authentication window opens with user name pre-populated with 'abc'
- User completes the authentication with user name 'xyz'
- User choose to save the authentication for the current Moonshine session
- During same repository browsing session at a time saved authentication information removed from SVN software/keychain
- On continuing browsing the repository Moonshine re-prompt to authenticate
- Authentication window opened with user name pre-populated with 'abc' **[BUG]**
- User re-authenticated with user name 'xyz' and choose to save the information for current Moonshine session
- Saved authentication information removed again from SVN software/keychain
- Moonshine again prompt to authenticate upon repository browsing attempt **[BUG]** (since auth information choose to save for Moonshine session, Moonshine was suppose to use that information instead asking again)

After taking some measure, following is the current expected results:
- User do not have any saved authentication to SVN software
- User saved a repository with a user name 'abc'
- Upon browsing the repository Moonshine asks for the authentication
- Authentication window opens with user name pre-populated with 'abc'
- User completes the authentication with user name 'xyz'
- User choose to save the authentication for the current Moonshine _session_
- During same repository browsing session at a time saved authentication information removed from SVN software/keychain
- On continuing browsing the repository Moonshine re-authenticate with _session_ saved auth information against the repository

On a more detailed situation, we currently have no functionality or option to remove that _session_-saved auth information against the repository, if user want.

**Comment by JoelProminic** [comment] 2019-04-11 23:10
I'm not sure if this is related to the recent Subversion updates, but I noticed that I get an error  on Moonshine startup if I have an SVN project open:
1. (optional) Close all other projects
2. Checkout a project from SVN in Moonshine
3. Restart Moonshine.  BUG:  I see this error on the console.

    : Error #1009
    : TypeError: Error #1009
    : 	at actionScripts.managers::DetectionManager/stepA_checkMoonshineInternal()
    : 	at actionScripts.managers::DetectionManager/startDetectionProcess()
    : 	at actionScripts.managers::DetectionManager/detect()
    : 	at MethodInfo-29748()
    : 	at SetIntervalTimer/onTimer()
    : 	at flash.utils::Timer/tick()
    :
    : Click here to Report a Bug

**Comment by rat-moonshine** [comment] 2019-04-12 05:55
> I'm not sure if this is related to the recent Subversion updates, but I noticed that I get an error on Moonshine startup if I have an SVN project open:

The error description says it has been thrown from Moonshine SDK Installer shared library project during startup detection process. There were no recent changes to these section. 

I have tried to reproduce by above steps, but I couldn't able to reproduce in my initial tests in either platform. I'll keep an eye to have an error fire like this.

**Comment by rat-moonshine** [comment] 2019-04-12 06:40
Okay. I haven't noticed this before, but I see there are recent changes to the `DetectionManager` and MSDKI library project towards #453 fix. The only thing related to `PLAYERGLOBAL_HOME` check in `stepA_checkMoonshineInteral()` method is [this](https://github.com/prominic/Moonshine-SDK-Installer/blob/master/InstallerSharedCore/src/actionScripts/managers/DetectionManager.as#L81). Do you think about any possible break in this step @piotrzarzycki21 ? 

By the way, I'll change the execution from stepA_checkMoonshineInternal() to stepB_checkDefaultInstallLocation(), because that is the place for checking Windows' environment variable. The execution also happens on each iteration of loop, which probably I want to change.

I couldn't able to reproduce the error @JoelProminic reported in my initial test on macOS. Joel, can you confirm if this reproducible at you every time, or any certain project checkout cause this problem?

**Comment by piotrzarzycki21** [comment] 2019-04-12 07:33
I believe @JoelProminic didn't have luck with downloading enough updated version of Moonshine. First I have committed changes which are adding detection of PLAYERGLOBAL_HOME. Bamboo pickup that and probably Joel download that version - about one hour later I discovered above problem and pushes the fix.

**Comment by rat-moonshine** [comment] 2019-04-12 11:40
Here are the rest of the updates from our last discussion (with @JoelProminic ),

1. "Add Repository" path insertion updated with suggested RegExp
2. Trailing slash will now remove during repository save
3. Commit and Update commands are now using (if any)saved authentication to the repository item, details are in **Commit and Update updates** section below

### Commit and Update updates

Commit and Update commands are now executing `svn info` to gather information about the project's repository root. Once the repository-root information gather, Moonshine checks through the saved repository item list to match the repository-root URL, and takes the first instance of the match. 

To do this effectively, updated "Add Repository" window now checks for duplicate URL entry in the existing "Manage Repository" list at the time of submission. If duplicate found, it'll alert and no new entry will be added. Joel, if you have duplicate entries in your history for "Manage Repositories", you might want to remove them, or `svn info` post-process will anyway take the first instance of the URL/repository-root match. 

Following are my test procedures on Windows after the implementation:
- Opened Moonshine with a previously opened SVN project
- Made sure not authentication data to keychain
- `SVN -> Update` shows authentication window
- Authentication done without selecting "Save until Moonshine exits" option
- Update operation completed
- Removed authentication data from keychain
- `SVN -> Update` shows authentication window
- This time authentication done by selecting "Save until Moonshine exits" option
- Removed authentication data from keychain
- `SVN -> Update` operation completed by using temporary saved authentication data
- `SVN -> Commit` operation completed by using temporary saved authentication data

The above test cases also true if starts with Commit and then test Update.

**Comment by JoelProminic** [comment] 2019-04-17 22:44
One case that is not covered by the above logic:
1. Add a repository entry like https://.../repository/trunk
2. Browse the respository.  Save the credentials when prompted
3. Checkout a directory from this repository
4. Clear the SVN credentials
5. Try an Update or Commit.  The username is not populated because there is no repository entry for the root repository URL:  https://.../repository

If we want to cover this case, I think we would need to automatically correct the base repository URL after checking out a project.  So:
1. Add a repository entry like https://.../repository/trunk
2. Browse the respository.  Save the credentials when prompted
3. Checkout a directory from this repository
4. Moonshine detects that the root repository URL is https://.../repository and updates the repository entry to match

Note that the updated name could conflict with an existing repository.

**Comment by JoelProminic** [comment] 2019-04-17 22:44
In practical terms, the current implementation is probably sufficient for release:
- The recommended SVN applications will automatically save the credentials.
- Even if the credentials are cleared, Moonshine will prompt the user to enter the credentials, so they can still access their projects.

Unless you see a common case that would be a problem with the current status, I think it is fine to release v2.1.0, and improve this logic later if desired.

**Comment by rat-moonshine** [comment] 2019-04-18 04:36
Since the new logic implementation may involve many possible test cases (those we already know and those we haven't thought of at this moment), and possible also bug-fixes after that, if we want a release now then perhaps it'd be better to keep this particular implementation for later.

We can track this tuneup as a separate issue, though.

**Comment by piotrzarzycki21** [comment] 2019-04-18 08:04
I'm closing this one. Open separate issue for specific cases.

**Closed by piotrzarzycki21** 2019-04-18 08:04 UTC
Labels: enhancement
