### ISSUE TITLE
Some Minor Issues

### ISSUE THREAD

**Issue by doug777** [prominic/Moonshine-IDE#17] opened 2017-09-19 03:34 UTC
After using Moonshine for a few days, a few things I've noticed.

1. If my project called Test is open and I then select Open/Import Flex Project and try to open project called Test2, it won't open and the bottom panel shows Project already open - ignoring request. If Test2 is already open however, then Test will open correctly.

2. Suggest set a timer (30 seconds is probably more than enough) on the mouse-over pop-ups. Sometimes they get orphaned and I have to close the IDE and re-open to remove them.

3. I like to work in a window not full screen but bigger than the default start window. Either store the window size after resizing or add a line in global settings for start window size.

Overall it's an excellent IDE as far as it goes. Looking forward to next update. But brilliant job so far. I really like using it - just wish I could do some build tests.

Doug

**Comment by rat-moonshine** [comment] 2017-09-19 05:45
Doug, thank you. 

1. Can you ensure the 'Test2' project is not a sub-directory of 'Test' project. That is not a valid project structure to Moonshine, and it suppose to report you by the kind of message you described. Make sure your projects holds individual paths.

2. Can you give some more details on the problem? Maybe a screen recording would help, too.

3. Starts from (upcoming) 1.6.0 Moonshine, it suppose to preserve your last opened panels' state. It also suppose to preserve application's maximizing state; we shall take a look to keep the resized window size as well.

**Comment by rat-moonshine** [comment] 2017-09-19 07:51
We've added the application size preservation on next 1.6.0 release. 

Thanks!

**Comment by rat-moonshine** [comment] 2017-09-19 15:54
> If my project called Test is open and I then select Open/Import Flex Project and try to open project called Test2, it won't open and the bottom panel shows Project already open - ignoring request. If Test2 is already open however, then Test will open correctly.

We able to reproduce the problem with further tests. Fix coming shortly. Thank you!

**Comment by rat-moonshine** [comment] 2017-09-20 07:42
#2 seems a legit issue and I'm opening a new issue tracker on this - https://github.com/prominic/Moonshine-IDE/issues/19. Since the other reported issues are solved, I'm closing this, and transferring to next release sprint.

**Closed by rat-moonshine** 2017-09-20 07:42 UTC
Labels: bug, enhancement
