### ISSUE TITLE
Replacing Windows packaging software with NSIS

### ISSUE THREAD

**Issue by rat-moonshine** [prominic/Moonshine-IDE#713] opened 2020-07-14 04:31 UTC
This issue is a subset of #712 .

@joshtynjala suggested a few free alternatives to replace Adobe's proprietary packaging software with - [NSIS](https://nsis.sourceforge.io/Docs/) or [Inno Setup](https://jrsoftware.org/ishelp/index.php?topic=compilercmdline).

Josh already has a satisfactory experience with NSIS to package his a few AIR applications in past, we think this worth a try to investigate for Moonshine, too.

Here's the .nsi file he's been using to Feathers SDK Manager packaging:
https://github.com/BowlerHatLLC/feathersui-starling-sdk-manager/blob/master/nsis/feathers-sdk-manager.nsi

NSIS documentation:
https://nsis.sourceforge.io/Docs/

The original discussions on this can read from [here](https://github.com/prominic/Moonshine-IDE/issues/712#issuecomment-656804480).

**Comment by rat-moonshine** [comment] 2020-07-14 06:22
The initial sign looks great. I haven't noticed any delay during installer open, installation (including 'elements' folder) or the actual executable run. 

If this goes good, then we probably re-think on Moonshine SDK Installer Windows distribution as well.

**Comment by rat-moonshine** [comment] 2020-07-14 15:43
@joshtynjala what is the best way to have the `signtool` installed? I remember I had the exe downloaded long-back, but I don't see that file anymore now. Through different articles, I see the signtool installer can be acquired by downloading Windows 10 SDK but I hesitated to download a complete SDK for this, instead I was hoping any other source to have the installer downloaded.

**Comment by joshtynjala** [comment] 2020-07-14 16:19
As I recall, I've always installed the Windows SDK to get signtool. I believe that I once looked for alternative ways to download it from Microsoft, but I was not successful.

**Comment by rat-moonshine** [comment] 2020-07-15 10:45
@Aszusz @JoelProminic please give a try to this new installer if this slows your operation anymore:
https://app.box.com/s/r6ibp9dfvq53e3t5r3k7syonbz2ra88e

A few things to note:

1. Since a completely separate packager, we have no liberty to distribute 64-bit of Moonshine, previously it wasn't possible keeping into the Adobe's proprietary one. The above packager will install you a 64-bit of Moonshine. I'm not very confident but this might cause any trouble to the 32-bit OS holders. We need to consider if we want to distribute a separate 32-bit Moonshine distribution for those users or continue to distribute as 32-bit
2. Since 64-bit compilation, we needed to upgrade the AIR SDK use >28. Currently, it is using 32

Please, check.

**Comment by JoelProminic** [comment] 2020-07-15 19:38
The new installer was much faster for me, especially for the initial launch response.

I was curious how this would interact with the old Moonshine installations.   Since the binary has changed from 32-bit to 64-bit, this installs in a different location.  However, I see that this also results in having two Moonshine entries in the Start menu:
![image](https://user-images.githubusercontent.com/24532731/87588027-9d0e8000-c6a8-11ea-9be0-ba7f09395d3e.png)

We need to clean this up so that the user is not accidentally opening an old build of Moonshine.   If we can't remove the old Start menu entry, we may need to change the name for the new application.

**Comment by Aszusz** [comment] 2020-07-15 23:36
Hi @rat-moonshine,
The new installer works instantly for me, there's no reason anymore to time it with a stopwatch.

**Comment by Aszusz** [comment] 2020-07-15 23:38
I noticed we're still using an old icon. We can think about replacing it with the new one prepared by Josh.

**Comment by piotrzarzycki21** [comment] 2020-07-16 08:23
I think what @JoelProminic is describing is a serious issue. Thinking about that we could go with following scenario:

1. We can support both 32bit and 64bit version of Moonshine. It is just a matter of preparation different bamboo build
2. In release notes we should describe that we have started to support 64bit Moonshine, so before installation we recommending uninstall previous version.

Thoughts ?

**Comment by piotrzarzycki21** [comment] 2020-07-16 08:23
> I noticed we're still using an old icon. We can think about replacing it with the new one prepared by Josh.

+1 for that

**Comment by rat-moonshine** [comment] 2020-07-16 08:39
Between choosing 32 and 64 Bit, I'm still waiting to listen Justin's thought on this. Based on that we can decide our course of action.

If we go to support both 32 and 64 Bit (through different distribution), then perhaps some changes in executable label make sense; One can install both the version in the same x64 system.

**Comment by piotrzarzycki21** [comment] 2020-07-16 08:42
> If we go to support both 32 and 64 Bit (through different distribution), then perhaps some changes in executable label make sense; One can install both the version in the same x64 system.

If you mean notify user what version Moonshine is being used by some label - that is good idea.

**Comment by rat-moonshine** [comment] 2020-07-16 09:58
I'm not sure what you meant by 'notify' but yes it is to give users an easy understanding by different shortcuts to the application. We can have shortcuts in Start Menu (consider the image Joel reported) where one can label something like 'Moonshine x86' and another 'Moonshine x64'; That would give the user a clear understanding which variant s/he is using.

**Comment by joshtynjala** [comment] 2020-07-16 16:46
In NSIS, you can detect the uninstaller for an app like this:

```
ReadRegStr $R0 HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\com.example.MyApp" \
		"UninstallString"
```

I wonder if we can look at the file name (or parts of the full path) to detect if it's the old AIR uninstaller, and then offer to run it before continuing. If we detect the NSIS uninstaller (or no uninstaller), we can skip that part and install normally.

**Comment by rat-moonshine** [comment] 2020-07-17 05:33
I think that is considerable if we chose to support only 64-bit and offering an uninstallation of 32-bit(existing) during installation, make sense.

My registry may have stored now different properties since the NSIS-version installation. I tried to give a fresh regular Moonshine installation and the registry now looks like this:

![image](https://user-images.githubusercontent.com/24370870/87751932-c9e3a400-c81c-11ea-9245-f1e1eb188e53.png)

"InstallLocation" probably something that can give us a hint if user already has a 32-bit installation. I wonder what could be the uninstaller-path to this Adobe's installation (?) ("QuietUninstallString" probably something created by the NSIS-installation)

**Comment by piotrzarzycki21** [comment] 2020-07-17 06:41
@rat-moonshine regardless of our direction on that, you could start working on preparing installer for SDK Installer. I would definitely wanted to see ability to send user new nightly build and install it properly. - Of course the old way how it is done should work as well.

**Comment by rat-moonshine** [comment] 2020-07-17 07:46
I have that plan on my radar. However, continue supporting the old way would be an overkill. I'm not going to support that anymore once new installer in place.

**Comment by rat-moonshine** [comment] 2020-07-17 12:36
Requisite softwares added to Windows 10 Bamboo build system.

**Comment by rat-moonshine** [comment] 2020-07-23 09:36
I have updated the Ant build script to read from Bamboo Capabilities to use NSIS and Signtool paths. While testing this on branch build Windows, I see the Signtool path is pointing to the executable instead of the directory:

![image](https://user-images.githubusercontent.com/24370870/88271892-7fb76280-ccf5-11ea-8a40-ba11432c5d88.png)

Ant build script updated to use the executable by itself followed by the directory-path, i.e.
`${SIGNTOOL_HOME}/signtool.exe`

The same usage also followed for the NSIS. @JoelProminic can you please update the Signtool path in Capabilities to use the directory only - `C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64` (?)

**Comment by rat-moonshine** [comment] 2020-07-23 10:48
I have updated the branch build-plan to use AIR 30.0 (to support 64-bit Windows) and this will be common for both OSX and Windows build in the future.

**Comment by piotrzarzycki21** [comment] 2020-07-23 10:51
> I have updated the branch build-plan to use AIR 30.0 (to support 64-bit Windows) and this (or higher) will be common for both OSX and Windows build in the future.

Why not to jump to the latest official release of AIR 32 ?

**Comment by piotrzarzycki21** [comment] 2020-07-23 10:51
Could you send me a link so I could download results ? Will it be available for me ?

**Comment by rat-moonshine** [comment] 2020-07-23 10:52
) For now, we have installed upto 30.

**Comment by rat-moonshine** [comment] 2020-07-23 10:56
Unlike production, branch build not deploys anywhere but Bamboo server only. I need to test the macOS version since this AIR version update to ensure the using ANE does not fail.

**Comment by rat-moonshine** [comment] 2020-07-24 07:39
Incrementing AIR version doesn't seem any negative effect on using ANE. So we should be fine with the incrementation.

**Comment by piotrzarzycki21** [comment] 2020-07-24 07:45
> Incrementing AIR version doesn't seem any negative effect on existing ANE. So we should be fine with the incrementation.

If that's the case, jump to 32.

**Comment by rat-moonshine** [comment] 2020-07-24 07:49
Yeah, I was thinking about that.. I need to have some time to have that installed in both the build systems.

**Comment by piotrzarzycki21** [comment] 2020-07-24 09:51
There is significant increase of speed on Windows for Moonshine 64bit - starting from launching and general usage. I have no doubts right now that we should do the switch as soon as it is possible and forgot about 32bit. :)

**Comment by rat-moonshine** [comment] 2020-07-24 10:36
That sounds great! 

We need to do some investigation on the dual-installation solution suggested by Josh [here](https://github.com/prominic/Moonshine-IDE/issues/713#issuecomment-659535456), this seems to be doable but I need to check if any sandbox issue raise during the procedure.

**Comment by piotrzarzycki21** [comment] 2020-07-24 10:37
> That sounds great!
> 
> We need to do some investigation on the dual-installation solution suggested by Josh [here](https://github.com/prominic/Moonshine-IDE/issues/713#issuecomment-659535456), this seems to be doable but I need to check if any sandbox issue raise during the procedure.

The best in my opinion is suggest people in release notes that they should uninstall 32bit version.

**Comment by rat-moonshine** [comment] 2020-07-28 13:26
@joshtynjala As I was testing this possibly a worthy solution to uninstall the 32-Bit version of Moonshine automatically (if exists) without putting a burden on the users; Of course, we'll notify the activity to the user. 

In my tests, I found I can uninstall a different location's uninstaller (which is odd) without getting into a sandbox. Good for us.

My idea to test the 'uninstallString' value of installed Moonshine's if a value like "(x86)" is present. I was looking into how to use [strContains](https://nsis.sourceforge.io/StrContains) or [indexOf](https://nsis.sourceforge.io/IndexOf_%26_RIndexOf:_Find_index_of_character_in_string) properties in NSIS. Both the API calls in a way like this,

`strContains` calls in this way,
`${StrContains} $0 "Dirt" "Dirty deeds done dirt cheap"`

Even after struggling quite some time how to include/define `strContains` to the file, so far it failed. The compilation failed with `Invalid command: "${StrContains}"`.

Do you have any knowledge of how to use/define the above in the file?

I also tried to `!include "StrContains.nsh"` from some old code-articles - but this usage may be deprecated.

**Comment by rat-moonshine** [comment] 2020-07-28 16:02
Some updates here. When I was discussing this with @JoelProminic he questioned if we need to add the complete "Function Code" in our script file, from [here](https://nsis.sourceforge.io/StrContains). When I tried this previously, somehow this raised error during compilation. When I re-tried this now, it worked. 

It turns out that we require to add the complete "Function Code" for the method in our script file, unlike the way we include/define an API to use in a file.

`${StrContains}` calls now working well in our script file.

**Comment by rat-moonshine** [comment] 2020-07-29 07:28
Okay. I have adjusted the installer script to offer the user to uninstall the 32-bit (if exists) or continue to keep both the variants; The alert will look like this, we can change the texts if requires:

![image](https://user-images.githubusercontent.com/24370870/88769206-c4317b00-d199-11ea-93dc-d6234164ae02.png)

**Comment by rat-moonshine** [comment] 2020-07-31 06:51
![image](https://user-images.githubusercontent.com/24370870/89008433-5071a880-d328-11ea-9968-f2e07220fede.png)

**Comment by JoelProminic** [comment] 2020-07-31 17:20
For the test matrix, I'm looking for a more detailed breakdown of the cases, along with whether you have tested and confirmed the case.   Here is what I came up with during the meeting today, with the cases that I have tested marked.

### 1. Moonshine is running:

Test | Expected Result | Actual
-----|-----------------|-------
No Running instance | Prompt not displayed | 
Running 32-bit Instance | Prompt displayed, instance killed by Yes | Confirmed
Running 64-bit Instance | Prompt displayed, instance killed by Yes | Confirmed
Prompt appears - click No | Installation canceled, Moonshine stays running | Confirmed


### 2. 32-bit version

Test | Expected Result | Actual
-----|-----------------|-------
No 32-bit version | Prompt not shown | 
32-bit version only, choose Yes | 32-bit version uninstalled, continue installation | 
32-bit version only, choose No | 32-bit version remainins installed, continue installation | 
Both 64 and 32-bit versions, choose Yes | 32-bit version uninstalled, continue installation | BUG:  64-bit uninstaller called instead
Both 64 and 32-bit versions, choose No | 32-bit version remainins installed, continue installation | Confirmed



### 3. Previous Version

Test | Expected Result | Actual
-----|-----------------|-------
No previous install | Prompt not shown | 
32-bit install only | Prompt not shown | 
Same 64-bit version uninstalled previously | Prompt not shown | 
Later timestamp than installed | Prompt not shown | Confirmed
Earlier timestamp than installed | Prompt not shown | 
Same Timestamp, choose Yes | Show prompt, Moonshine starts | Confirmed
Same Timestamp, choose No | Show prompt, Uninstaller runs, Installer runs again | Confirmed
Same Timestamp, choose Cancel | Show prompt, Installer terminates |

### Additional Notes


Looking into the case with both a 32-bit version and a 64-bit version, I see in Add/Remove Programs that there is only one entry for Moonshine in this case.   Removing this application triggers the 64-bit uninstaller, and after the uninstaller runs, the 32-bit version still remains on the system.

Thinking about this further, I think it is a bad idea to let the user keep the 32-bit version, especially if the name is the same.  I'm thinking we should:
- Change the application name to something different like "Moonshine (64-bit)"
- Require the user to uninstall the 32-bit before installing the 64-bit version.  Note that this does not prevent the user from running an old 32-bit installer if they try to downgrade.

If we change the application name, will we still have the registry conflicts that are causing the above issue.  If not, then requiring an uninstall may not be necessary

I'd like to do a little cleanup on the prompt text once we finallize the logic.   Are we required to use Yes, No, and Cancel for the buttons?   I'd rather change the button names to be more descriptive so that the key is not required.

**Comment by rat-moonshine** [comment] 2020-08-03 05:14
> If we change the application name, will we still have the registry conflicts that are causing the above issue. If not, then requiring an uninstall may not be necessary

Giving some tests to above thought where executable names are different, installation locations and Start Menu shortcuts are different, but application-id remains the same. It turned out that the "Add/Remove Programs" window works on application-id rather than executable-name. The latter installation overrides former installation in "Add/Remove Programs" section and shows only entry. This option thus out of proposition now.

**Comment by rat-moonshine** [comment] 2020-08-03 05:52
Here's the updated prompt on enforcing the uninstallation of 32-bit before proceeding:

![image](https://user-images.githubusercontent.com/24370870/89150194-a12d0f80-d57b-11ea-970d-103b394232c0.png)

**Comment by rat-moonshine** [comment] 2020-08-03 06:43
The original [test-matrix](https://github.com/prominic/Moonshine-IDE/issues/713#issuecomment-667239462) will be updated addition of newer values as appropriate.

**Comment by rat-moonshine** [comment] 2020-08-03 10:15
I tried to sign an Uninstaller based on the example shown here - https://nsis.sourceforge.io/Signing_an_Uninstaller. Since the structure of the example, it turned out a bit difficult to fit in the current script-file structure. I spent some time figuring out how to fit the commands in current script-file, but mostly ended with unresolved errors. For now, I'm leaving this and keep the Uninstaller as it's provided by the installer-script itself. 

As the example seems to be created problem for others, some suggested to create an Uninstaller by a separate NSIS process, sign and attach into the targeted installer. This probably considerable if we really need this.

**Comment by rat-moonshine** [comment] 2020-08-13 05:23
This issue now merged into 'master'. 

I'm also proposing a re-versioning of the current milestone from [v2.7.0](https://github.com/prominic/Moonshine-IDE/milestone/21) to **v3.0.0**, based on the contents we shall going to have in next release. It's possible we may have one or two more issue/features added to this release, i.e. module-uspport. 

The quantity of features and their _types_ in next release, give us a good reason why it should be a major version.

**Comment by piotrzarzycki21** [comment] 2020-08-13 06:37
> This issue now merged into 'master'.

Please make sure that we can see build of [Moonshine SDK Installer](https://moonshine-ide.com/downloads/msdki/dev/windows/) and Moonshine itself [here](https://moonshine-ide.com/downloads/releases/dev/windows/).

**Comment by piotrzarzycki21** [comment] 2020-08-13 09:16
Close this issue once you will be sure that Bamboo is working and producing require artifacts.

**Comment by rat-moonshine** [comment] 2020-08-13 09:36
The deployment locations for Moonshine, should updated with newer builds now.

I shall keep this issue open for some time. The current Moonshine build still pointing to MSDKI's 'master' branch, I need to merge the NSIS-branch in Moonshine SDK Installer and update its Bamboo build plan; Once done Moonshine shall have update procedures to download Moonshine SDK Installer's NSIS version. We also needs to update the textual stuff in the installers.

**Comment by piotrzarzycki21** [comment] 2020-08-13 12:29
> I shall keep this issue open for some time. The current Moonshine build still pointing to MSDKI's 'master' branch, I need to merge the NSIS-branch of Moonshine SDK Installer and update its Bamboo build plan; Once done Moonshine shall have update procedures to download Moonshine SDK Installer's NSIS version. We also needs to update the textual stuff in the installers.

I still don't see Installer being build so I could download it.

**Comment by rat-moonshine** [comment] 2020-08-13 12:49
Okay. I see the [location](https://moonshine-ide.com/downloads/releases/dev/windows/) (if this where the nightly suppose to be deployed) have not updated after 10th August. I'm not very familiar with the deployment process. I'd request @JoelProminic to take a look if something is wrong, Bamboo completed its merged build however.

**Comment by JoelProminic** [comment] 2020-08-13 15:53
The installer EXE name changed from Moonshine.exe to Moonshine-2.7.0.exe.    I updated the build script to use a wildcard in this case, and now the build was deployed:
![image](https://user-images.githubusercontent.com/24532731/90157182-08ed1280-dd53-11ea-8844-8a9218576d70.png)

Do we need to rename the executable back to Moonshine.exe?   The Windows Nightly download link opens the directory rather than linking directly to Moonshine.exe, so this part will still work fine.

**Comment by piotrzarzycki21** [comment] 2020-08-13 17:24
I prefer to have version in name. @Aszusz any objections for that in connection to website?

**Comment by rat-moonshine** [comment] 2020-08-14 04:54
As I'm thinking, the above-screened section was supposed to be for the nightly builds only, a 'nightly' word perhaps make sense attached to the installer name to make clear it is nightly and not production or regular version.

I'll see what changes it may require to have in the build script to control that from Bamboo to produce between nightly and production. We are distributing installer with version number for release distribution, so that format is fine with us.

**Comment by piotrzarzycki21** [comment] 2020-08-14 10:50
I cannot run SDK Installer with Moonshine build **173**
![sdk_installer](https://user-images.githubusercontent.com/24554795/90242105-ad8f5300-de2c-11ea-8a84-1ec1948a384e.png)

**Comment by piotrzarzycki21** [comment] 2020-08-14 10:54
It is not a huge problem, cause I can run installer by double click on exe file, but just wanted to point out current state.

**Comment by rat-moonshine** [comment] 2020-08-14 11:26
Yeah, I'm aware of this... This because of the updater-XML which needs some adjustment to work with the latest Moonshine SDK Installer check/download process.

**Comment by Aszusz** [comment] 2020-08-18 14:33
Sorry for the late reply

> I prefer to have version in name. @Aszusz any objections for that in connection to website?

No problem, version numbers are fine.

> As I'm thinking, the above-screened section was supposed to be for the nightly builds only, a 'nightly' word perhaps make sense attached to the installer name to make clear it is nightly and not production or regular version.

I like the concept. I use many installers and need to name them myself as nightly.

**Comment by piotrzarzycki21** [comment] 2020-08-25 09:02
Where I can find Moonshine SDK installer to download ? Old link seems to provide still *.zip archive for Windows.

**Comment by rat-moonshine** [comment] 2020-08-25 09:23
Yeah.. the Bamboo build plan still needs to update its deploy detail. You can download a Windows version from here though, http://moonshine-ide.com/downloads/msdki/nsisTest/windows/MoonshineSDKInstaller-3.6.0.exe.

**Comment by JoelProminic** [comment] 2020-08-25 21:47
I reviewed the prompts again, and I have updated text below.

On a side note, I noticed that when the installer is running, it shows version 2.6.0 instead of the expected 3.0.0

![2020_08_25__Moonshine_InstallerStartup](https://user-images.githubusercontent.com/24532731/91231207-78b7b180-e6f2-11ea-818d-8c2674989fe8.png)

### Currently Running

![2020_08_25__Moonshine_AlreadyRunning](https://user-images.githubusercontent.com/24532731/91231226-81a88300-e6f2-11ea-9f8a-4da19c06fa2a.png)

The only required change I see is that the application name should be "Moonshine-IDE" rather than "Moonshine SDK Installer".

> Title:  Moonshine-IDE Setup
> 
> An instance of Moonshine-IDE is already running.  To you want to terminate the instance and continue?

### 32-bit version

![2020_08_25__Moonshine_32Bit](https://user-images.githubusercontent.com/24532731/91231258-8ec57200-e6f2-11ea-9b0b-229e89100309.png)

> Title: Moonshine-IDE Setup
> 
> This will install 64-Bit Moonshine-IDE on your system.
> 
> A 32-Bit version is currently installed.  You will need to uninstall the 32-bit version before you can install the new version.  Your settings and open projects will still be available in the new version.  Do you want to uninstall the old version now?

Note that I removed the "Yes" and "No" clarifications - I think these are unnecessary with the updated prompt.

Also note that the application name in the body was "Moonshine" instead of "Moonshine-IDE"

### Same version installed

![2020_08_25__SDKInstaller_SameVersion](https://user-images.githubusercontent.com/24532731/91231290-99800700-e6f2-11ea-939f-552b0a7402d7.png)

Change to:

> Title:  Moonshine-IDE Setup
>
> This version of Moonshine-IDE is already installed.  Do you want to run the current installation?
>
> Yes - Start Moonshine-IDE now
> No - Do a fresh install
> Cancel - Cancel this installation

**Comment by Aszusz** [comment] 2020-10-01 13:38
@JoelProminic 

> On a side note, I noticed that when the installer is running, it shows version 2.6.0 instead of the expected 3.0.0

In my tests this only happens during upgrade (2.6.0 -> 3.0.0). This is to be expected. Old installer is invoked to uninstall the old version. Then the new installer proceeds to install the new version.

**Comment by Aszusz** [comment] 2020-10-01 13:47
Tested Moonshine IDE 3.0.0 nightly from 01-Oct-2020 on Windows 10 64-bit.

Upgrade 2.6.0 -> 3.0.0 nightly
- [ ] - Moonshine IDE installation
- [ ] - SDK Installer installation
- [ ] - Apache Royale download
- [ ] - Complication of MyAccount

Clean install of 3.0.0 nightly
- [ ] - Moonshine IDE installation
- [ ] - SDK Installer installation
- [ ] - Apache Royale download
- [ ] - Complication of MyAccount

**Comment by rat-moonshine** [comment] 2020-10-01 15:15
> Complication of MyAccount

@Aszusz did you meant to say 'compilation of MyAccount'?

**Comment by Aszusz** [comment] 2020-10-01 19:46
@rat-moonshine 

> @Aszusz did you meant to say 'compilation of MyAccount'?

Yes, sorry and thanks for pointing this out. Updated.

**Comment by JoelProminic** [comment] 2020-10-02 18:52
I confirmed that the popup alerts were updated like I requested here: https://github.com/prominic/Moonshine-IDE/issues/713#issuecomment-680285981

I think the messages look look like this, so I am closing the issue.

**Closed by JoelProminic** 2020-10-02 18:52 UTC
Labels: Investigation, enhancement, in-progress, test-ready
