### ISSUE TITLE
Add right click menu support to define integration with other editors

### ISSUE THREAD

**Issue by JustinProminic** [prominic/Moonshine-IDE#677] opened 2020-03-05 01:14 UTC
The primary purpose of Moonshine has always been to rapidly configure user's computers to have access to very specific niche tools that are otherwise cumbersome to get setup on user's workstations.   We started with Flex, added Royale, and increased in complexity through Java, Groovy, PrimeFaces, and now Notes/Domino.

The repeated horrible experiences of even trying to do basic setups with Eclipse on Mac to have team SVN support led me to believe that attention to detail is lacking in other IDEs, and the responsibility is often shifted to the user to do the heavy lifting to explore whatever the niche technologies are they are interested in.

Providing a robust editor across all of these targets, especially with a variety of niches, is a challenge.  Eclipse, IntelliJ, and even SublimeText, TextMate, CotEditor, NotePad++, MacVim, etc. all become ingrained in people's lives.  The nuances of their editors are not something we can hope to replace.

While this does not mean I have given up on wanting to improve the Moonshine internal editor by any means, it is a problem we have to solve at least halfway in short order.

Therefore, I propose the following:

1) A new configuration wizard that will attempt to auto-detect and auto-setup access to the most common editors on each platform.

2) A new right click context menu which when the user selects any file can both access the aforementioned setup wizard above, as well as immediately trigger launch of the editor for the specific file.

I would like to support the following, but also ask that @Aszusz expand upon this list so that we cover the top 10 on each platform.  Here are the bare minimum:

Windows and Mac:
Eclipse
Visual Studio Code

Windows Only:
NotePad++
UltraEdit
Vim

Mac Only (include direct Mac App Store links for the download of these in the setup wizard please, as appropriate)
MacVim
SublimeText
TextMate
CotEditor
BBEdit
XCode
IAWriter (for Markdown)
Prettify XML
XML Inspector
XML Notepad

**Comment by JoelProminic** [comment] 2020-05-19 23:00
@JustinProminic asked about this again yesterday.  

We have discussed this as a simpler alternative to #654.  This will allow a user to quickly edit a file with a different editor, but a generically linked editor would not have access to the additional logic from the language server.

Is this something that could be quickly implemented and included in the 2.7.0 milestone?  I think the parts would be:
- Create a UI to allow the user to define the path (and command, if we can't rely on a consistent syntax for editors) for an external editor/application
- Populate the list with default entries for common applications Justin listed above, with the default paths and download links
- Add a context menu option allow the user to open the file in a selected editor.

**Comment by rat-moonshine** [comment] 2020-05-26 08:38
Here's some further requests from @JustinProminic on this related, 

> Indeed, I would like to get:
> 
> Vim
> Emacs
> Visual Studio Code
> TextMate
> Notepad++
> 
> All added to the right click menu...

**Comment by rat-moonshine** [comment] 2020-05-26 09:31
Here's an initial mockup for the discussion, 

![image](https://user-images.githubusercontent.com/24370870/82884658-a2313780-9f61-11ea-91a5-56f403455d4b.png)

Balsamiq file to edit,
[ExternalEditors.bmpr.zip](https://github.com/prominic/Moonshine-IDE/files/4681220/ExternalEditors.bmpr.zip)

**Comment by rat-moonshine** [comment] 2020-06-04 10:38
Test-matrix:

**macOS**
Editor | Opening a file to the editor | Default path
----------------------- | ------------ | ------------------
BBEdit | - | /Applications/BBEdit.app
Emacs | - | /Applications/Emacs.app
IAWriter | - | /Applications/IAWriter.app
Prettify XML | - | UNKNOWN DOWNLOAD LOCATION
Sublime Text | Works | /Applications/Sublime Text.app
TextMate | - | /Applications/TextMate.app
VIM | Works | /Applications/MacVim.app
Visual Studio Code | Works | /Applications/Visual Studio Code.app
Eclipse (tested with Flash Builder) | Works | UNKNOWN

**Windows**
Editor | Opening a file to the editor | Default path
----------------------- | ------------ | ------------------
VIM | - | -
Visual Studio Code | - | -
Notepad++ | - | -
UltraEdit | - | -
Eclipse | - | -

**Comment by JoelProminic** [comment] 2020-06-05 17:00
For extra arguments, the syntax is:

    # macOS
    open -a %app_path% %file_path% --args %args%

    # Windows
    %app_path% %file_path% %args%

Examples:
- macOS:  use the `--disable-extensions` argument with Visual Studio Code.  This will show a notice that extensions were disabled
- Windows:  use the `-R` option with gVim to enable read-only mode.

**Comment by JoelProminic** [comment] 2020-06-05 17:17
For IAWriter, I see this error in Moonshine when I open a .mxml file:

    : open -a '/Applications/iA Writer.app' '-snip-/src/MainContent.mxml'
    : LSOpenURLsWithRole() failed for the application /Applications/iA Writer.app with error -10820 for the file -snip-/src/MainContent.mxml.


But I get a much clearer error if I run it manually.  Do you know why this behaves differently?

    open -a /Applications/iA\ Writer.app/ -snip-/src/MainContent.mxml

![image](https://user-images.githubusercontent.com/24532731/83905015-875f7f80-a726-11ea-918b-9fe28da0392e.png)

**Comment by rat-moonshine** [comment] 2020-06-05 17:21
> I noticed that custom editor entries don't work until I restart Moonshine:
> 
> 1. Open Moonshine
> 2. Create a new custom editor
> 3. Save the Settings
> 4. Test the new editor - nothing happens
> 5. Restart Moonshine
> 6. Test the new editor - it works

This should be fixed by now.

**Comment by JoelProminic** [comment] 2020-06-05 17:43
I confirmed that the custom editor will work without a restart now.

**Comment by JoelProminic** [comment] 2020-06-09 17:10
1. Create a new Editor like this:
![image](https://user-images.githubusercontent.com/24532731/84178436-09fb7e00-aa4a-11ea-852d-62eb094a62d2.png)

2. This triggers an error for duplicate name
3. Change the name to "Visual Studio Code2"
4. Save the settings
5. Open the settings again.  BUG:  Visual Studio Code is missing:
![image](https://user-images.githubusercontent.com/24532731/84178453-11bb2280-aa4a-11ea-9525-4bdd60b9cc4e.png)

And I see a blank entry:
![image](https://user-images.githubusercontent.com/24532731/84178498-239cc580-aa4a-11ea-9fec-0c7322643551.png)

Note that Visual Studio Code2 is the "default" editor now.

6. Save and reopen the settings
7. Try to create a new editor with the same application path
8. BUG:  I get this error:

    : TypeError: Error #1009
    : 	at components.popup::ExternalEditorAddEditPopup/onSubmit()
    : 	at components.popup::ExternalEditorAddEditPopup/__btnCommit_click()




On later tests, I was able to simplify this test procedure even further:
1. Create a new Editor with a unique path (I tested with Eclipse)
2. Save the Editor - no errors
3. BUG:  Visual Studio Code was renamed to match the new application, and the blank entry appears in the application list.

**Comment by rat-moonshine** [comment] 2020-06-10 08:58
It turned out all those problems were caused by a silly error. That is rectified now. Adding, updating editors seems to be working fine now. Following is a test-matrix against my tests:

Editor Type | Behavior | Saved & Sorted Properly | Re-opened Properly
------------- | ------------------ | ------------- | ------------
Custom | Add | Yes | Yes
Custom | Modify "Title" | Yes | Yes
Custom | Modify "Path" | Yes | Yes
Default | Modify "Path" | Yes | Yes
Custom | Removed | Yes | Yes

I also did some tuning to saved object updation with newer editor updates. Following are my test-matrix on the same:

Editor Type | Behavior | Effect in Saved Editor
--------------- | ---------- | -------------- 
Default | Updated fields except "Path" | Updated all except "Path"
Default | Updated "Path" | Updated when no-path or invalid path
Default | Updated "Path" | Do not updates when an existing valid path
Custom | N/A | N/A
Default | Added new | Added to saved list
Default | Removed existing | No effect in the saved list

**Comment by JoelProminic** [comment] 2020-06-10 22:47
I created a custom editor for latest version of Eclipse (2020-03).  This worked fine for me on both macOS and Windows.

I also tested with the old version I have been using for my Java development (Luna 4.0).

Some of the language server features work in Eclipse, but it may be because I have some of the related projects open already.

Here are the default paths I saw in my tests:

Windows:  `C:\Users\<user>\eclipse\java-2020-03\eclipse\eclipse.exe`
MacOS:  `/Users/<user>/Documents/eclipse/java-2020-03/Eclipse.app`
Download URL:  https://www.eclipse.org/downloads/

Unfortunately, Eclipse has unusual behavior for the default install location:
- The default install location is under the user's home directory, rather than in Program Files or /Application.  See below for examples
- Eclipse has multiple variations that can be installed (Java, Java Enterprise Edition, etc).  Each one has a different subdirectory directory name, and the name also includes the version.  For example, "java-2020-03" for the Java installation, "jee-2020-03" for the Java Enterprise Edition installation.


I see that Visual Studio Code on Windows also installs to the user home directory by default, so we can use the same logic.

**Comment by rat-moonshine** [comment] 2020-06-11 06:00
> I noticed this problem while testing on Windows:
> 
> 1. Open File > Settings > External Editor
> 2. Update the path of VIM (in my case, it was installed under "Program Files (x86)")
> 3. Without saving the settings first, add a new editor for Eclipse and set a path
> 4. Save the settings
> 5. Open the settings again.  BUG:  VIM is set to use the same path as Eclipse
> 
> I see the same behavior if I first update the path for VIM and then update the path for my custom Eclipse entry.

This should have fixed now. Please, check.

**Comment by JoelProminic** [comment] 2020-06-11 17:30
I noticed this bug on Windows:
1. Open a file with an editor.  I reproduced this with all editors I had configured
1. The editor opens.   Leave this editor open
1. Try to open another file with any editor.  
1. BUG:  the console shows "Build is running. Wait for finish..."


    : "C:\Program Files (x86)\Vim\vim82\gvim.exe" "C:\Flex\temp_workspace\TestRoyale_0529\build\build.xml"
    : "C:\Program Files (x86)\Vim\vim82\gvim.exe" "C:\Flex\temp_workspace\TestRoyale_0529\src\MainContent.mxml"
    : Build is running. Wait for finish...

**Comment by JoelProminic** [comment] 2020-06-11 17:33
I also noticed that the paths were cleared for all custom editors on macOS when I installed the latest build.   This custom application was also impossible to disable:

![image](https://user-images.githubusercontent.com/24532731/84420429-a30fcd80-abdf-11ea-9a94-c1afe04a09f5.png)

I sent @rat-moonshine my `#SharedObjects` directory to help debug this.  I couldn't reproduce the issue when running the same installer again.

**Comment by rat-moonshine** [comment] 2020-06-12 08:41
The Windows problem should have resolved now. 

I tried to look into the `#SharedObjects` sent by @JoelProminic . It appears that both the custom Eclipse entries have install-path value and they remain to show appropriately when Moonshine opens. However, I able to reproduce the invalid but enabled-checkbox Joel reported for a particular application:

![image](https://user-images.githubusercontent.com/24370870/84483004-52b76f00-acb6-11ea-94f8-5a0a1615d1da.png)

It seems that somehow the 'isValid' property saved as `true` when install-path is `null`. I couldn't able to reproduce the situation that Joel encountered once, though. 

I added some handling in Moonshine, this should effectively make an application disabled now. Please, check.

**Comment by rat-moonshine** [comment] 2020-06-12 17:40
Some generation-dependencies as suggested by @JoelProminic for my references,

> Most of the options should work the same way they do for the Domino form.
> Type and Multivalue will determine the control.
> Editable will determine if the field should be editable in the UI. I think we'll want the formula to be executed on the agent side only.
> Include in View, Sort Options - These fields should determine which fields appear in the main list, and the sorting to use.

Fields can be referred from here https://github.com/prominic/Moonshine-IDE/issues/670#issue-571561798.

**Comment by JoelProminic** [comment] 2020-06-15 17:13
I can now open multiple files with the same editor on Windows.  I did notice that the editors didn't work when Moonshine was launched from the installer, but this was related to the Active Directory profile on my machine.  I created a separate issue here:  #707

@rat-moonshine and I found that the custom editor paths were cleared when I installed a different build of Moonshine which did not have the custom editor code, and then reinstalled a build for this issue.   This probably won't matter for normal users, but it may indicate some other problems in the code.   @rat-moonshine made an update for this, and the problem did not trigger for me when I tried again.

**Comment by JoelProminic** [comment] 2020-06-17 16:20
This is ready to be merged.   I would still like to go through and verify the download links, but the core logic seems to work well.   I tested Eclipse on macOS (including an older version) and Windows.

**Comment by rat-moonshine** [comment] 2020-06-18 05:05
The issue is now merged into 'master'.

**Comment by JoelProminic** [comment] 2020-06-24 16:31
This seems to be working in master now - I did some quick tests on macOS.

**Closed by JoelProminic** 2020-06-24 16:31 UTC
Labels: enhancement, test-ready
